<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    index.phtml
// Created: 2015-11-23 23:02:02
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<h1 class="success">Help sections</h1>
<div class="row">
    <?php
    foreach ($help as $section => $ds) {
            printf("<div class=\"col-lg-3 col-md-3 col-sm-3\">\n");
            foreach ($help as $section => $ds) {
                    printf("<a href=\"%s/%s\" title=\"Click to display more manuals in various formats and translations\">\n", $base, $section);
                    printf("<h2>%s</h2>\n", $ds['name']);
                    printf("<img src=\"%s\" style=\"padding-bottom:15px\" />\n", $icon);
                    printf("</a>\n");
                    printf("<ul>\n");
                    foreach ($ds['data'] as $target => $dt) {
                            printf("<li><a href=\"%s/%s/%s\">%s</a></li>\n", $base, $section, $target, $dt['name']);
                    }
                    printf("<br/><li><a href=\"%s/%s\">Other formats and translations...</a></li>\n", $base, $section);
                    printf("</ul>\n");
            }
            printf("</div>\n");
    }

    ?>            
</div>
<br><hr/>    
<p>If you see this page, then you might have ended up on this page by misstake. Please follow one of the links above to access desired content.</p>
