<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    index.phtml
// Created: 2015-11-23 23:02:02
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<h1 class="success">Help sections</h1>
<div class="row">
    <?php
    foreach ($help as $section => $ds) {
            printf("<div class=\"col-lg-3 col-md-3 col-sm-3\">\n");
            foreach ($help as $section => $ds) {
                    printf("<a href=\"%s/%s\" title=\"Click to display more manuals in various formats and translations\">\n", $base, $section);
                    printf("<h2>%s</h2>\n", $ds['name']);
                    printf("<img src=\"%s\" style=\"padding-bottom:15px\" />\n", $icon);
                    printf("</a>\n");
                    printf("<ul>\n");
                    foreach ($ds['data'] as $target => $dt) {
                            printf("<li><a href=\"%s/%s/%s\">%s</a></li>\n", $base, $section, $target, $dt['name']);
                    }
                    printf("<br/><li><a href=\"%s/%s\">Other formats and translations...</a></li>\n", $base, $section);
                    printf("</ul>\n");
            }
            printf("</div>\n");
    }

    ?>            
</div>
<br><hr/>    
<p>If you see this page, then you might have ended up on this page by misstake. Please follow one of the links above to access desired content.</p>
