<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    index.phtml
// Created: 2015-11-23 23:02:33
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<h1 class="success">Manuals</h1>
<div class="row">
    <?php
    foreach ($manual as $section => $data) {
            printf("<div class=\"span3\">\n");
            printf("<a href=\"%s/manual/%s\">\n", $base, $section);
            printf("<h2>%s</h2>\n", $data['name']);
            printf("<img src=\"%s\" style=\"padding-bottom:15px\" />\n", $icon);
            printf("</a>");
            printf("<ul>\n");
            foreach ($data['data'] as $format => $name) {
                    printf("<li>\n");
                    printf("<a href=\"%s/manual/%s/%s/%s\">%s</a>\n", $base, $section, $data['lang'][0], $format, $name);
                    if (count($data['lang']) > 1) {
                            $links = array();
                            foreach ($data['lang'] as $language) {
                                    $links[] = sprintf("<a href=\"%s/manual/%s/%s/%s\">%s</a>", $base, $section, $language, $format, ucfirst($language));
                            }
                            printf("<br/>[%s]", implode(", ", $links));
                    }
                    printf("</li>\n");
                    printf("<br/>\n");
            }
            printf("</ul>\n");
            printf("</div>\n");
    }

    ?>            
</div>
<br><hr/>    
<p>If you see this page, then you might have ended up on this page by misstake. Please follow one of the links above to access desired content.</p>
