<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    question-info.phtml
// Created: 2017-08-18 16:28:17
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<style>
    div.question-info-section {
        margin-top: 5px;
        padding: 10px; 
        background-color: white;
    }
    
    span.question-corrector {
        padding-right: 8px;
    }
</style>

<td title="Corrected: <?= $corrected ?> Percent: <?= $percent ?>%" class="cc aa">
    <span style="white-space: nowrap;"><?= $avarage ?> (<?= floatval($question->score) ?>)</span>
    <div>
        <button class='q-info-btn btn btn-default no-print' style="white-space: nowrap;"><i class="fa fa-battery-<?= intval($percent / 25) ?> fa-rotate-270"></i> More</button>
        <div style="display: none">
            <div class="correction-status">
                <b>Correction status</b>
                <div class='question-info-section'>
                    Answers corrected: <?= $corrected ?><br>
                    Percent of max score: <?= $percent ?>%
                </div>
            </div>
            <hr>
            <div class="question-correctors">
                <b>Question corrector's</b>
                <?php $correctors = array(); ?>
                <div class='question-info-section'>
                    <?php foreach ($question->correctors as $corrector): ?>
                            <span class="question-corrector">
                                <?php foreach ($corrector->mail as $mail): ?>
                                        <?php array_push($correctors, sprintf("%s <%s>", $corrector->name, $mail)); ?>
                                <?php endforeach; ?>
                                <i class="fa fa-user"></i>
                                <a href="mailto:<?= implode(",", $corrector->mail) ?>"><?= $corrector->name ?></a>
                            </span>
                    <?php endforeach; ?>
                </div>
                <br>
                <a href="mailto:<?= implode(',', $correctors) ?>" class="btn btn-success btn-sm no-print">
                    <i class="fa fa-envelope"></i> 
                    <span>Contact All</span>
                </a>                
            </div>
        </div>
    </div>
</td>
