<?php
/*
 * Copyright (C) 2017-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    question-info.phtml
// Created: 2017-08-18 16:28:17
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<style>
    div.question-info-section {
        margin-top: 5px;
        padding: 10px; 
        background-color: white;
    }
    
    span.question-corrector {
        padding-right: 8px;
    }
</style>

<td title="Corrected: <?= $corrected ?> Percent: <?= $percent ?>%" class="cc aa">
    <span style="white-space: nowrap;"><?= $avarage ?> (<?= floatval($question->score) ?>)</span>
    <div>
        <button class='q-info-btn btn btn-default no-print' style="white-space: nowrap;"><i class="fa fa-battery-<?= intval($percent / 25) ?> fa-rotate-270"></i> More</button>
        <div style="display: none">
            <div class="correction-status">
                <b>Correction status</b>
                <div class='question-info-section'>
                    Answers corrected: <?= $corrected ?><br>
                    Percent of max score: <?= $percent ?>%
                </div>
            </div>
            <hr>
            <div class="question-correctors">
                <b>Question corrector's</b>
                <?php $correctors = array(); ?>
                <div class='question-info-section'>
                    <?php foreach ($question->correctors as $corrector): ?>
                            <span class="question-corrector">
                                <?php foreach ($corrector->mail as $mail): ?>
                                        <?php array_push($correctors, sprintf("%s <%s>", $corrector->name, $mail)); ?>
                                <?php endforeach; ?>
                                <i class="fa fa-user"></i>
                                <a href="mailto:<?= implode(",", $corrector->mail) ?>"><?= $corrector->name ?></a>
                            </span>
                    <?php endforeach; ?>
                </div>
                <br>
                <a href="mailto:<?= implode(',', $correctors) ?>" class="btn btn-success btn-sm no-print">
                    <i class="fa fa-envelope"></i> 
                    <span>Contact All</span>
                </a>                
            </div>
        </div>
    </div>
</td>
