<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    resource-file-viewer.phtml
// Created: 2017-09-20 19:32:06
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

/**
 * This partial accepts these parameters passed from view:
 * 
 *      path    -> the resource file path on disk
 *      href    -> the resource URL
 *      type    -> the mime type (i.e. array('application', 'pdf'))
 *      name    -> the resource name
 *      hide    -> forge resource (i.e. array('image' => 'blur'))
 */

?>

<div class="resource-file-box" style="margin-bottom: 10px; border-radius: 3px; width: 290px; padding: 3px; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.2), 0 5px 20px 0 rgba(0, 0, 0, 0.2);">
    <?php
    if (!isset($type) || !is_array($type)) {
            if (file_exists("$path")) {
                    $mime = mime_content_type("$path");
                    $type = explode("/", $mime);
            } else {
                    $mime = "application/octet-stream";
                    $type = explode("/", $mime);
            }
    }

    if (empty($name)) {
            $name = basename($path);
    }
    if (!isset($hide)) {
            $hide = array();
    }
    if (isset($hide[$type[0]])) {
            $name = sprintf("%s (%s)", ucfirst($type[0]), strtoupper($type[1]));
    }

    switch ($type[0]) {
            case 'audio':
                    $icon = 'file-audio-o';
                    $desc = 'Download audio file';
                    break;
            case 'video':
                    $icon = 'file-video-o';
                    $desc = 'Download video file';
                    break;
            case 'image':
                    $icon = 'file-image-o';
                    $desc = 'Download image file';
                    break;
            case 'application':
                    switch ($type[1]) {
                            case 'pdf':
                                    $icon = 'file-pdf-o';
                                    $desc = 'Download PDF';
                                    break;
                            case 'vnd.oasis.opendocument.spreadsheet':
                            case 'octet-stream':
                            case 'vnd.ms-office':
                                    $icon = 'file-excel-o';
                                    $desc = 'Download spreadsheet';
                                    break;
                            case 'vnd.openxmlformats-officedocument.wordprocessingml.document':
                            case 'vnd.oasis.opendocument.text':
                            case 'msword':
                                    $icon = 'file-word-o';
                                    $desc = 'Download text document';
                                    break;
                            case 'vnd.openxmlformats-officedocument.presentationml.presentation':
                            case 'vnd.oasis.opendocument.presentation':
                            case 'vnd.ms-powerpoint':
                                    $icon = 'file-powerpoint-o';
                                    $desc = 'Download presentation';
                                    break;
                            case 'zip':
                            case 'x-gzip':
                            case 'java-archive':
                                    $icon = 'file-archive-o';
                                    $desc = 'Download archive file';
                                    break;
                    }
                    break;
    }

    ?>

    <?php if (isset($hide[$type[0]]) && $hide[$type[0]] == 'hide') : ?>
            <div style="position: relative">
                <img src="<?= $url->get('img/pexels-photo-87216-camera.jpeg') ?>" style="max-width:100%">
                <div class="resource-file-hidden">
                    <h3>The media content has been hidden on request from teacher</h3>
                </div>
            </div>
            <?php $href = '#' ?>
    <?php else : ?>
            <?php if ($type[0] == 'video') : ?>
                    <video
                        id="my-player"
                        class="video-js"
                        controls
                        preload="auto"
                        poster="<?= $url->get('img/pexels-photo-318540-video.jpeg') ?>"
                        width="284" height="215"
                        data-setup='{}'>
                        <source src="<?= $href ?>" type="<?= $mime ?>"></source>
                        <p class="vjs-no-js">
                            To view this video file please enable JavaScript, and consider upgrading to a
                            web browser that
                            <a href="http://videojs.com/html5-video-support/" target="_blank">
                                supports HTML5 video/audio
                            </a>
                        </p>
                    </video>
            <?php elseif ($type[0] == 'audio') : ?>
                    <audio
                        id="my-player"
                        class="video-js"
                        controls
                        preload="auto"
                        poster="<?= $url->get('img/pexels-photo-144429-audio.jpeg') ?>"
                        width="290" height="215"
                        data-setup='{}'>
                        <source src="<?= $href ?>" type="<?= $mime ?>"></source>
                        <p class="vjs-no-js">
                            To listen to this audio file please enable JavaScript, and consider upgrading to a
                            web browser that
                            <a href="http://videojs.com/html5-video-support/" target="_blank">
                                supports HTML5 audio/audio
                            </a>
                        </p>
                    </audio>
            <?php elseif ($type[0] == 'image') : ?>
                    <?php if (isset($hide[$type[0]]) && $hide[$type[0]] == 'blur') : ?>
                            <svg width="100%" height="250px"> 
                            <defs> 
                            <filter id="blur"> 
                                <feGaussianBlur stdDeviation="8" /> 
                            </filter> 
                            </defs> 
                            <image xlink:href="<?= $href ?>" y="0px" x="15px" width="250px" height="250px" filter="url(#blur)">  
                            </image> 
                            </svg>                                                                                                
                            <div class="resource-file-blurred">The media content has been blurred on request from teacher</div>
                            <?php $href = '#' ?>
                    <?php else : ?>
                            <img class="img-zoom" src="<?= $href ?>" data-zoom-image="<?= $href ?>" style="background-color:#f9f9f9; max-width:100%;">
                    <?php endif; ?>
            <?php else : ?>
                    <div>
                        <a class="fancybox" rel="fancybox" href="<?= $href ?>" title="<?= $name ?>">
                            <a class="media {width:284}" href="<?= $href ?>"></a> 
                        </a>    
                    </div>
            <?php endif; ?>
    <?php endif; ?>

    <div class="resource-title" style="padding: 5px">
        <a href="<?= $href ?>" title="<?= $desc ?>" style="text-decoration: none">
            <small class="text-muted" style="vertical-align: central">
                <i class="fa fa-<?= $icon ?> fa-2x"></i> 
                <?= $name ?>
            </small> <br />
        </a>
    </div>
</div>
