<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?= Phalcon\Tag::stylesheetLink("css/font-awesome.css"); ?>
        <title><?= $exam->name ?></title>
    </head>
    <style>

        body {
            margin:0px; background-color:#F8F8F8; font-family:Verdana, Geneva, sans-serif; font-size:13px
        }

        .header {
            margin-left:3%; 
            background-color:#C91F3C; 
            width:10%;
        }
        .body {
            left: -50%; position: relative; text-align: left;

        }
        .body-content {
            left: 50%; 
            position:relative; 
            background: rgba(255, 255, 255, 0.95);
            height: 100%;
        }
        .main-box {
            left: 50%; 
            position:relative; 
            background: rgba(255, 255, 255, 0.9);
            border-radius:5px; 
            border: 5px solid #f0f0f0; 
            padding:30px; 
            -webkit-box-shadow: 0px 0px 10px 1px rgba(206,206,206,1);
            -moz-box-shadow: 0px 0px 10px 1px rgba(206,206,206,1);
            box-shadow: 0px 0px 10px 1px rgba(206,206,206,1);
        }
        h1 {
            font-weight:normal; 
            border-bottom: 1px solid #bebebe; 
            font-size:22px; 
            color:#990000
        }
        h2 {
            font-weight:normal;
        }
        table {
            padding:5px;
            margin:25px;
        }
        td,th {
            text-align:right;
            padding-right:25px;
            font-size:13px
        }

        .summary-row td {
            border-top:1px dashed #bebebe;
        }

        .uu-color {
            color:#797C80;
        }
        .quest-part {
            padding:5px; 
            border:1px solid #dedede; 
            background-color:white; 
            margin-bottom:15px
        }
        .quest-part h2 {
            border-bottom:1px solid #990000;
        }
        .page-first {
            background:url("<?= $this->url->get("img/seal.png") ?>") no-repeat scroll 80px 30px transparent;
        }
        .page-inner {
            background:url("<?= $this->url->get("img/seal.png") ?>") center center / 600px 600px no-repeat scroll padding-box transparent;
        }
        .page {
            page-break-after: always !important;
            min-height: 270mm;
            min-width: 200mm;
            border-top:5px solid #990000; 
        }
        .blue-txt {
            font-size:14px;
            color:#3d749b
        }
        .blurred {
            font-size: 1.1em;
            color: #bbbbbb;
            width: 100%;
            text-align: center;
            margin-bottom: 10px;
        }
        .resource-wrapper,
        .resource-file-box {
            background-color: white;
            display: inline-block;
            border-radius: 5px;
            box-shadow: 1px 2px 15px grey;
            margin: 5px;
            width: 45%;
        }
        .resource-content {
            padding: 10px;
            display: inline-block;
        }
        .resource-title a {
            color: grey;
            margin-bottom: 5px;
        }
        .resource-image {
            border: 1px dashed #bebebe;
            display: inline-block;
        }
    </style>

    <body>
        <script type="text/x-mathjax-config">
            MathJax.Hub.Config({
            extensions: ["tex2jax.js"],
            jax: ["input/TeX","output/HTML-CSS"],
            tex2jax: {inlineMath: [["$","$"],["\\(","\\)"]]}
            });
        </script>
        <?= Phalcon\Tag::javascriptInclude('js/mathjax/MathJax.js'); ?>

        <?php

        use OpenExam\Models\Exam;

        ?>

        <!-- Main page -->
        <div class="page page-first" style='min-height: 1017px; border-bottom:none' >
            <div class="header">
                <div>
                    <img src="<?= $this->url->get("img/Logo_UU.jpg") ?>" style="width:200%; z-index: 0" />
                </div>
            </div>
            <div class="body" style="float: right;  margin-top: 35%; margin-left: 10%;">
                <div class="main-box">
                    <h1><?= $exam->name ?></h1>
                    <div>
                        <span style="color:#000; font-size:14px"><?= $exam->orgunit ?></span>
                    </div>
                    <div>
                        <small>
                            <span style="color:#797C80">Exam held on: <?= date("Y-m-d", strtotime($exam->starttime)) ?> (<?= date("H:i", strtotime($exam->starttime)) ?>&mdash;<?= date("H:i", strtotime($exam->endtime)) ?>)</span><br />
                        </small>
                    </div>
                    <div style="margin-top:35px">
                        <center>
                            <h3 style="text-align: left">
                                <span style="color:#3d749b">Name | Code:</span>
                            </h3>
                        </center>
                    </div>
                </div>         
            </div>
        </div>

        <!-- Description page -->   
        <div class="page page-inner">
            <div class="body" >
                <div class="body-content" style="height:950px">
                    <h1>Exam description</h1>
                    <div>
                        <div>
                            <?= $exam->descr ?>
                        </div>
                    </div>
                </div>         
            </div>
        </div>

        <!-- Question pages -->
        <?php foreach ($data['questions'] as $questNo => $question): ?>
                <div class="page page-inner">
                    <div class="body" >
                        <div class="body-content">
                            <div class="quest">
                                <h1 class="q-<?= $question->id ?>">Question <?= $question->slot ?> </h1>

                                <?php foreach ($data['qData'][$question->id]['qParts'] as $pTitle => $pData): ?>
                                        <div class="quest-part">
                                            <?php if (count($data['qData'][$question->id]['qParts']) > 1): ?>
                                                    <h2>Part <?= $pTitle ?></h2>
                                            <?php endif; ?>
                                            <div style="padding: 10px 20px 0px 20px;">

                                                <!-- resources -->
                                                <?php foreach ($pData['resources'] as $resTitle => $resUrl): ?>
                                                        <div class="resource-file-box" style="margin-bottom: 10px; border-radius: 3px; width: 325px; padding: 5px; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.2), 0 5px 20px 0 rgba(0, 0, 0, 0.2);">
                                                            <?php
                                                            $type = basename(dirname($resUrl)) . 's';
                                                            $path = $this->config->application->mediaDir . $type . DIRECTORY_SEPARATOR . basename(urldecode($resUrl));

                                                            if (file_exists($path)) {
                                                                    $mime = mime_content_type($path);
                                                                    $type = explode("/", $mime);
                                                            } else {
                                                                    $mime = "application/octet-stream";
                                                                    $type = explode("/", $mime);
                                                            }

                                                            switch ($type[0]) {
                                                                    case 'audio':
                                                                            $icon = 'file-audio-o';
                                                                            $desc = 'Download audio file';
                                                                            break;
                                                                    case 'video':
                                                                            $icon = 'file-video-o';
                                                                            $desc = 'Download video file';
                                                                            break;
                                                                    case 'image':
                                                                            $icon = 'file-image-o';
                                                                            $desc = 'Download image file';
                                                                            break;
                                                                    case 'application':
                                                                            switch ($type[1]) {
                                                                                    case 'pdf':
                                                                                            $icon = 'file-pdf-o';
                                                                                            $desc = 'Download PDF';
                                                                                            break;
                                                                                    case 'vnd.oasis.opendocument.spreadsheet':
                                                                                    case 'octet-stream':
                                                                                    case 'vnd.ms-office':
                                                                                            $icon = 'file-excel-o';
                                                                                            $desc = 'Download spreadsheet';
                                                                                            break;
                                                                                    case 'vnd.openxmlformats-officedocument.wordprocessingml.document':
                                                                                    case 'vnd.oasis.opendocument.text':
                                                                                    case 'msword':
                                                                                            $icon = 'file-word-o';
                                                                                            $desc = 'Download text document';
                                                                                            break;
                                                                                    case 'vnd.openxmlformats-officedocument.presentationml.presentation':
                                                                                    case 'vnd.oasis.opendocument.presentation':
                                                                                    case 'vnd.ms-powerpoint':
                                                                                            $icon = 'file-powerpoint-o';
                                                                                            $desc = 'Download presentation';
                                                                                            break;
                                                                                    case 'zip':
                                                                                    case 'x-gzip':
                                                                                    case 'java-archive':
                                                                                            $icon = 'file-archive-o';
                                                                                            $desc = 'Download archive file';
                                                                                            break;
                                                                            }
                                                                            break;
                                                            }

                                                            ?>
                                                            <?php if ($type[0] == 'video') : ?>
                                                                    <video
                                                                        id="my-player"
                                                                        class="video-js"
                                                                        controls
                                                                        preload="auto"
                                                                        poster="<?= $this->url->get('img/pexels-photo-318540-video.jpeg') ?>"
                                                                        width="325" height="240"
                                                                        data-setup='{}'>
                                                                        <source src="<?= $resUrl ?>" type="<?= $mime ?>"></source>
                                                                        <p class="vjs-no-js">
                                                                            To view this video file please enable JavaScript, and consider upgrading to a
                                                                            web browser that
                                                                            <a href="http://videojs.com/html5-video-support/" target="_blank">
                                                                                supports HTML5 video/audio
                                                                            </a>
                                                                        </p>
                                                                    </video>
                                                            <?php elseif ($type[0] == 'audio') : ?>
                                                                    <audio
                                                                        id="my-player"
                                                                        class="video-js"
                                                                        controls
                                                                        preload="auto"
                                                                        poster="<?= $this->url->get('img/pexels-photo-144429-audio.jpeg') ?>"
                                                                        width="325" height="240"
                                                                        data-setup='{}'>
                                                                        <source src="<?= $resUrl ?>" type="<?= $mime ?>"></source>
                                                                        <p class="vjs-no-js">
                                                                            To listen to this audio file please enable JavaScript, and consider upgrading to a
                                                                            web browser that
                                                                            <a href="http://videojs.com/html5-video-support/" target="_blank">
                                                                                supports HTML5 audio/audio
                                                                            </a>
                                                                        </p>
                                                                    </audio>
                                                            <?php elseif ($type[0] == 'image') : ?>
                                                                    <img src="<?= $resUrl ?>" style=" background-color:#f9f9f9; max-width:100%;">
                                                            <?php else : ?>
                                                                    <div>
                                                                        <a class="fancybox" rel="fancybox" href="<?= $resUrl ?>" title="<?= $resTitle ?>">
                                                                            <a class="media {width:320}" href="<?= $resUrl ?>"></a> 
                                                                        </a>    
                                                                    </div>
                                                            <?php endif; ?>

                                                            <div class="resource-title" style="padding: 5px">
                                                                <a href="<?= $resUrl ?>" title="<?= $desc ?>" style="text-decoration: none">
                                                                    <small class="text-muted" style="vertical-align: central">
                                                                        <i class="fa fa-<?= $icon ?> fa-2x"></i> 
                                                                        <?= $resTitle ?>
                                                                    </small> <br />
                                                                </a>
                                                            </div>
                                                        </div>

                                                <?php endforeach; ?>

                                                <div style="padding: 20px 0; font-size:14px">
                                                    <?= $pData['q_text'] ?>
                                                    <?php if ($pData["ans_area"]["type"] == 'choicebox'): ?>
                                                            <?php $correctAnsArr = array(); ?>
                                                            <ul>
                                                                <?php foreach ($pData["ans_area"]["data"] as $opt => $isCorrect): ?>
                                                                        <li><?= $opt ?></li>       
                                                                <?php endforeach; ?>
                                                            </ul>
                                                    <?php endif; ?>
                                                </div>

                                                <?php if (isset($data['results'][$student->id][$question->id]["comments"]) && !empty($data['results'][$student->id][$question->id]["comments"])): ?>
                                                        <div style="padding-bottom: 20px;">
                                                            <div class="blue-txt"> Teacher's comments:</div> 
                                                            <div class="uu-color"><?= nl2br($data['results'][$student->id][$question->id]["comments"]) ?></div>
                                                        </div>
                                                <?php endif; ?>

                                                <?php if ($data['qData'][$question->id]['qParts'][$pTitle]['q_points'] > 0) : ?>
                                                        <div style="padding-bottom: 20px;">
                                                            <div style="font-size:14px; color: grey"> 
                                                                <span>Max score: <?= floatval($data['qData'][$question->id]['qParts'][$pTitle]['q_points']) ?></span>
                                                            </div> 
                                                        </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                <?php endforeach; ?>
                            </div>
                        </div>         
                    </div>
                </div>
        <?php endforeach; ?>

        <!-- Reference page -->
        <div class="page page-inner">
            <div class="body" >
                <div class="body-content" style="height:950px">
                    <h1>Reference</h1>
                    <div style="margin-top:15px">
                        <span style="font-size:15px; color:#3d749b">Responsable for examination:</span><br>
                        <span class="uu-color">Main responsible person for the examination is <a href="mailto:<?= $this->catalog->getMail($exam->creator) ?>" style="color:#990000; text-decoration:none"><?= $this->catalog->getName($exam->creator) ?></a></span><br>
                    </div>
                </div>	
            </div>
        </div>
    </body>
</html>
