<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    archive.phtml
// 
// Author:  Ahsan Shahzad (Medfarm DoIT)
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?= Phalcon\Tag::stylesheetLink("css/font-awesome.css"); ?>
        <?= Phalcon\Tag::stylesheetLink("css/pdf-rendering.css"); ?>
        <title><?= $exam->name ?></title>
    </head>

    <style>
        .page-first {
            background:url("<?= $this->url->get($this->config->brand->logo->seal) ?>") no-repeat scroll 80px 30px transparent;
        }
        .page-inner {
            background:url("<?= $this->url->get($this->config->brand->logo->seal) ?>") no-repeat scroll 100px 200px transparent;
        }
    </style>

    <body>
        <script type="text/x-mathjax-config">
            var mathjax_typeset_finished = false;

            MathJax.Hub.Config({
            extensions: ["tex2jax.js"],
            jax: ["input/TeX", "output/HTML-CSS"],
            tex2jax: {inlineMath: [["$", "$"], ["\\(", "\\)"]]}
            });

            MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
            MathJax.Hub.Queue(function () {
            mathjax_typeset_finished = true;
            });
        </script>
        <?= Phalcon\Tag::javascriptInclude('js/mathjax/MathJax.js'); ?>

        <!-- Main page -->
        <div class="page page-first" style='min-height: 1017px; border-bottom:none' >
            <div class="header">
                <div>
                    <img src="<?= $this->url->get($this->config->brand->logo->file) ?>" style="width:200%; z-index: 0" />
                </div>
            </div>
            <div class="body" style="float: right;  margin-top: 35%; margin-left: 10%;">
                <div class="main-box">
                    <h2><?= $exam->name ?></h2>
                    <div>
                        <span style="color:#000; font-size:14px"><?= $exam->orgunit ?></span>
                    </div>
                    <div>
                        <small>
                            <span style="color:#797C80">Exam held on: <?= date("Y-m-d", strtotime($exam->starttime)) ?> (<?= date("H:i", strtotime($exam->starttime)) ?>&mdash;<?= date("H:i", strtotime($exam->endtime)) ?>)</span><br />
                        </small>
                    </div>
                    <div style="margin-top:35px">
                        <center>
                            <h3 style="text-align: left">
                                <span style="color:#3d749b">Name | Code:</span>
                            </h3>
                        </center>
                    </div>
                </div>         
            </div>
        </div>

        <!-- Description page -->   
        <div class="page page-inner">
            <div class="body" >
                <div class="body-content" style="height:950px">
                    <h2>Exam description</h2>
                    <div>
                        <div>
                            <?= $exam->descr ?>
                        </div>
                    </div>
                </div>         
            </div>
        </div>

        <!-- Question pages -->
        <?php if (is_array($data['questions'])) : ?>
                <?php foreach ($data['questions'] as $questNo => $question): ?>
                        <div class="page page-inner">
                            <div class="body" >
                                <div class="body-content">
                                    <div class="quest">
                                        <h2 class="q-<?= $question->id ?>">Question <?= $question->slot ?> </h2>

                                        <?php foreach ($data['qData'][$question->id]['qParts'] as $pTitle => $pData): ?>
                                                <div class="quest-part">
                                                    <?php if (count($data['qData'][$question->id]['qParts']) > 1): ?>
                                                            <h2>Part <?= $pTitle ?></h2>
                                                    <?php endif; ?>
                                                    <div style="padding: 10px 20px 0px 20px;">

                                                        <!-- resources -->
                                                        <?php
                                                        foreach ($pData['resources'] as $resTitle => $resUrl) {
                                                                $type = basename(dirname($resUrl));
                                                                $path = $this->config->application->mediaDir . $type . DIRECTORY_SEPARATOR . basename(urldecode($resUrl));
                                                                $href = $this->url->get($resUrl);
                                                                $name = $resTitle;

                                                                // 
                                                                // Use resource viewer:
                                                                // 
                                                                $this->partial('partials/resource-file-viewer', array(
                                                                        'type' => $type, 'path' => $path,
                                                                        'href' => $href, 'name' => $name,
                                                                        'url'  => $this->url
                                                                ));
                                                        }

                                                        ?>

                                                        <div style="padding: 20px 0; font-size:14px">
                                                            <?= $pData['q_text'] ?>
                                                            <?php if ($pData["ans_area"]["type"] == 'choicebox'): ?>
                                                                    <?php $correctAnsArr = array(); ?>
                                                                    <ul>
                                                                        <?php foreach ($pData["ans_area"]["data"] as $opt => $isCorrect): ?>
                                                                                <li><?= $opt ?></li>       
                                                                        <?php endforeach; ?>
                                                                    </ul>
                                                            <?php endif; ?>
                                                        </div>

                                                        <?php if (isset($data['results'][$student->id][$question->id]["comments"]) && !empty($data['results'][$student->id][$question->id]["comments"])): ?>
                                                                <div style="padding-bottom: 20px;">
                                                                    <div class="blue-txt"> Teacher's comments:</div> 
                                                                    <div class="uu-color"><?= nl2br($data['results'][$student->id][$question->id]["comments"]) ?></div>
                                                                </div>
                                                        <?php endif; ?>

                                                        <?php if ($data['qData'][$question->id]['qParts'][$pTitle]['q_points'] > 0) : ?>
                                                                <div style="padding-bottom: 20px;">
                                                                    <div style="font-size:14px; color: grey"> 
                                                                        <span>Max score: <?= floatval($data['qData'][$question->id]['qParts'][$pTitle]['q_points']) ?></span>
                                                                    </div> 
                                                                </div>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                        <?php endforeach; ?>
                                    </div>
                                </div>         
                            </div>
                        </div>
                <?php endforeach; ?>
        <?php endif; ?>

        <!-- Reference page -->
        <div class="page page-inner">
            <div class="body" >
                <div class="body-content" style="height:950px">
                    <h2>Reference</h2>
                    <div style="margin-top:15px">
                        <span style="font-size:15px; color:#3d749b">Responsable for examination:</span><br>
                        <span class="uu-color">Main responsible person for the examination is <a href="mailto:<?= $this->catalog->getMail($exam->creator) ?>" style="color:#990000; text-decoration:none"><?= $this->catalog->getName($exam->creator) ?></a></span><br>
                    </div>
                </div>	
            </div>
        </div>

        <script>
                document.addEventListener("DOMContentLoaded", function (event) {
                    setTimeout(function () {
                        var timer = setInterval(function () {
                            if (mathjax_typeset_finished) {
                                clearInterval(timer);
                                window.status = "content-loaded";       // PDF rendering
                            }
                        }, 1000);
                    }, 3000);
                });
        </script>

    </body>
</html>
