<?php

use OpenExam\Library\Core\Exam\Check;
use OpenExam\Library\Core\Exam\State;

/*
 * Copyright (C) 2016-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    details.phtml
// Created: 2016-10-27 22:41:32
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

if ($this->user->roles->isStudent($exam->id)) {
        $exam->show_state = true;
        $exam->show_staff = false;
        $exam->show_roles = false;
        $exam->show_other = true;
        $exam->show_grade = true;
} else {
        $exam->show_state = true;
        $exam->show_staff = true;
        $exam->show_roles = true;
        $exam->show_other = true;
        $exam->show_grade = true;
}

?>

<style>
    .exam-properties {
        -webkit-column-count: 2; /* Chrome, Safari, Opera */
        -moz-column-count: 2; /* Firefox */
        column-count: 2;
    }
    .exam-details {
        border: 1px solid #eeeeee;
        border-radius: 5px;
        margin-top: 30px;
        background-color: #ffffff;
    }
    .exam-details .header {
        background-color: #666699;
        border-radius: 4px 4px 0 0;
        padding: 3px;
        padding-left: 15px;
    }
    .exam-details .content {
        padding: 3px 15px 10px 3px;       
    }
    .exam-details .overview {
        border-bottom: 1px solid ghostwhite;
    }
    .exam-details .header span {
        background-color: #7777aa;
        border: 1px solid #555588;

    }
    .exam-properties {
        margin-top: 10px;
        min-height: 100px;
    }
    .exam-properties.other {
        column-count: 1;
    }
    @media screen and (max-width: 750px) {
        .exam-properties {
            column-count: 1;
        }
        .exam-details .toolbtn {
            min-width: 65px;
            margin: 2px;
            text-align: center;
        }
    }
</style>

<div class="exam-details">
    <div class="header">
        <?php if ($exam->show_state) : ?>
                <span class="toolbtn exam-state">State</span>
        <?php endif; ?>
        <?php if ($exam->show_other) : ?>
                <span class="toolbtn exam-grade">Grade</span>
        <?php endif; ?>
        <?php if ($exam->show_staff) : ?>
                <span class="toolbtn exam-staff">Staff</span>
        <?php endif; ?>
        <?php if ($exam->show_roles) : ?>
                <span class="toolbtn exam-roles">Roles</span>
        <?php endif; ?>
        <?php if ($exam->show_other) : ?>
                <span class="toolbtn exam-other">Other</span>
        <?php endif; ?>
    </div>
    <div class="content">
        <div class="overview">
            <div class="exam-phase" style="display: inline-block; float: right">
                <?php $phase->render() ?>
            </div>
            <div class="exam-date" style="display: inline-block; padding-left: 10px">
                <?php $datetime->render() ?>
            </div>
        </div>

        <?php if ($exam->show_state) : ?>
                <div class="exam-properties state">
                    <ul>
                        <?php
                        $state = $exam->getState();

                        if ($state->has(State::DRAFT)) {
                                printf("<li>%s</li>\n", "This exam is an draft (not yet scheduled)");
                        }

                        if ($state->has(State::UPCOMING)) {
                                printf("<li>%s</li>\n", "This exam is scheduled, but has not yet started");
                        } elseif ($state->has(State::RUNNING)) {
                                printf("<li>%s</li>\n", "This exam is currently ongoing");
                        } elseif ($state->has(State::FINISHED)) {
                                printf("<li>%s</li>\n", "This exam has been finished");
                        }

                        if ($state->has(State::ANSWERED)) {
                                printf("<li>%s</li>\n", "This exam has answers from students");
                        }
                        if ($state->has(State::CONTRIBUTABLE)) {
                                printf("<li>%s</li>\n", "Questions can still be contributed");
                        }
                        if ($state->has(State::CORRECTABLE)) {
                                printf("<li>%s</li>\n", "Answers can still be corrected on this exam");
                        }
                        if ($state->has(State::CORRECTED)) {
                                printf("<li>%s</li>\n", "All answers has been fully corrected");
                        }

                        if ($state->has(State::ENQUIRY)) {
                                printf("<li>%s</li>\n", "This exam is under investigation");
                        }

                        if ($state->has(State::DECODED)) {
                                printf("<li>%s</li>\n", "This exam has been decoded");
                        } elseif ($state->has(State::DECODABLE)) {
                                printf("<li>%s</li>\n", "This exam can be decoded");
                        }

                        if ($state->has(State::DELETABLE)) {
                                printf("<li>%s</li>\n", "Can be deleted (no answers exist or exam is flagged as testcase)");
                        }
                        if ($state->has(State::EDITABLE)) {
                                printf("<li>%s</li>\n", "The exam can still be edited");
                        }
                        if ($state->has(State::EXAMINATABLE)) {
                                printf("<li>%s</li>\n", "Student can be registered and start/endtime can be changed");
                        }
                        if ($state->has(State::LOCKDOWN)) {
                                printf("<li>%s</li>\n", "Lockdown mode is enabled on this exam");
                        }
                        if ($state->has(State::PUBLISHED)) {
                                printf("<li>%s</li>\n", "Exam has been published");
                        }
                        if ($state->has(State::REUSABLE)) {
                                printf("<li>%s</li>\n", "Can be reused as new exam");
                        }
                        if ($state->has(State::TESTCASE)) {
                                printf("<li>%s</li>\n", "Marked as testcase (always deletable)");
                        }

                        ?>
                    </ul>
                </div>
        <?php endif; ?>

        <?php if ($exam->show_grade) : ?>
                <div class="exam-properties grade" style="display: none">
                    <ul>
                        <?php
                        $grade = $exam->getGrade();

                        if ($grade->useScores()) {
                                printf("<li>This exam uses points instead of percent</li>\n");
                        }
                        if (($maximum = $grade->getMaximum())) {
                                printf("<li>Maximum score is " . floatval($maximum) . "p on this exam</li>\n");
                        }
                        foreach ($grade->getGrades() as $name => $limit) {
                                printf("<li>$name >= " .
                                    floatval($limit) . "%% (" .
                                    floatval($grade->getPoints($limit)) .
                                    "p)</li>\n");
                        }

                        ?>
                    </ul>
                </div>
        <?php endif; ?>

        <?php if ($exam->show_staff) : ?>
                <div class="exam-properties staff" style="display: none">
                    <ul>
                        <?php
                        $users = $exam->getStaff()->getData('users');

                        foreach ($users as $user => $data) {
                                printf("<li><a href=\"mailto:%s\">%s</a>: %s</li>\n", $data['mail'][0], $data['name'], implode(", ", $data['role']));
                        }

                        ?>
                    </ul>
                </div>
        <?php endif; ?>

        <?php if ($exam->show_roles) : ?>
                <div class="exam-properties roles" style="display: none">
                    <ul>
                        <?php
                        $roles = $exam->getStaff()->getData('roles');

                        foreach ($roles as $role => $rdata) {
                                $users = array();
                                foreach ($rdata as $user => $data) {
                                        $users[] = sprintf("<a href=\"mailto:%s\">%s</a>", $data['mail'][0], $data['name']);
                                }
                                printf("<li>%s: %s</li>", ucfirst($role), implode(", ", $users));
                        }

                        ?>
                    </ul>
                </div>
        <?php endif; ?>

        <?php if ($exam->show_other) : ?>
                <div class="exam-properties other" style="display: none">
                    <ul>
                        <?php $check = $exam->getCheck(); ?>

                        <li>Questions: <?= $check->getQuestions() ?></li>
                        <li>Students:  <?= $check->getStudents() ?></li>
                        <li>Locations:  <?= $check->getLocations() ?></li>

                        <?php $security = $check->getSecurity(); ?>
                        <?php if ($security == Check::SECURITY_NONE) : ?>
                                <li>Security: None</li>
                        <?php elseif ($security == Check::SECURITY_FULL) : ?>
                                <li>Security: Full</li>
                        <?php elseif (($security & Check::SECURITY_LOCKDOWN) == 0) : ?>
                                <li>Security: Partial (lockdown missing)</li>
                        <?php elseif (($security & Check::SECURITY_LOCATION) == 0) : ?>
                                <li>Security: Partial (no locations defined)</li>
                        <?php else : ?>
                                <li>Security: Partial</li>
                        <?php endif; ?>
                    </ul>
                </div>
        <?php endif; ?>

    </div>
</div>
