<?php

// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    index.phtml
// 
// Author:  Ahsan Shahzad (Medfarm DoIT)
// Author:  Anders Lövgren (QNET)
// 


use OpenExam\Library\Security\Roles;
use Phalcon\Tag;

$sections = include('sections.inc');

for ($i = 0; $i < count($roles); ++$i) {
        if (!array_key_exists($roles[$i], $sections)) {
                unset($roles[$i]);
        }
}

?>

<div id="container" class="left_menu_space container" style="width:100%">

    <div class="hero-unit" style="margin:15px">
        <h1>Hi <?= $this->catalog->getFirstName() ?>!</h1>
        <div style="padding:10px 0px">
            The content of this page depends on the different roles you have. Information about the different roles (creator, contributor, corrector, invigilator, student) can be found <a href="<?= $this->url->get('/help/manual/teacher') ?>">teacher manual</a>.  
        </div>
    </div>

    <section class="ac-container">
        <?php foreach ($roles as $index => $role) : ?>
                <?php if (array_key_exists($role, $sections)) : ?>
                        <div section-role="<?= $role ?>">
                            <?php if (in_array($role, $expand)): ?>
                                    <input id="ac-<?= $index ?>" name="accordion-1" type="radio" checked="" />
                            <?php else: ?>
                                    <input id="ac-<?= $index ?>" name="accordion-1" type="radio"/>
                            <?php endif; ?>

                            <label for="ac-<?= $index ?>" class="exam-list-boxes">
                                <i class="fa fa-chevron-right chevron" style="font-size: 16px; color: #990000"></i>
                                <?= $sections[$role]['title'] ?>
                            </label>
                            <article class="ac-large exam-listing-wrapper">
                                <?php if ($role == Roles::CREATOR): ?>
                                        <a href="<?= $this->url->get('exam/create') ?>"> 
                                            <span style="float: right; font-size: 12px; padding: 5px"> 
                                                <span class="label label-blue" style="margin-right: 26px; background-color:#3D7489">
                                                    <i class="fa fa-plus-square"></i> Create new exam
                                                </span> 
                                            </span> 
                                        </a>
                                <?php endif; ?>

                                <div style="float:right; padding:5px;">
                                    <input type="text" class="exam-search-box" placeholder="Quick search" value="<?= $search ?>">
                                    <span class="label label-orange search-exam"><i class="fa fa-search" style="color:#FFF"></i></span> 
                                </div>

                                <div class="exam-listing-area" style="min-height:260px"></div>
                            </article>
                        </div>
                <?php endif; ?>
        <?php endforeach; ?>
    </section>

    <!--
        Dialog for managing students on exam.
    -->
    <div id="manage-students" title="Manage students for exam" style="display:none"></div>

    <!--    
        Dialog for reusing exam (copy properties and questions).
    -->
    <div id="reuse-exam-dialog" title="Reuse exam" style="display:none">
        <div style="margin-top:15px; margin-bottom:10px">
            Along with <strong>Exam title, instructions and exam settings</strong>, please select if any of the following exam parts you would like to reuse:
        </div>
        <div style="margin-left:25px">
            <input type="checkbox" value="topics" class="exam-reuse-opt">
            Question sections<br>
            <input type="checkbox" value="questions" class="exam-reuse-opt">
            Questions and question correctors<br>
            <input type="checkbox" value="roles"  class="exam-reuse-opt">
            Exam roles<br>
        </div>         
    </div>

    <!--    
        Dialog for changing exam schedule.
    -->
    <div id="exam-datetime-changer" style="display: none" title="Change exam schedule">
        <div class="exam-datetime-select" style="padding: 10px">
            <label for="starttime">Start time:</label>
            <input type="text" value="" id="exam-starttime" name="starttime" placeholder="yyyy-mm-dd hh:mm:ss">
            <label for="endtime">End time:</label>
            <input type="text" value="" id="exam-endtime"   name="endtime" placeholder="yyyy-mm-dd hh:mm:ss">
        </div>
    </div>

    <!--
        Dialog for checking exam status.
    -->
    <div id="exam-check-box" style="display:none" title="Exam status check" ></div>    

</div>

<?= Tag::javascriptInclude('js/views/exam/index.js') ?>

<script>
        var examSections = <?= json_encode($sections); ?>;
</script>
