<!-- BISMILLAH-->

<?php $testMode = $exam->creator == $this->user->getPrincipalName() ? TRUE : FALSE;?>

<div class='col-xs-12' style="padding:0px 35px">
        <div class='row'>
                <div class='col-sm-12'>
                        <div class='page-header'>
                                <h1 class='pull-left'> <i class='icon-book'></i> 
                                        <span>
                                                <?=$exam->name?>
                                        </span> 
                                </h1>
                        </div>
                </div>
        </div>
        <div class='alert alert-info alert-dismissable'> 
        	<a class='close' data-dismiss='alert' href='#'>&times;</a> <strong>Hey <?=$this->helper->getCatalogAttribute($this->user->getPrincipalName(), 'name')?>!</strong>
                <br />
                Please do check that your computer is well functional before you start your exam. 
                All answers to the questions are automatically saved while you write.  
                In case you face any problem, please feel free to contact invigilator.
		
        </div>
        <div class="exam-descr">
        	<?=$exam->descr?>
        </div>
        
        <div class="exam-status-area">
                <center>
                <input onClick="javascript:location.href='<?=$this->url->get('exam/'.$exam->id.'/question/1')?>';" class="btn btn-success btn-lg" value="I am ready, start the exam <?=$testMode?'in test mode':''?>" type="button" style=" <?=(strtotime($exam->starttime) <= strtotime("now")) ? '':'display:none'?>">
                <?php if(strtotime($exam->starttime) > strtotime("now")):?>
                <input id="countdown-btn" class="btn btn-warning btn-lg" value="Exam <?=$testMode?'testing':''?> starts in: " type="button" disabled="disabled" style="font-size:45px; margin:14% 0px">
                <?php endif;?>
                </center>
        </div>        
</div>

<script language="javascript">
$('#main-nav').remove();
$('#main-nav-bg').remove();
$('#content').css("margin-left", "0px");
$('.toggle-nav').remove();
<?php if(strtotime($exam->starttime) > strtotime("now")):?>
$('.exam-descr').hide();
$('.alert').hide();
var examStartCount = <?=(strtotime(!$testMode ? $exam->starttime : "+4 seconds") - strtotime("now"))?>;
var examStartCountDown = setInterval(function() {
	examStartCount--;
	if (examStartCount <= 0)
	{
		$('#countdown-btn').hide();
		$('.btn-success').show(500);
		clearInterval(examStartCountDown);
		$('.exam-descr').show();
		$('.alert').show();
		return;
	}
	$("#countdown-btn").val("Exam <?=$testMode?'testing':''?> starts in: " + toHHMMSS(examStartCount));
	$('.exam-descr').hide();
	$('.alert').hide();
}, 1000); 
<?php endif;?>

</script> 
