<?php 
$testMode 	= $exam->creator == $this->user->getPrincipalName() ? TRUE : FALSE;
$examStartsAt 	= is_object($student) && !is_null($student->starttime) ? $student->starttime : $exam->starttime;
?>

<div class='col-xs-12' style="padding:0px 35px">
        <div class='row'>
                <div class='col-sm-12'>
                        <div class='page-header'>
                                <h1 class='pull-left'> <i class='icon-book'></i> 
                                        <span>
                                                <?=$exam->name?>
                                        </span> 
                                </h1>
                        </div>
                </div>
        </div>
        <div class='alert alert-info alert-dismissable'> 
        	<a class='close' data-dismiss='alert' href='#'>&times;</a> <strong>Welcome to OpenExam!</strong>
					<p>
					Use the buttons in the heading to minimize the left pane or increase the text size 
Under Exam info. You may again read the instructions, access a preview of all your answers and log out when you are done. <!--If you find it helpful, you can mark all questions as completed (green), in need of revision  (yellow) or will not be answered (red). -->
					You can hover over images (in supplementary material) to zoom. You can see full size image by clicking on it.
					</p>
					<br />
					<p>
					<strong>Important to know:</strong><br />
					<ul>
						<li>All your answers are automatically saved, every 10 seconds.</li>
						<li>It is highly recomended that you <u>don't</u> use "back" and "forward" buttons of web browser to go from one question to another. Always click on <button class="btn btn-xs btn-success" disabled="disabled"> Next Question <i class="icon-arrow-right"></i></button> and <button class="btn btn-xs" disabled="disabled"><i class="icon-arrow-left"></i> Prev. Question </button> buttons. To open a specific question, you can always click on desired question number appearing in left side menu.</li>
						<li>Please report to invigilator immediately if any button or link do not work. In such a case, please don't close/refresh web browser otherwise we may loose your answer. If you see any error message from system, it is highly important that you <u>don't</u> refresh/close the web page before you report. </li>
						<li>Flip down the screen if you go away for a biological break.</li>
						<li>If you have drawing canvas in a quesiton, don't try to write text in canvas by drawing.</li>
					</ul>
		
        </div>
        <div class="exam-descr">
        	<?=$exam->descr?>
        </div>
        
        <div class="exam-status-area">
                <center>
                <input onClick="javascript:location.href='<?=$this->url->get('exam/'.$exam->id.'/question/1')?>';" class="btn btn-success btn-lg" value="I am ready, start the exam <?=$testMode?'in test mode':''?>" type="button" style=" <?=((strtotime($examStartsAt) <= strtotime("now"))|| $testMode) ? '':'display:none'?>">
                <?php if(strtotime($examStartsAt) > strtotime("now")):?>
                <input id="countdown-btn" class="btn btn-warning btn-lg" value="Exam <?=$testMode?'testing':''?> starts in: " type="button" disabled="disabled" style="font-size:45px; margin:14% 0px; <?=($testMode) ? 'display:none':''?>">
                <?php endif;?>
                </center>
        </div>        
</div>

<script language="javascript">
$('#main-nav').remove();
$('#main-nav-bg').remove();
$('#content').css("margin-left", "0px");
$('.toggle-nav').each(function(i, elem) {
	if(!$(elem).hasClass('url')) {
		$(elem).remove();
	}
});
<?php if(strtotime($examStartsAt) > strtotime("now")):?>
<?php if(!$testMode):?>
$('.exam-descr').hide();
$('.alert').hide();
<?php endif;?>
var examStartCount = <?=(strtotime(!$testMode ? $examStartsAt : "+0 seconds") - strtotime("now"))?>;
var examStartCountDown = setInterval(function() {
	examStartCount--;
	if (examStartCount <= 0)
	{
		$('#countdown-btn').hide();
		$('.btn-success').show(500);
		clearInterval(examStartCountDown);
		$('.exam-descr').show();
		$('.alert').show();
		return;
	}
	$("#countdown-btn").val("Exam <?=$testMode?'testing':''?> starts in: " + toHHMMSS(examStartCount));
	$('.exam-descr').hide();
	$('.alert').hide();
}, 1000); 
<?php endif;?>

</script> 
