<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    pending.phtml
// Created: 2015-03-19 12:52:04
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<style>
    h1.pending {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }  
    .oe-pending button {
        min-width: 80px;
    }
</style>
<script>
        $(document).ready(function () {
            setTimeout(function () {
                window.location.assign('<?= $retry ?>');
            }, 30000)
        });
</script>

<div class="oe-pending">
    <h1 class="header">
        <i class="fa fa-clock-o" aria-hidden="true" style="color: darkorange"></i>
        Approval required
    </h1>

    <p class="message">
    </p>

    <div class="info">
        <p>
            Access to the exam '<?= $exam->name; ?>' is pending approval by the exam invigilator. 
            Please wait for a while before retrying again or wait for the automatic retry that occurs every 30 seconds.
        </p>
        <button class="btn btn-success" type="submit" name="retry" onclick="window.location.assign('<?= $retry ?>')" title="Click on this button to retry access to this exam."/>Retry</button>
    </div>
</div>
