<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    pending.phtml
// Created: 2015-03-19 12:52:04
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<style>
    h1.pending {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }  
    .oe-pending button {
        min-width: 80px;
    }
</style>
<script>
        $(document).ready(function () {
            setTimeout(function () {
                window.location.assign('<?= $retry ?>');
            }, 30000)
        });
</script>

<div class="oe-pending">
    <h1 class="header">
        <i class="fa fa-clock-o" aria-hidden="true" style="color: darkorange"></i>
        Approval required
    </h1>

    <p class="message">
    </p>

    <div class="info">
        <p>
            Access to the exam '<?= $exam->name; ?>' is pending approval by the exam invigilator. 
            Please wait for a while before retrying again or wait for the automatic retry that occurs every 30 seconds.
        </p>
        <button class="btn btn-success" type="submit" name="retry" onclick="window.location.assign('<?= $retry ?>')" title="Click on this button to retry access to this exam."/>Retry</button>
    </div>
</div>
