<?php

use OpenExam\Library\Core\Exam\State;
use OpenExam\Library\Gui\Component\Exam\Progress;

// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    section.phtml
// Created: 2017-11-05 14:42:33
// 
// Author:  Anders Lövgren (QNET)
// Author:  Ahsan Shahzad (Medfarm DoIT)
// 

$sections = include('sections.inc');

$buttons = array(
        'check-exam'        => '<span class="toolbtn toolbtn-orange"><i class="fa fa-thumbs-o-up"></i> Status</span>',
        'check-exam-status' => array(
                1 => '<span class="toolbtn toolbtn-red-outline"><i class="fa fa-thumbs-o-up"></i> Status</span>',
                2 => '<span class="toolbtn toolbtn-orange-outline"><i class="fa fa-thumbs-o-up"></i> Status</span>',
                3 => '<span class="toolbtn toolbtn-green-outline"><i class="fa fa-thumbs-o-up"></i> Status</span>'
        ),
        'manage-exam'       => '<span class="toolbtn toolbtn-green"><i class="fa fa-gear"></i> Manage</span>',
        'test-exam'         => '<span class="toolbtn toolbtn-blue"><i class="fa fa-thumbs-o-up"></i> Preview</span>',
        'del-exam'          => '<span class="toolbtn toolbtn-red"><i class="fa fa-trash"></i> Delete</span>',
        'reuse-exam'        => '<span class="toolbtn toolbtn-primary" style="background-color: #4285F4"><i class="fa fa-refresh"></i> Reuse</span>',
        'view-exam'         => '<span class="toolbtn toolbtn-green"><i class="fa fa-question-circle"></i> Display</span>',
        'add-q'             => '<span class="toolbtn toolbtn-blue"><i class="fa fa-pencil-square-o"></i> Add questions</span>',
        'ans-correction'    => '<span class="toolbtn toolbtn-green"><i class="fa fa-check-square-o"></i> Answer correction</span>',
        'exam-not-finished' => '<span class="toolbtn toolbtn-primary"><i class="fa fa-times"></i> Exam not finished yet</span>',
        'view-results'      => '<span class="toolbtn toolbtn-orange"><i class="fa fa-line-chart"></i> View results</span>',
        'view-scoreboard'   => '<span class="toolbtn toolbtn-orange"><i class="fa fa-trophy"></i> View Score board</span>',
        'download-result'   => '<span class="toolbtn toolbtn-primary" style="background-color: #4285F4"><i class="fa fa-download"></i> Download results</span>',
        'decode-exam'       => '<span class="toolbtn toolbtn-green"><i class="fa fa-code"></i> Decode this exam</span>',
        'decode-closed'     => '<span class="toolbtn toolbtn-primary"><i class="fa fa-times"></i> Not open for decoding yet</span>',
        'manage-student'    => '<span class="toolbtn toolbtn-green"><i class="fa fa-user"></i> Manage students</span>',
        'change-time'       => '<span class="toolbtn toolbtn-blue"><i class="fa fa-clock-o"></i> Change schedule</span>',
        'st-exam-page'      => '<span class="toolbtn toolbtn-green"><i class="fa fa-gear"></i> Go to exam page</span>',
        'st-view-exam'      => '<span class="toolbtn toolbtn-green"><i class="fa fa-gear"></i> View exam</span>'
);

$ordering = array(
        "created"   => "Date created",
        "name"      => "Exam name",
        "code"      => "Exam code",
        "starttime" => "Start date"
);

?>

<style>
    .pagination > .active > a {
        background-color: #f6f6f6;
        border-color: #dddddd;
        color: #c1002b;
        border-top-right-radius: 0px;
        border-top-left-radius: 0px;
    }
    .pagination > .active > a:hover,
    .pagination > .active > a:focus {
        background-color: white;
        border-color: #dfdfdf;
    }
</style>

<?php if (count($page->items) != 0): ?>
        <ul class="list-group exam-list">
            <li class="list-group-item" style="background-color: rgb(245, 245, 245); padding: 5px;">
                <div class="form-inline">
                    <span>Sort by: </span>
                    <select class="exam-order-by form-control" style="max-width: 200px">
                        <?php foreach ($ordering as $key => $val) : ?>
                                <?php if ($order == $key) : ?>
                                        <option value="<?= $key ?>" selected="true"><?= $val ?></option>
                                <?php else: ?>
                                        <option value="<?= $key ?>"><?= $val ?></option>
                                <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                    <?php if ($sort == "desc") : ?>
                            <i class="exam-sort-order fa fa-lg fa-arrow-circle-down" sort="desc" style="color: rgb(193, 0, 43);"></i>
                    <?php else : ?>
                            <i class="exam-sort-order fa fa-lg fa-arrow-circle-up" sort="asc" style="color: rgb(193, 0, 43);"></i>
                    <?php endif; ?>                        
                </div>
            </li>

            <?php foreach ($page->items as $exam): ?>
                    <li class="list-group-item" data-id="<?= $exam->id ?>" style="min-height: 20px; <?= $exam->published ? ';background-color:#ffffed' : '' ?>">
                        <div class="exam-show-state" style="float:left;margin-top: 0px"> 
                            <span class="exam-status">
                                <?php
                                if ($exam->state & State::PUBLISHED) {
                                        printf("<i class=\"fa fa-check-square-o published-exam\" style=\"color:green;\"></i>\n");
                                        printf("<i class=\"fa fa-question draft-exam\" style=\"color:lightgray;display:none\"></i>\n");
                                        printf("<i class=\"fa fa-pencil-square-o upcoming-exam\" style=\"color:red;display:none\"></i>\n");
                                } elseif ($exam->state & State::DRAFT) {
                                        printf("<i class=\"fa fa-check-square-o published-exam\" style=\"color:green;display:none\"></i>\n");
                                        printf("<i class=\"fa fa-question-circle draft-exam\" style=\"color:lightgray;\"></i>\n");
                                        printf("<i class=\"fa fa-pencil-square-o upcoming-exam\" style=\"color:red;display:none\"></i>\n");
                                } else {
                                        printf("<i class=\"fa fa-check-square-o published-exam\" style=\"color:green;display:none\"></i>\n");
                                        printf("<i class=\"fa fa-question draft-exam\" style=\"color:lightgray;display:none\"></i>\n");
                                        printf("<i class=\"fa fa-pencil-square-o upcoming-exam\" style=\"color:red;\"></i>\n");
                                }

                                ?>
                            </span>
                            <?php
                            $progress = new Progress($exam->id, $role, $exam->getState());
                            $progress->render();

                            ?>
                            <a href="#"
                               class="exam-state-show"
                               title="Click to display exam details"
                               style="cursor: pointer">
                                <span class="exam-date toolbtn toolbtn-blue-outline">
                                    <i class="fa fa-clock-o"></i> 
                                    <?php
                                    if (isset($exam->starttime)) {
                                            echo strftime("%x", strtotime($exam->starttime));
                                    } else {
                                            echo "---";
                                    }

                                    ?>
                                </span>
                                <span class="exam-name">
                                    <?= $exam->name ?>
                                    <?= !empty($exam->course) ? " (" . $exam->course . ") " : "" ?>
                                </span>
                            </a>
                        </div>
                        <div style="float:right">
                            <div class="exam-show-options">
                                <?php foreach ($sections[$sect]['show-options'] as $op => $opData): ?>
                                        <?php
                                        if ($op == 'check-exam') {
                                                $button = $buttons['check-exam-status'][$exam->getStatus()];
                                        } else {
                                                $button = $buttons[$op];
                                        }

                                        ?>

                                        <?php $isUrl = preg_match('/.*\/.*/', $opData['target']); ?>
                                        <?php if ($opData['show-on-flags'][0] == '*' || count(array_diff($opData['show-on-flags'], $exam->flags)) != count($opData['show-on-flags'])) : ?>
                                                <?php $href = ($isUrl ? str_replace("{exam-id}", $exam->id, $opData['target']) : '#'); ?>
                                                <a data-id="<?= $exam->id ?>" 
                                                   href="<?= $this->url->get($href) ?>" 
                                                   class="<?= ($isUrl ? '' : $opData['target'] . ' prevent') ?>"
                                                   >
                                                       <?= $button ?>
                                                </a>
                                        <?php endif; ?>

                                <?php endforeach; ?>
                            </div>
                            <div style="padding-top: 5px; float:right; clear:both; display:none">
                                <span class="exam-date" style="padding-right: 5px; font-size: 9px;">
                                    <i class="fa fa-calendar"></i>
                                    <span><?= date("Y-m-d", strtotime($exam->starttime)) ?></span>
                                </span> 
                                <span style="font-size: 9px;"> <i class="fa fa-clock-o"></i>
                                    <span class="exam-starts"><?= date("H:i", strtotime($exam->starttime)) ?></span>
                                    &mdash;
                                    <span class="exam-ends"><?= date("H:i", strtotime($exam->endtime)) ?></span>
                                </span> 
                            </div>
                        </div>
                        <div style="clear:both" class="exam-state-view">
                            <!-- exam details (phase, datetime and state) -->
                            <div style="display: none"></div>
                        </div>
                    </li>
            <?php endforeach; ?>
        </ul>

        <?php if ($page->total_pages > 1): ?>
                <div style="text-align: center;">
                    <ul class="pagination" style="margin: 0;">
                        <?php
                        for ($i = 1; $i <= $page->total_pages; $i++):

                                ?>
                                <?php if ($i == $page->current) : ?>
                                        <li class="active" page="<?= $i ?>">
                                            <a href="#"><?= $i ?><span class="sr-only">(current)</span></a> 
                                        </li>
                                <?php else : ?>
                                        <li page="<?= $i ?>">
                                            <a href="#"><?= $i ?><span class="sr-only">(current)</span></a> 
                                        </li>
                                <?php endif; ?>
                        <?php endfor; ?>
                    </ul>
                </div>
        <?php endif; ?>
<?php else: ?>
        <div class="exam-listing-default-msg"> 
            <i class="fa fa-info-circle"></i> No exams as <?= $role ?> was found using current filtering.
        </div>
<?php endif; ?>
