<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    security.phtml
// Created: 2015-04-07 23:20:12
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

/**
 * @internal Helper class for displaying locations.
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class DisplayLocation
{

        private $data;
        private $name;

        public function __construct($data, $name)
        {
                $this->data = $data;
                $this->name = $name;
        }

        public function display()
        {
                if ($this->data) {
                        printf("<b><u>%s</u></b>\n", $this->name);
                        printf("<ul>\n");
                        foreach ($this->data as $key => $location) {
                                if (is_array($location['addr'])) {
                                        $location['disp'] = $location['addr'];
                                        $location['addr'] = implode(';', $location['addr']);
                                } elseif (strstr($location['addr'], ';')) {
                                        $location['disp'] = explode(';', $location['addr']);
                                } else {
                                        $location['disp'] = array($location['addr']);
                                }

                                printf("<li addr='%s' disp='%s'>\n", $location['addr'], $key);
                                printf("<b>%s</b><br/><div class='location-addresses'>%s</br/></div>\n", $key, implode('<br/>', $location['disp']));
                                printf("<span class='btn btn-success' id='location-add'>\n");
                                printf("<i class='fa fa-plus-circle'></i>\n");
                                printf("<span>Add</span>\n");
                                printf("</span>\n");
                                printf("</li>\n");
                                printf("<br/>\n");
                        }
                        printf("</ul>\n");
                }
        }

}

?>

<style>
    div.locations, div.lockdown-method {
        padding-top: 20px;
    }
    div.location-addresses {
        display: none;
    }
</style>

<div class="exam-security-box">
    <div class="alert alert-info">
        Use this view for defining exam security and access restrictions. <strong>Notice:</strong> For keeping the exam public (no access restriction), simply uncheck the 'Enable lockdown' option.
    </div>

    <div class="checkbox">
        <label>
            <?php if ($exam->lockdown->enable) : ?>
                    <input id="lockdown-enable" class="save" type="checkbox" checked="true"> 
            <?php else : ?>
                    <input id="lockdown-enable" class="save" type="checkbox" > 
            <?php endif; ?>
            Enable lockdown                
        </label>
    </div>

    <div class="locations <?= $exam->lockdown->enable ? '' : 'oe-disabled' ?>">
        <p><b>This exam should only be accessable from these locations:</b></p>
        <table id="locations-table" class="table table-hover">
            <thead><tr><th>Location</th><th>Address</th></tr></thead>
            <tbody>
                <?php foreach ($active as $key => $location) { ?>
                        <tr entry="update" id="<?= $location['id'] ?>">
                            <td contenteditable="true"><?= $key ?></td>
                            <td contenteditable="true"><?= str_replace(';', '<br/>', $location['addr']) ?></td>
                            <td>
                                <span class="btn btn-success" id="location-remove">
                                    <i class="fa fa-cut"></i>
                                    <span>Remove</span>
                                </span>
                            </td>
                        </tr>
                <?php } ?>
            </tbody>
        </table>
        <div id="locations-list" style="display: none">
            <div class="alert alert-info">
                Select locations from recent used, system pre-defined or current action locations.
            </div>
            <span style="float: right" class="btn btn-success" id="locations-details">
                <i class="fa fa-list-alt"></i>
                <span>Details</span>
            </span>
            <?php
            $location = new DisplayLocation($recent, 'Recent used locations');
            $location->display();
            $location = new DisplayLocation($system, 'Pre-defined locations');
            $location->display();
            $location = new DisplayLocation($active, 'Currently active locations');
            $location->display();

            ?>
        </div>
        <span style="min-width: 6em" class="btn btn-success" id="location-new">
            <i class="fa fa-plus-circle"></i>
            <span>New</span>
        </span>
        <span style="min-width: 6em" class="btn btn-success" id="location-insert">
            <i class="fa fa-list"></i>
            <span>Insert...</span>
        </span>
    </div>

    <div class="lockdown-method <?= $exam->lockdown->enable ? '' : 'oe-disabled' ?>">
        <p><b>Use this method for client side locking:</b></p>
        <select id="lockdown-method" class="save form-control">
            <option value="" <?= $exam->lockdown->method == "" ? "selected" : "" ?>>---</option>
            <option value="fwexamd" <?= $exam->lockdown->method == "fwexamd" ? "selected" : "" ?>>fwexamd</option>
        </select>
    </div>

    <div class="oe-dialog-buttons">
        <hr>
        <center>
            <span style="min-width: 6em" class="btn btn-success save" id="close-security">
                <i class="fa fa-save"></i>
                <span>OK</span>
            </span>
            <span style="min-width: 6em" class="btn btn-success" id="close-security">
                <i class="fa fa-undo"></i>
                <span>Cancel</span>
            </span>
        </center>		
    </div>
</div>   
