<!-- Main area -->

<?php

use OpenExam\Models\Exam;

?>

<?php $canUpdateExam = true; ?>
<?php
$totalScore = 0;
$missingQuestText = $missingPoints = array();
$qs = $exam->getQuestions(array('order' => 'slot'));
foreach ($qs as $qNo => $q):
        $totalScore += $q->score;

        $qTxt = '(';
        $quest = json_decode($q->quest, true);
        foreach ($quest as $qPartTitle => $qPart):
                if (strip_tags($qPart['q_text']) == ''):
                        $qTxt .= "Part " . $qPartTitle . ",";
                endif;
        endforeach;

        if ($qTxt != '('):
                $missingQuestText[] = "Q" . ($qNo + 1) . " " . trim($qTxt, ',') . ")";
        endif;

        if (!$q->score):
                $missingPoints[] = "Q" . ($qNo + 1);
        endif;

endforeach;
/* print_r($missingQuestText);
  die; */

?>
<div class="exam-settings-box">
    <div role="alert" class="alert alert-warning alert-dismissible fade in" style="width:unset; font-weight:normal; position:inherit; text-align:justify">
        <div style="float:left; width:68%">
            <?php if ($canUpdateExam): ?>
                    <div style="color:#333333">Please note that you may return anytime and can complete the exam settings. </div>
            <?php endif; ?>

            <ul style="margin:10px;">
                <?php if (trim($exam->name) == '' || empty($exam->starttime) || empty($exam->endtime) || empty($exam->grades)): ?>
                        <li style="color:#c09853">Please fill up all required fields (marked with <span style="color:#F02222">*</span>). </li>
                <?php endif; ?>
                <?php if (count($missingQuestText)): ?>
                        <li style="color:#c09853">Some questions are empty: <?= implode(", ", $missingQuestText) ?></li>
                <?php endif; ?>
                <?php if (count($missingPoints)): ?>
                        <li style="color:#c09853">Some questions don't have any credits: <?= implode(", ", $missingPoints) ?></li>
                <?php endif; ?>
            </ul>
        </div>	
        <div style="background-color: #51A451; padding: 10px; color: #FCF8E3; float: right; margin-right: 0px; border-radius:5px">
            Total number of students in exam: <?= count($exam->getStudents()) ?> <br />
            Total exam points: <?= $totalScore ?> 
        </div>
        <br style="clear:both" />
    </div>
    <div class="st-line">
        <label for="exam-title"><strong>Exam title:</strong> <span style="color:#F02222">*</span></label>
        <?php if ($canUpdateExam && in_array("editable", $exam->flags)): ?>
                <input title="Exam code from active directory" type="text" value="<?= $exam->name ?>" name="exam-title"  class="validate[required]" style="width:68% !important" ><!--data-prompt-position="topRight:-150"-->
        <?php else: ?>
                <span style="border: 1px solid #cecece; padding:5px"><?= trim($exam->name) != '' ? trim($exam->name) : 'Untitled exam' ?></span>
        <?php endif; ?>
    </div>
    <div class="st-line" style="float:left; margin-right:25px">
        <label for="exam-course-code"><strong>Course code:</strong></label>
        <?php if ($canUpdateExam && in_array("editable", $exam->flags)): ?>
                <input title="Course code of this exam" type="text" value="<?= $exam->course ?>" name="exam-course-code">
        <?php else: ?>
                <span style="border: 1px solid #cecece; padding:5px"><?= empty($exam->course) ? " --- " : $exam->course ?></span>
        <?php endif; ?>
    </div>
    <div class="st-line">
        <label for="exam-code"><strong>Uppdok test code:</strong></label>
        <?php if ($canUpdateExam && in_array("editable", $exam->flags)): ?>
                <input title="Exam code from active directory" type="text" value="<?= $exam->code ?>" name="exam-code">
        <?php else: ?>
                <span style="border: 1px solid #cecece; padding:5px;"><?= empty($exam->code) ? " --- " : $exam->code ?></span>
        <?php endif; ?>
    </div>
    <div class="st-line" style="float:left; margin-right:25px">
        <label for="start"><b>Exam Start time:</b> <span style="color:#F02222">*</span></label>
        <?php if ($canUpdateExam && in_array("editable", $exam->flags)): ?>
                <input type="text" placeholder="yyyy-mm-dd hh:mm" value="<?= $exam->starttime ?>" name="start" class="datepicker validate[required]">
        <?php else: ?>
                <span style="border: 1px solid #cecece; padding:5px"><?= $exam->starttime ?></span>
        <?php endif; ?>
    </div>

    <div class="st-line">
        <label for="end"><b>Exam End time:</b> </label>
        <?php if ($canUpdateExam && in_array("editable", $exam->flags)): ?>
                <input type="text" placeholder="yyyy-mm-dd hh:mm" value="<?= $exam->endtime ?>" name="end" class="datepicker">
        <?php else: ?>
                <span style="border: 1px solid #cecece; padding:5px"><?= $exam->endtime ?></span>
        <?php endif; ?>
    </div>
    <div class="st-line" style="float:left; margin-right:25px">
        <label for="grade"><strong>Grades:</strong> <span style="color:#F02222">*</span></label>
        <?php if ($canUpdateExam): ?>
                <textarea title="Input name:value pairs on separate lines defining the grade levels in percent for this examination. The first line must be on form name:0, denoting the failed grade." name="grade" class="grade validate[required]" placeholder="<?= str_pad("U:0", 65, " ") . str_pad("G:50", 60, " ") . "VG:75" ?>"><?= trim($exam->grades) ?></textarea>
        <?php else: ?>
                <span style="border: 1px solid #cecece; padding:5px"><?= nl2br(trim($exam->grades)) ?></span>
        <?php endif; ?>
    </div>
    <div class="st-line">
        <label for="unit"><b>Organization:</b> <span style="color:#F02222">*</span></label>
        <?php if ($canUpdateExam && in_array("editable", $exam->flags)): ?>
                <input type="text" value="<?= $exam->orgunit ?>" name="unit" class="validate[required]">
        <?php else: ?>
                <span style="border: 1px solid #cecece; padding:5px"><?= $exam->orgunit ?></span>
        <?php endif; ?>
    </div>
    <br style="clear:both" />
    <div class="st-line">
        <label for="exam-desc"><strong>Exam instructions for students:</strong></label>		
        <?php if ($canUpdateExam && in_array("editable", $exam->flags)): ?>
                <textarea id="exam-desc" style="width:99%;" rows="1" placeholder="Write exam description here"><?= trim($exam->descr) ?></textarea>
        <?php else: ?>
                <div style="width:99%;border: 1px solid #cecece; padding:5px"><?= trim($exam->descr) ?></div>
        <?php endif; ?>
    </div>
    <div class="st-line">
        <?php if ($canUpdateExam): ?>
                <input type="checkbox" value="1" title="Expose names and contact information for people involved in the creation and correction process in the result PDF seen by the student." <?= ((($exam->details & Exam::RESULT_EXPOSE_EMPLOYEES) != 0 || empty($exam->details)) ? 'checked="checked"' : '') ?> name="details[]" >
                In corrected exam, display correcting teacher.
        <?php else: ?>
                <?= ((($exam->details & Exam::RESULT_EXPOSE_EMPLOYEES) != 0) ? '&#10004; In corrected exam, display correcting teacher.' : '') ?>
        <?php endif; ?>
        <br />

        <?php if ($canUpdateExam): ?>
                <input type="checkbox" value="2" title="Include statistics like avarage/mean values and score distribution compared to other students in the result PDF seen by the student." <?= ((($exam->details & Exam::RESULT_OTHERS_STATISTICS) != 0 || empty($exam->details)) ? 'checked="checked"' : '') ?> name="details[]" >
                In corrected exam, include result statistics.
        <?php else: ?>
                <?= (($exam->details & Exam::RESULT_OTHERS_STATISTICS) != 0) ? '&#10004; In corrected exam, include result statistics.' : '' ?>
        <?php endif; ?>
        <br>

        <?php if ($canUpdateExam): ?>
                <input type="checkbox" value="4" <?= ((($exam->details & Exam::EXPOSE_GRADES_DURING_CORRECTION) != 0 || empty($exam->details)) ? 'checked="checked"' : '') ?> name="details[]" >
                Expose student's accumulated points in score board.
        <?php else: ?>
                <?= (($exam->details & Exam::EXPOSE_GRADES_DURING_CORRECTION) != 0) ? '&#10004; Expose student\'s accumulated points in score board.' : '' ?>
        <?php endif; ?>
        <br>

        <?php if ($canUpdateExam): ?>
                <input type="checkbox" value="16" <?= ((($exam->details & Exam::HIDE_MEDIA_CONTENT_IN_RESULT) != 0 || empty($exam->details)) ? 'checked="checked"' : '') ?> name="details[]" >
                Hide rendered media content (i.e. images) in student result file.
        <?php else: ?>
                <?= (($exam->details & Exam::HIDE_MEDIA_CONTENT_IN_RESULT) != 0) ? '&#10004; Hide rendered media content in student result file.' : '' ?>
        <?php endif; ?>
        <br>
    </div>
    <?php if ($canUpdateExam): ?>
            <div class="st-line">
                <center>
                    <span style="padding:2px; font-size:11px" class="btn btn-success save-exam-settings">
                        <i class="fa fa-floppy-o"></i>
                        <span>Save exam settings</span>
                    </span>
                    &nbsp;
                    <?php if (!$exam->published): ?>
                            <span style="padding:2px; font-size:11px" class="btn btn-success" id="publish_exam">
                                <i class="fa fa-check-circle"></i>
                                <span>This exam is ready for use</span>
                            </span>
                    <?php endif; ?>
                </center>		

            </div>   
    <?php endif; ?> 
</div>


<script language="javascript">
        $(function () {

            jQuery(".exam-settings-box").validationEngine();
            if ($('#exam-desc').length) {
                CKEDITOR.replace('exam-desc', {
                    height: '100px',
                    extraPlugins: 'specialchar,link',
                    toolbar: [
                        ['Cut', 'Copy', 'Paste', 'PasteFromWord', '-',
                            'Undo', 'Redo', 'Outdent', 'Indent', '-',
                            'Bold', 'Italic', 'Underline', '-',
                            'NumberedList', 'BulletedList', '-',
                            'Link', 'Unlink'/*, '-',
                             'Mathjax', 'Specialchar'*/
                        ]
                    ]

                });
            }
        });
</script>