<!-- Main area -->

<?php
$i=0;
$stList = array(); 
$students = $exam->getStudents();
foreach($students as $student):
	$stList[$i]["id"] = $student->id;
	$stList[$i]["value"] = $student->user." - ".$student->code;
	$i++;
endforeach;
?>
<div id="st-mng-wrapper" exam-id="<?=$this->request->getPost('exam_id')?>">
	<div style="padding-bottom:15px">
        	<h3><?=$exam->name?></h3>
        </div>
        <div class="tabs">
                <ul>
                        <li><a href="#tabs-1">Add new students</a></li>
                        <li><a href="#tabs-2">Manage existing students</a></li>
                </ul>
                <div id="tabs-1">

                        <div class="accordion">
                            <h3>Add single or multiple students</h3>
                            <div>
                                <p>
                                    Write usernames and exam code of single or multiple students. Username and exam code should be space seprated.
                                    To add multiple students, data of students should be comma seprated.
                                    <br />
                                    <small>
                                    Format to add single student: <strong>username code</strong><br />
                                    Format to add multiple student: <strong>username1 code1, username2 code2</strong><br />
                                    </small>
                                </p>
                                <textarea id="student_list" placeholder="username code" style="height:100px; width:480px"></textarea>
                                
                                <div id="add_students_btn" style="display: block;margin:10px 0px 30px 0px;">        
                                        <span class="btn btn-success">
                                                <i class="fa fa-chevron-circle-right"></i>
                                                <span>Add students</span>
                                        </span>
                                </div>                                
                            </div>
                            <h3>Import from file</h3>
                            <div>
                                <p>
                                        Instructions about the file to be imported.
                                </p>
                                <input type="file" />
                                
                                <div id="import_students_by_file" style="display: block;margin:10px 0px 30px 0px;">        
                                        <span class="btn btn-success">
                                                <i class="fa fa-chevron-circle-right"></i>
                                                <span>Import students</span>
                                        </span>
                                </div>                                
                            </div>
                            <h3>Import from Uppdock</h3>
                            <div>
                                <p>
                                        Provide term details in following form
                                </p>
                                <div>
                                	Enter course code: <input type="text" /><br />
                                        Select Term: <select><option>Select</option></select>
                                </div>
                                
                                <div id="import_students_by_file" style="display: block;margin:10px 0px 30px 0px;">        
                                        <span class="btn btn-success">
                                                <i class="fa fa-chevron-circle-right"></i>
                                                <span>Import students</span>
                                        </span>
                                </div>                                
                            </div>
                        </div>
                </div>
                <div id="tabs-2">
                	<h4 style="float:left">Registered students in this exam</h4>
                        <div style="float:right">
                                <input class="search-students" type="text" placeholder="Filter students" style="width:145px; height:15px;" />
                                <span class="label label-orange filter-students"><i style="color:#FFF" class="fa fa-search"></i></span>
                        </div>
                       	<div style="clear:both"></div>
                       
                       	<!--
                        <a href="#" id="lsit-all-students" class="prevent" style="color:#CC0066"> View list of all students</a><br />
                        -->
			<ul class="student-list" style="list-style:none; max-height:500px; overflow:auto; margin-left:0px" >
                                <li style="float: left; background-color: #FEFF99; border: 1px solid rgb(222, 222, 222); padding: 5px; margin:2px; display:none">
                                        <a href="#" class="prevent del-student" data-id=""><i class="fa fa-trash" style="color:#C02E3C"></i></a> 
                                        <span></span>
                                </li>
                                <?php foreach($students as $student):?>
                                        <li style="float: left; background-color: #F5F5F5; border: 1px solid #dedede; padding: 5px; margin:2px">
                                                <a href="#" class="prevent del-student" data-id="<?=$student->id?>"><i class="fa fa-trash" style="color:#C02E3C"></i></a> 
                                                <span><?=$student->user." - ".$student->code?></span>
                                        </li>
                                <?php endforeach;?>
                        </ul>
                        <div style="clear:both"></div>
                </div>
        </div>
</div>

<script language="javascript">
var studentList = <?=json_encode($stList)?>;

$(function() {

	$('.tabs').tabs();
	$( ".accordion" ).accordion({
      		heightStyle: "content"
	});

	
	$( ".search-students" ).autocomplete({
		source: studentList,
		select: function( event, ui ) {
			newItem = $('.student-list > li:first').clone();
			newItem.find('span').html(ui.item.value).end()
				.find('a').attr('data-id', ui.item.id).end()
				.show();
			$('.student-list').empty();
			$('.student-list').append(newItem);
			$('.ui-autocomplete-input').val('');
		}
		
	});

	if(stEvents == 'loaded') {
		return;
	} else {
		stEvents = 'loaded';
	}
	
	/*
	$(document).on('click', '#lsit-all-students', function () {

		$('.student-list > li:visible').remove();
		jQuery.each(studentList , function( i, studentData ) {
			//jQuery.each(studentData , function( username, student ) {			
				newItem = $('.student-list > li:first').clone();
				newItem.find('span').html(studentData.value).end()
					.find('a').attr('data-id', studentData.id).end()
					.show();
				$('.student-list').append(newItem);
			//});	
		});
		
		if(!$('.student-list > li:visible').length) {
			$('.student-list').append('<li>There are no registered users in this exam.</li>');
		}
		$('.student-list').show();
		
	});*/
	
	$(document).on('click', '.del-student', function () {
		var student = $(this);
		if(confirm("Are you sure you want to delete this student?")) {
			ajax(
				baseURL + 'core/ajax/invigilator/student/delete', 
				{"id":$(this).attr('data-id')}, 
				function(status) {
					
					jQuery.each(studentList , function( i, sData ) {
						if(sData.id == $(student).attr('data-id')) {
							delete studentList[i];
						}
					});
					
					// hide from list
					$(student).parent().slideUp('500', function() {
						// hide
						$(this).remove();
					});
		
				}
			);
		}
	});
	
	$(document).on('click', '#add_students_btn', function () {
		
		stData = [];
		examId = $(this).closest('#st-mng-wrapper').attr('exam-id');
		if(examId) {
			stList = jQuery.trim($('#student_list').val()).split(',');
			
			//prepare data object
                        var totalStudents = 0;
			$.each(stList, function(i, val) {
				st = jQuery.trim(val).split(/\s/g);
				stData.push({'exam_id': examId, "user": st[0], "code": st[1]});
                                totalStudents++;
			});

			// send ajax request to add these students to the exam
			ajax(
				baseURL + 'core/ajax/invigilator/student/create',
				JSON.stringify(stData),
				function (userData) {
                                        if(totalStudents > 1) {
                                                $.each(userData, function(i, user) {
                                                        newItem = $('.student-list > li').first().clone();
                                                        $(newItem)
                                                                .find('.del-student').attr('data-id', user.id)
                                                                .find('span').html(user.user+" - "+user.code).end()
                                                                .show();
                                                        $('.student-list').prepend($(newItem));
                                                });
                                        } else {
                                                newItem = $('.student-list > li').first().clone();
                                                $(newItem)
                                                        .find('.del-student').attr('data-id', userData.id)
                                                        .find('span').html(userData.user+" - "+userData.code).end()
                                                        .show();
                                                $('.student-list').prepend($(newItem));
                                        }        
				}
			);
		}
	});
	
});
</script>