<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    students.phtml
// 
// Author:  Ahsan Shahzad (Medfarm DoIT)
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<?= Phalcon\Tag::stylesheetLink('css/tablesorter.default.css'); ?>
<?= Phalcon\Tag::javascriptInclude('js/jquery.tablesorter.js'); ?>

<?php
$i = 0;
$stList = array();

foreach ($exam->students as $student) {
        $stList[$i]["id"] = $student->id;
        $stList[$i]["value"] = $student->user . " - " . $student->code;
        $i++;
}

?>

<style>
    td[data-modified="true"] {
        border: 1px solid #ccff99;
        background-color: #99ff99;
    }
    .st-exam-item-save {
        white-space: nowrap;
    }
</style>

<div id="st-mng-wrapper" exam-id="<?= $this->request->getPost('exam_id') ?>">
    <div style="padding-bottom:15px">
        <h3><?= $exam->name ?></h3>
    </div>
    <?php if ($readonly) : ?>
            <div class="tabs">
                <?php $this->partial("partials/students-list", array('exam' => $exam, 'readonly' => true)) ?>
            </div>
    <?php else: ?>
            <div class="tabs">
                <ul>
                    <li><a href="#tabs-1">Add new students</a></li>
                    <li><a href="#tabs-2">Manage existing students</a></li>
                </ul>
                <?php $this->partial("partials/students-add", array('domains' => $domains)) ?>
                <?php $this->partial("partials/students-list", array('exam' => $exam, 'readonly' => false)) ?>
            </div>
    <?php endif; ?>
</div>

<script language="javascript">

        (function () {

            var studentList = <?= json_encode($stList) ?>;

            // 
            // Called after students has been added to exam.
            // 
            // @param int examId The exam ID.
            // 
            var onStudentInserted = function (examId) {

                $.ajax({
                    type: "POST",
                    data: {exam_id: examId},
                    url: baseURL + 'exam/students/',
                    success: function (content) {
                        // 
                        // Replace dialog content:
                        // 
                        $("#manage-students").html(content);

                        // 
                        // Switch to second tab:
                        // 
                        $(".tabs").tabs("option", "active", 1);
                        $('#no-student-msg').hide();
                    }
                });
            };

            $('.tablesorter').tablesorter({
                usNumberFormat: false,
                sortReset: true,
                sortRestart: true,
                sortList: [[0, 0], [1, 0]],
                headers: {
                    '.no-sort': {
                        sorter: false
                    }
                }
            });

            $('.tabs').tabs();
            $(".accordion").accordion({
                heightStyle: "content"
            });

            if (oe_module_loaded("exam-students")) {
                return;
            }

            // 
            // Edit student properties inline.
            // 
            $(document).on('click', '.st-exam-item-edit', function () {
                if ($(this).attr("contenteditable")) {
                    return false; // Already editing.
                }

                $(this).attr("contenteditable", true);
                $(this).focus();
                $(this).parent().find("span.btn").css("visibility", "visible");

                var type = $(this).attr('data-name');

                if (type === 'starttime' || type === 'endtime') {
                    if ($(this).text().length === 0) {
                        $(this).attr("data-modified", true);
                    }
                    var date = $(this).attr('data-stud-date');
                    var time = $(this).attr('data-stud-time');
                    $(this).text(date + ' ' + time);
                }
            });

            // 
            // Refresh display and update attribute values.
            // 
            $(document).on('blur', '.st-exam-item-edit', function () {
                $(this).removeAttr("contenteditable");

                var type = $(this).attr('data-name');

                if (type === 'starttime' || type === 'endtime') {
                    var part = $(this).text().split(" ");

                    // 
                    // Check if date is invalid:
                    // 
                    if (part.length > 1) {
                        if (isNaN(Date.parse($(this).text()))) {
                            $(this).text($(this).attr('data-stud-date') + ' ' + $(this).attr('data-stud-time'));
                            return false;
                        }
                    } else {
                        if (isNaN(Date.parse($(this).attr('data-exam-date') + ' ' + $(this).text()))) {
                            $(this).text($(this).attr('data-stud-date') + ' ' + $(this).attr('data-stud-time'));
                            return false;
                        }
                    }

                    if (part.length > 1) {
                        if ($(this).attr('data-stud-date') !== part[0] || $(this).attr('data-stud-time') !== part[1]) {
                            $(this).attr("data-modified", true);
                        }
                        $(this).attr('data-stud-date', part[0]);
                        $(this).attr('data-stud-time', part[1]);
                    } else {
                        if ($(this).attr('data-stud-time') !== part[0]) {
                            $(this).attr("data-modified", true);
                        }
                        if ($(this).attr('data-stud-date') !== $(this).attr('data-exam-date')) {
                            $(this).attr("data-modified", true);
                        }
                        $(this).attr('data-stud-time', part[0]);
                        $(this).attr('data-stud-date', $(this).attr('data-exam-date'));
                    }
                    if ($(this).attr('data-stud-date') === $(this).attr('data-exam-date')) {
                        $(this).text($(this).attr('data-stud-time'));
                    }
                    if ($(this).attr('data-stud-time').length === 0) {
                        $(this).attr('data-stud-date', "");
                    }
                } else if (type === 'code') {
                    if ($(this).attr('data-stud-code') !== $(this).text()) {
                        $(this).attr('data-stud-code', $(this).text());
                        $(this).attr("data-modified", true);
                    }
                } else if (type === 'tag') {
                    if ($(this).attr('data-stud-tag') !== $(this).text()) {
                        $(this).attr('data-stud-tag', $(this).text());
                        $(this).attr("data-modified", true);
                    }
                }
            });

            // 
            // Save student properties.
            // 
            $(document).on('click', '.st-exam-item-save', function () {
                var data = {};
                var button = $(this).find("span.btn");
                var tblrow = $(this).parent();

                // 
                // Add editable item values to data object:
                // 
                $(this).parent().find(".st-exam-item-edit[data-modified=true]").each(function () {
                    var type = $(this).attr('data-name');

                    if (type === 'starttime' || type === 'endtime') {
                        data[type] = $(this).attr("data-stud-date") + ' ' + $(this).attr("data-stud-time");
                    } else if (type === 'code') {
                        data[type] = $(this).attr("data-stud-code");
                    } else if (type === 'tag') {
                        data[type] = $(this).attr("data-stud-tag");
                    }

                    data[type] = data[type].trim();
                });

                // 
                // Get student ID from data-id attribute:
                // 
                data.id = $(this).parent().find(".st-exam-detail").attr("data-id");

                // 
                // Send AJAX request. Hide save button on success.
                // 
                ajax(
                        baseURL + 'ajax/core/invigilator/student/update',
                        JSON.stringify(data),
                        function (response) {
                            if (response === true) {
                                button.css("visibility", "hidden");
                                tblrow.find(".st-exam-item-edit[data-modified=true]").each(function () {
                                    $(this).removeAttr("data-modified");
                                });
                            }
                        }
                );
            });

            // 
            // Unlock exam lock preventing student from using another computer.
            // 
            $(document).on("click", "#unlock-student", function () {
                var dataId = $(this).attr('data-id');
                var studId = $(this).attr('stud-id');
                ajax(
                        baseURL + 'ajax/core/invigilator/lock/delete',
                        {id: dataId},
                        function (status) {
                            $('a[data-id="' + studId + '"]').click();
                        });
            });

            // 
            // Approve prending student connection on exam.
            // 
            $(document).on("click", "#approve-student", function () {
                var dataId = $(this).attr('data-id');
                var studId = $(this).attr('stud-id');
                ajax(
                        baseURL + 'ajax/core/invigilator/lock/update',
                        {id: $(this).attr('data-id'), status: "approved"},
                        function (status) {
                            $('a[data-id="' + studId + '"]').click();
                        }
                );
            });

            // 
            // Reload exam lock status panel.
            // 
            $(document).on("click", "#lock-status-refresh", function () {
                $('a[data-id="' + $(this).attr('data-id') + '"]').click();
            });

            $(document).on("keyup", "#search-students", function () {
                var value = jQuery.trim($(this).val());
                $("table tr").each(function (index) {
                    if (index !== 0 && !$(this).hasClass('st-detail-rows')) {

                        $row = $(this);
                        $row.find("td").each(function (i, elem) {
                            if (jQuery.trim($(elem).text()).indexOf(value) !== 0) {
                                $row.hide();
                            } else {
                                $row.show();
                                return false;
                            }
                        });
                    }
                });
                $(".tablesorter").trigger("update");
                var sorting = [[0, 0], [1, 0]];
                $(".tablesorter").trigger("sorton", [sorting]);
            });

            $(document).on('click', '.st-exam-detail', function () {
                var row = $(this).closest("tr");
                var sid = $(this).attr('data-id');
                $.ajax({
                    url: baseURL + 'exam/lock',
                    type: 'POST',
                    cache: false,
                    data: {student_id: $(this).attr('data-id')}
                }).done(function (result) {
                    $('.st-detail-rows').hide();
                    $('#st-detail-row' + sid).show(500).insertAfter(row).find('td').html(result);
                });
                return false;
            });

            $(".tablesorter").bind("sortBegin", function (e, table) {
                $('.st-detail-rows').hide();
            });

            $(document).on('change', '#select_all_students', function () {
                $('input[name="students[]"]').prop("checked", this.checked);
            });

            $(document).on('click', '.del-student', function () {
                var student = $(this);
                if (confirm("Are you sure you want to delete this student?")) {
                    ajax(
                            baseURL + 'ajax/core/invigilator/student/delete',
                            {id: $(this).attr('data-id')},
                            function (status) {
                                jQuery.each(studentList, function (i, sData) {
                                    if (typeof sData !== 'undefined' && sData.id === $(student).attr('data-id')) {
                                        delete studentList[i];
                                    }
                                });

                                // 
                                // Hide from list:
                                // 
                                $(student).parent().slideUp('500', function () {
                                    $(this).remove();
                                });
                                if ($('.total-exam-students')) {
                                    $('.total-exam-students').html($('.student-list').find('li').length - 1);
                                }

                            }
                    );
                }
            });

            $(document).on('click', '#add_students_btn', function () {

                var stData = [];
                var examId = $(this).closest('#st-mng-wrapper').attr('exam-id');
                if (examId) {
                    stList = jQuery.trim($('#student_list').val()).split("\n");

                    //
                    // Prepare data object:
                    // 
                    $.each(stList, function (i, val) {
                        if (jQuery.trim(val) !== '') {
                            st = jQuery.trim(val).split(/\s/g);
                            if (st.length > 2) {
                                var tmp = '';
                                jQuery.each(st, function (i, e) {
                                    if (i) {
                                        tmp = tmp + " " + e;
                                    }
                                });
                                st[1] = jQuery.trim(tmp);
                            }

                            stData.push({exam_id: examId, user: st[0], code: st[1]});
                        }
                    });

                    // 
                    // Send AJAX request to add these students to the exam:
                    // 
                    ajax(
                            baseURL + 'ajax/core/invigilator/student/create',
                            JSON.stringify(stData),
                            function (userData) {
                                onStudentInserted(examId);
                            }
                    );
                }
            });

            // 
            // On select file type (file import):
            // 
            $(document).on('click', 'ul.dropdown-menu > li > a', function () {
                var target = $("div#file-type");
                target.children().first().text($(this).text()); // Display
                target.attr('type', $(this).attr('type')); // Save type
            });

            // 
            // Handle students file upload:
            // 
            $(document).on('click', '#import-students-by-file', function () {

                var data = new FormData($('form#student-file-import')[0]);
                data.append('type', $('#file-type').attr('type'));
                data.append('exam_id', $(this).closest('#st-mng-wrapper').attr('exam-id'));

                $.ajax({
                    url: baseURL + '/utility/import/students/file',
                    type: 'POST',
                    data: data,
                    cache: false,
                    contentType: false, // Prevent corrupted boundary strings.
                    processData: false    // No need to process data.
                }).done(function (result) {
                    $('#student-file-import-content').html(result);
                    $('#student-file-import-content').attr('id', 'student-data-import-content');
                    $('#import-students-by-file').attr('id', 'import-students-by-table');
                }).fail(function (message) {
                    alert("Failed submit form");
                });
            });

            // 
            // Handle student group import:
            // 
            $(document).on('click', '#import-students-by-group', function () {

                var data = new FormData($('form#student-group-import')[0]);
                data.append('group', $('#group-name').val());
                data.append('domain', $('#domain-name').val());
                data.append('exam_id', $(this).closest('#st-mng-wrapper').attr('exam-id'));

                $.ajax({
                    url: baseURL + '/utility/import/students/group',
                    type: 'POST',
                    data: data,
                    cache: false,
                    contentType: false, // Prevent corrupted boundary strings.
                    processData: false    // No need to process data.
                }).done(function (result) {
                    $('#student-group-import-content').html(result);
                    $('#student-group-import-content').attr('id', 'student-data-import-content');
                    $('#import-students-by-group').attr('id', 'import-students-by-table');
                }).fail(function (message) {
                    alert("Failed submit form");
                });
            });

            // 
            // Import students from table data (file or group import):
            // 
            $(document).on('click', '#import-students-by-table', function () {

                var examId = $(this).closest('#st-mng-wrapper').attr('exam-id');
                var stdata = [], sthead = [];

                // 
                // Create column type lookup table:
                // 
                $('#table-import-students thead tr th').each(function (i) {
                    sthead[i] = $(this).val();
                });

                // 
                // Process table body. Add students to object array:
                // 
                $('#table-import-students tbody tr').each(function () {
                    var stuobj = {exam_id: examId};
                    $(this).find('td').each(function (i) {
                        switch (sthead[i]) {
                            case 'user':
                                if ($(this).text() !== "") {
                                    stuobj.user = $(this).text();
                                }
                                break;
                            case 'code':
                                if ($(this).text() !== "") {
                                    stuobj.code = $(this).text();
                                }
                                break;
                            case 'tag':
                                if ($(this).text() !== "") {
                                    stuobj.tag = $(this).text();
                                }
                                break;
                            case 'pnr':
                                if ($(this).text() !== "" && stuobj.user === undefined) {
                                    stuobj.user = $(this).text();
                                }
                                break;
                        }
                    });
                    if (stuobj.user !== undefined && stuobj.user !== "") {
                        stdata.push(stuobj);
                    }
                });
                if (stdata.length === 0) {
                    alert("No student selected for import");
                    return;
                }

                // 
                // Send AJAX request to add students:
                // 
                ajax(
                        baseURL + 'ajax/core/invigilator/student/create',
                        JSON.stringify(stdata),
                        function (result) {
                            onStudentInserted(examId);
                        });
            });

            // 
            // Attach event for student deletion button
            // 
            $(document).on('change', 'input[name="students[]"], #select_all_students', function () {
                if ($('input[name="students[]"]:checked').length) {
                    $('#del-st-btn > span').html("Delete selected students (" + $('input[name="students[]"]:checked').length + ")").parent().show();
                } else {
                    $('#del-st-btn').hide();
                }
            });

            // 
            // Delete selected student:
            // 
            $(document).on('click', '#del-st-btn', function () {

                if (confirm("Are you sure you want to " + $('#del-st-btn > span').text().toLowerCase() + "?")) {

                    var delStudent = [];
                    $('input[name="students[]"]:checked').each(function (i, elem) {
                        delStudent.push({id: $(this).val()});
                    });
                    ajax(
                            baseURL + 'ajax/core/invigilator/student/delete',
                            JSON.stringify(delStudent),
                            function (status) {
                                $('input[name="students[]"]:checked').closest('tr').remove();
                            }
                    );
                }

                return false;
            });

            // 
            // Handle print student list.
            // 
            $(document).on("click", "#print-students-list", function () {
                var examId = $(this).closest('#st-mng-wrapper').attr('exam-id');
                window.location.href = baseURL + 'utility/export/students/' + examId + '/download';
            });
        })();
</script>
