<!-- Main area -->

<?= Phalcon\Tag::stylesheetLink('css/tablesorter.default.css'); ?>
<?= Phalcon\Tag::javascriptInclude('js/jquery.tablesorter.js'); ?>

<?php
$i = 0;
$stList = array();

foreach ($exam->students as $student) {
        $stList[$i]["id"] = $student->id;
        $stList[$i]["value"] = $student->user . " - " . $student->code;
        $i++;
}

?>
<div id="st-mng-wrapper" exam-id="<?= $this->request->getPost('exam_id') ?>">
    <div style="padding-bottom:15px">
        <h3><?= $exam->name ?></h3>
    </div>
    <div class="tabs">
        <ul>
            <li><a href="#tabs-1">Add new students</a></li>
            <li><a href="#tabs-2">Manage existing students</a></li>
        </ul>
        <div id="tabs-1">

            <div class="accordion">
                <h3>Add single or multiple students</h3>
                <div>
                    <p>
                        Write identities and anonymous code (optional) of single or multiple students. Separate the identity (username or personal number) and code by space.
                        The data should be separated by newlines when adding multiple students.
                        <br />
                        <small>
                            Format to add single student: <strong>identity code</strong><br />
                            Format to add multiple student: <br />
                            <strong>identity1 code1</strong><br />
                            <strong>identity1 code2</strong>
                        </small>
                    </p>
                    <textarea id="student_list" placeholder="identity code" style="height:100px; width:480px"></textarea>

                    <div style="display: block; margin:10px 0px 30px 0px;">   
                        <span id="add_students_btn" class="btn btn-success">
                            <i class="fa fa-chevron-circle-right"></i>
                            <span>Add students</span>
                        </span>
                    </div>                                
                </div>
                <h3>Import from file</h3>
                <div>
                    <div id="student-file-import-content">
                        <p>
                            Upload the file containing students to import. Students can be imported by username or personal number, with optional supplied anonymous code and/or tag.
                        </p>
                        <form id="student-file-import" name="student-file-import">
                            <input type="file" name="file[]" />                                
                            <div class="btn-group" style="padding-top: 5px">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"> Filetype 
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#" type='-1'>Auto Detect</a></li>
                                    <li><a href="#" type='oocalc'>OpenDocument Format Spreadsheet (*.ods,*.ots)</a></li>
                                    <li><a href="#" type='excel2007'>Microsoft Excel 2007/2010/2013 XML (*.xlsx)</a></li>
                                    <li><a href="#" type='excel2003'>Microsoft Excel 2003 XML (*.xml)</a></li>
                                    <li><a href="#" type='excel97'>Microsoft Excel 97/2000/XP/2003 (*.xls,*.xlt)</a></li>
                                    <li><a href="#" type='tab'>TAB Separated Values (*.tab,*.tsv,*.txt)</a></li>
                                    <li><a href="#" type='csv'>CSV File (*.csv)</a></li>
                                    <li><a href="#" type='gnumeric'>Gnumeric Spreadsheet (*.gnumeric)</a></li>
                                    <li><a href="#" type='html'>HTML Document (*.htm,*.html)</a></li>
                                    <li><a href="#" type='sylk'>SYLK Document (*.slk,*.sylk)</a></li>
                                </ul>
                                <div id='file-type' type='-1' style="padding: 5px 0"><span style="margin-left: 10px">Auto Detect</span></div>
                            </div>
                        </form>
                    </div>

                    <div style="display: block; margin:10px 0px 30px 0px;">        
                        <span id="import-students-by-file" class="btn btn-success">
                            <i class="fa fa-chevron-circle-right"></i>
                            <span>Import students</span>
                        </span>
                    </div>                                
                </div>
                <h3>Import from group</h3>
                <div>
                    <div id="student-group-import-content">
                        <p>
                            Supply the name of a group to import students from. The name could e.g. be a course code or a domain group. The search can be restricted to a single domain.
                        </p>
                        <form id="student-file-import" name="student-group-import">
                            <div>
                                <label for="group">Group name:</label>
                                <input id="group-name" type="text" name="group" placeholder="3MK579" /><br />
                                <label for="domain">Domain:</label> 
                                <select id="domain-name" name="domain">
                                    <option></option>
                                    <?php foreach ($domains as $domain): ?>
                                            <option><?= $domain ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </form>
                    </div>

                    <div style="display: block; margin:10px 0px 30px 0px;">   
                        <span id="import-students-by-group" class="btn btn-success">
                            <i class="fa fa-chevron-circle-right"></i>
                            <span>Import students</span>
                        </span>
                    </div> 
                </div>
            </div>
        </div>
        <div id="tabs-2">
            <h4 style="float:left">Registered students in this exam</h4>

            <div style="clear:both"></div>

            <?php if (!count($exam->students)): ?>
                    <div id="no-student-msg">
                        <em>No students have been added to the exam yet.</em>
                    </div>
            <?php else: ?>
                    <div id="print-students-list" style="float:left; display: inline; margin-bottom: 10px; margin-right: 5px;">        
                        <span class="btn btn-success">
                            <i class="fa fa-print"></i>
                            <span>Download</span>
                        </span>
                    </div>                                

                    <div style="float:left; margin-bottom: 10px;">
                        <span id='del-st-btn' class="btn btn-danger" style="display: none">
                            <i class="fa fa-trash-o"></i>
                            <span></span>
                        </span>
                    </div>
                    <div style="float:right">
                        <input id="search-students" type="text" placeholder="Filter students" style="width:145px; height:15px;" />
                        <span class="label label-orange filter-students"><i style="color:#FFF" class="fa fa-search"></i></span>
                    </div>
                    <table id="all-students-table" style="width:100%" class="tablesorter">
                        <thead>
                            <tr>
                                <th class="no-sort"><input id="select_all_students" type="checkbox" value="1"></th>
                                <th>Name</th>
                                <th>Username</th>
                                <th>Person no.</th>
                                <th>Start time</th>
                                <th>End time</th>
                                <th>Code</th>
                                <th>Tag</th>
                            </tr>    
                        </thead>
                        <tbody>
                            <?php foreach ($exam->students as $student): ?>
                                    <tr style="background-color:#D9ECF2;">
                                        <td><input name="students[]" type="checkbox" value="<?= $student->id ?>"></td>
                                        <td>
                                            <a href="#" data-id="<?= $student->id ?>" class="st-exam-detail" style="color:blue">
                                                <?= $this->catalog->getName($student->user) ?>
                                            </a>
                                        </td>
                                        <td><?= $student->user ?></td>
                                        <td><?= $this->catalog->getPersonalNumber($student->user) ?></td>
                                        <td>
                                            <span style="color:blue; cursor: pointer" class="st-exam-time" for="starttime" exam-date="<?= !empty($exam->starttime) ? date("Y-m-d", strtotime($exam->starttime)) : ""; ?>">
                                                <?= !empty($student->starttime) ? date("H:i", strtotime($student->starttime)) : "---" ?>
                                            </span>
                                        </td>
                                        <td>
                                            <span style="color:blue; cursor: pointer" class="st-exam-time" for="endtime" exam-date="<?= !empty($exam->starttime) ? date("Y-m-d", strtotime($exam->endtime)) : ""; ?>">
                                                <?= !empty($student->endtime) ? date("H:i", strtotime($student->endtime)) : "---" ?>
                                            </span>
                                        </td> 
                                        <td><?= $student->code ?></td>
                                        <td><?= $student->tag ?></td>
                                    </tr>
                                    <tr class="st-detail-rows" style="display:none;" id="st-detail-row<?= $student->id ?>">
                                        <td colspan="10" style="background-color:#ffe;"></td>
                                    </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
            <?php endif; ?>
            <div style="clear:both"></div>
        </div>
    </div>
</div>

<script language="javascript">
        console.log("<?= $_SERVER['SERVER_ADDR']; ?>");
        var studentList = <?= json_encode($stList) ?>;

        $(function () {

            $('.tablesorter').tablesorter({
                widgets: ['zebra', 'columns'],
                usNumberFormat: false,
                sortReset: true,
                sortRestart: true,
                sortList: [[0, 0], [1, 0]],
                headers: {
                    '.no-sort': {
                        sorter: false
                    }
                }
            });

            $('.tabs').tabs();

            $(".accordion").accordion({
                heightStyle: "content"
            });

            if (stEvents == 'loaded') {
                return;
            } else {
                stEvents = 'loaded';
            }

            // 
            // Called after students has been added to exam.
            // 
            // @param array userData The array of newly created student objects.
            // 
            var onStudentInserted = function (userData) {

                if (userData.length > 1) {
                    var examId = userData[0].exam_id;
                } else {
                    var examId = userData.exam_id;
                }

                $.ajax({
                    type: "POST",
                    data: {'exam_id': examId},
                    url: baseURL + 'exam/students/',
                    success: function (content) {
                        // 
                        // Replace dialog content:
                        // 
                        $("#manage-students").html(content);

                        // 
                        // Switch to second tab:
                        // 
                        $(".tabs").tabs("option", "active", 1);
                        $('#no-student-msg').hide();
                    }
                });
            }

            var updatingStExamTime = false;

            $(document).on('click', '.st-exam-time', function () {
                var field = $(this).attr('for');
                var currVal = jQuery.trim($(this).html());
                if (currVal.indexOf('<input') == -1 && !updatingStExamTime) {

                    $('.st-exam-time-input').each(function (i, elem) {
                        $(elem).parent().html($(elem).val() === '' ? '---' : $(elem).val());
                    });

                    $(this).html(
                            '<input class="st-exam-time-input" name="' + field + '" type="text" value="' + (currVal == '---' ? '' : currVal) + '" placeholder="HH:MM" style="height:13px; width:38px">' +
                            '<input type="button" value="ok" class="st-exam-time-save">'
                            );
                    $(this).find('input[type=text]').focus();
                }
                updatingStExamTime = false;
                return false;
            });

            $(document).on('click', '.st-exam-time-save', function () {

                var stData = [];
                var stId = $(this).closest('tr').find('td>input[type=checkbox]').val();
                var currVal = $(this).parent().find('input[type=text]').val();
                var inputElem = $(this).parent().find("input[type=text]");

                if ($(inputElem).parent().attr('exam-date') == "") {
                    alert("Failed to save data. Please set start date and time for the exam first.");
                    currVal = '';
                } else {

                    if ($(inputElem).prop('name') === 'starttime') {
                        stData.push({'id': stId, 'starttime': $(inputElem).parent().attr('exam-date') + " " + currVal});
                    } else if ($(inputElem).prop('name') === 'endtime') {
                        stData.push({'id': stId, 'endtime': $(inputElem).parent().attr('exam-date') + " " + currVal});
                    } else {
                        alert("Sorry, failed to save data");
                        return false;
                    }

                    ajax(
                            baseURL + 'ajax/core/invigilator/student/update',
                            JSON.stringify(stData),
                            function (userData) {
                            }
                    );
                }

                $(this).parent().html(currVal === '' ? '---' : currVal);
                updatingStExamTime = true;

            });

            // 
            // Unlock exam lock preventing student from using another computer.
            // 
            $(document).on("click", "#unlock-student", function () {
                var dataId = $(this).attr('data-id');
                var studId = $(this).attr('stud-id');
                
                ajax(
                        baseURL + 'ajax/core/invigilator/lock/delete',
                        {"id": dataId},
                function (status) {
                    $('a[data-id="' + studId + '"]').click();
                });
            });

            // 
            // Approve prending student connection on exam.
            // 
            $(document).on("click", "#approve-student", function () {
                var dataId = $(this).attr('data-id');
                var studId = $(this).attr('stud-id');

                ajax(
                        baseURL + 'ajax/core/invigilator/lock/update',
                        {"id": $(this).attr('data-id'), "status": "approved"},
                function (status) {
                    $('a[data-id="' + studId + '"]').click();
                }
                );
            });

            // 
            // Reload exam lock status panel.
            // 
            $(document).on("click", "#lock-status-refresh", function () {
                $('a[data-id="' + $(this).attr('data-id') + '"]').click();
            });

            $(document).on("keyup", "#search-students", function () {
                var value = jQuery.trim($(this).val());

                $("table tr").each(function (index) {
                    if (index != 0 && !$(this).hasClass('st-detail-rows')) {

                        $row = $(this);
                        $row.find("td").each(function (i, elem) {
                            if (jQuery.trim($(elem).text()).indexOf(value) != 0) {
                                $row.hide();
                            } else {
                                $row.show();
                                return false;
                            }
                        });
                    }
                });

                $(".tablesorter").trigger("update");
                var sorting = [[0, 0], [1, 0]];
                $(".tablesorter").trigger("sorton", [sorting]);
            });

            $(document).on('click', '.st-exam-detail', function () {
                var row = $(this).closest("tr");
                var sid = $(this).attr('data-id');

                $.ajax({
                    url: baseURL + 'exam/lock',
                    type: 'POST',
                    cache: false,
                    data: {"student_id": $(this).attr('data-id')}
                }).done(function (result) {
                    $('.st-detail-rows').hide();
                    $('#st-detail-row' + sid).show(500).insertAfter(row).find('td').html(result);
                });

                return false;
            });

            $(".tablesorter").bind("sortBegin", function (e, table) {
                $('.st-detail-rows').hide();
            });

            $(document).on('change', '#select_all_students', function () {
                $('input[name="students[]"]').prop("checked", this.checked);
            });

            $(document).on('click', '.del-student', function () {
                var student = $(this);
                if (confirm("Are you sure you want to delete this student?")) {
                    ajax(
                            baseURL + 'ajax/core/invigilator/student/delete',
                            {"id": $(this).attr('data-id')},
                    function (status) {
                        jQuery.each(studentList, function (i, sData) {
                            if (typeof sData !== 'undefined' && sData.id == $(student).attr('data-id')) {
                                delete studentList[i];
                            }
                        });
                        // 
                        // Hide from list:
                        // 
                        $(student).parent().slideUp('500', function () {
                            $(this).remove();
                        });
                        if ($('.total-exam-students')) {
                            $('.total-exam-students').html($('.student-list').find('li').length - 1);
                        }

                    }
                    );
                }
            });

            $(document).on('click', '#add_students_btn', function () {

                var stData = [];
                var examId = $(this).closest('#st-mng-wrapper').attr('exam-id');
                if (examId) {
                    stList = jQuery.trim($('#student_list').val()).split("\n");
                    //
                    // Prepare data object:
                    // 
                    $.each(stList, function (i, val) {
                        if (jQuery.trim(val) != '') {
                            st = jQuery.trim(val).split(/\s/g);
                            if (st.length > 2) {
                                var tmp = '';
                                jQuery.each(st, function (i, e) {
                                    if (i) {
                                        tmp = tmp + " " + e;
                                    }
                                });
                                st[1] = jQuery.trim(tmp);
                            }

                            stData.push({'exam_id': examId, "user": st[0], "code": st[1]});
                        }
                    });
                    // 
                    // Send AJAX request to add these students to the exam:
                    // 
                    ajax(
                            baseURL + 'ajax/core/invigilator/student/create',
                            JSON.stringify(stData),
                            function (userData) {
                                onStudentInserted(userData);
                            }
                    );
                }
            });

            // 
            // On select file type (file import):
            // 
            $(document).on('click', 'ul.dropdown-menu > li > a', function () {
                var target = $("div#file-type");
                target.children().first().text($(this).text()); // Display
                target.attr('type', $(this).attr('type')); // Save type
            });

            // 
            // Handle students file upload:
            // 
            $(document).on('click', '#import-students-by-file', function () {

                var data = new FormData($('form#student-file-import')[0]);
                data.append('type', $('#file-type').attr('type'));
                data.append('exam_id', $(this).closest('#st-mng-wrapper').attr('exam-id'));
                $.ajax({
                    url: baseURL + '/utility/import/students/file',
                    type: 'POST',
                    data: data,
                    cache: false,
                    contentType: false, // Prevent corrupted boundary strings.
                    processData: false    // No need to process data.
                }).done(function (result) {
                    $('#student-file-import-content').html(result);
                    $('#student-file-import-content').attr('id', 'student-data-import-content');
                    $('#import-students-by-file').attr('id', 'import-students-by-table');
                }).fail(function (message) {
                    alert("Failed submit form")
                });
            });

            // 
            // Handle student group import:
            // 
            $(document).on('click', '#import-students-by-group', function () {
                var data = new FormData($('form#student-group-import')[0]);
                data.append('group', $('#group-name').val());
                data.append('domain', $('#domain-name').val());
                data.append('exam_id', $(this).closest('#st-mng-wrapper').attr('exam-id'));
                $.ajax({
                    url: baseURL + '/utility/import/students/group',
                    type: 'POST',
                    data: data,
                    cache: false,
                    contentType: false, // Prevent corrupted boundary strings.
                    processData: false    // No need to process data.
                }).done(function (result) {
                    $('#student-group-import-content').html(result);
                    $('#student-group-import-content').attr('id', 'student-data-import-content');
                    $('#import-students-by-group').attr('id', 'import-students-by-table');
                }).fail(function (message) {
                    alert("Failed submit form")
                });
            });

            // 
            // Import students from table data (file or group import):
            // 
            $(document).on('click', '#import-students-by-table', function () {

                var examId = $(this).closest('#st-mng-wrapper').attr('exam-id');
                var stdata = [], sthead = [];

                // 
                // Create column type lookup table:
                // 
                $('#table-import-students thead tr th').each(function (i) {
                    sthead[i] = $(this).val();
                });

                // 
                // Process table body. Add students to object array:
                // 
                $('#table-import-students tbody tr').each(function () {
                    var stuobj = {'exam_id': examId};
                    $(this).find('td').each(function (i) {
                        switch (sthead[i]) {
                            case 'user':
                                if ($(this).text() !== "") {
                                    stuobj.user = $(this).text();
                                }
                                break;
                            case 'code':
                                if ($(this).text() !== "") {
                                    stuobj.code = $(this).text();
                                }
                                break;
                            case 'tag':
                                if ($(this).text() !== "") {
                                    stuobj.tag = $(this).text();
                                }
                                break;
                            case 'pnr':
                                if ($(this).text() !== "" && stuobj.user === undefined) {
                                    stuobj.user = $(this).text();
                                }
                                break;
                        }
                    });
                    if (stuobj.user !== undefined && stuobj.user !== "") {
                        stdata.push(stuobj);
                    }
                });
                if (stdata.length === 0) {
                    alert("No student selected for import");
                    return;
                }

                // 
                // Send AJAX request to add students:
                // 
                ajax(
                        baseURL + 'ajax/core/invigilator/student/create',
                        JSON.stringify(stdata),
                        function (result) {
                            onStudentInserted(result)
                        });
            });

            // 
            // Attach event for student deletion button
            // 
            $(document).on('change', 'input[name="students[]"], #select_all_students', function () {
                if ($('input[name="students[]"]:checked').length) {
                    $('#del-st-btn > span').html("Delete selected students (" + $('input[name="students[]"]:checked').length + ")").parent().show();
                } else {
                    $('#del-st-btn').hide();
                }
            });

            // 
            // Delete selected student:
            // 
            $(document).on('click', '#del-st-btn', function () {
                if (confirm("Are you sure you want to " + $('#del-st-btn > span').html() + "?")) {

                    var delStudent = [];
                    $('input[name="students[]"]:checked').each(function (i, elem) {
                        delStudent.push({'id': $(this).val()});
                    });

                    ajax(
                            baseURL + 'ajax/core/invigilator/student/delete',
                            JSON.stringify(delStudent),
                            function (status) {
                                $('input[name="students[]"]:checked').closest('tr').remove();
                            }
                    );
                }
            });

            // 
            // Handle print student list.
            // 
            $(document).on("click", "#print-students-list", function () {
                var examId = $(this).closest('#st-mng-wrapper').attr('exam-id');
                window.location.href = baseURL + 'utility/export/students/' + examId + '/download'
            });

        });
</script>
