<?php

// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    update.phtml
// 
// Author:  Ahsan Shahzad (Medfarm DoIT)
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 


use Phalcon\Tag;

?>

<?= Tag::stylesheetLink('plugins/jquery-ui/jquery-ui.min.css'); ?>
<?= Tag::stylesheetLink('plugins/validation/css/validationEngine.jquery.css'); ?>

<?= Tag::stylesheetLink('css/opentip.css'); ?>

<?= Tag::javascriptInclude('js/modernizr.js') ?>
<?= Tag::javascriptInclude('plugins/jquery-ui/jquery-ui.min.js'); ?>
<?= Tag::javascriptInclude('plugins/ckeditor/ckeditor.js'); ?>
<?= Tag::javascriptInclude('plugins/ckeditor/adapters/jquery.js'); ?>
<?= Tag::javascriptInclude('plugins/validation/js/languages/jquery.validationEngine-en.js') ?>
<?= Tag::javascriptInclude('plugins/validation/js/jquery.validationEngine.js') ?>
<?= Tag::javascriptInclude('js/opentip-jquery.min.js'); ?>
<?= Tag::javascriptInclude('js/opentip-style.js'); ?>

<?= Tag::javascriptInclude('js/views/exam/create.js'); ?>
<?= Tag::javascriptInclude('js/views/exam/security.js'); ?>
<?= Tag::javascriptInclude('js/views/exam/check.js'); ?>
<?= Tag::javascriptInclude('js/views/user-search.js'); ?>

<?php $examQs = $exam->getQuestions(array("order" => "slot")); ?>

<!-- User search support -->
<?php $this->partial("partials/user-search", array('staff' => $staff)) ?>

<?php
if (in_array("contributable", $exam->flags)) {
        $exam->is_contributable = true;
} else {
        $exam->is_contributable = false;
}
if (in_array("published", $exam->flags)) {
        $exam->is_published = true;
} else {
        $exam->is_published = false;
}
if (in_array("editable", $exam->flags)) {
        $exam->is_editable = true;
} else {
        $exam->is_editable = false;
}

?>

<style>
    div.question-removed {
        opacity: 0.25;
        filter: grayscale(100%);
    }
    .qs_area_line_q_parts {
        margin-left: 10px;
    }
    .qs_area_line_q_no {
        color: #333333;
        font-size: 16px;
        padding: 0 15px 15px 0;
        background-color: #ffffee;
        border: 2px solid #fbeed5;
        border-radius: 5px;
        padding: 5px 8px 5px 5px;
        max-height: 125px;
        min-width: 70px;
        padding: 10px;
    }    
    .qs_area_line_q_no .q_score{
        font-size: 10px; 
        padding-top: 5px; 
        color: #999999;
    }    
    .qs_area_line {
        padding-bottom: 25px;
        display: flex;
    }
    .qs_area_line_q {
        padding-bottom: 15px;
        border-left: 2px solid #fbeed5;
        padding-left: 10px;
        min-height: 85px;
        min-width: 400px;
    }  
    .q_line_op {
        padding-top: 15px; 
        font-size: 15px; 
        text-align: center
    }    
    .qs_area_line_q .q_fields {
        padding-left: 15px;
    }   
    .view-q > i {
        color: #008803;
    }
    .insert-q > i, 
    .remove-q > i {
        color: #ff7300;
    }
    .edit-q > i,
    .edit-q.editable > i,
    .edit-q.published.editable > i {
        color: #004276;
    }
    .edit-q.published > i {
        color: #994276;
    }
    .q-tool-item {
        float: left; 
        margin-right: 3px;
        padding: 2px;
    }
</style>

<!-- Main area -->         
<div class="oe-columns-container">
    <!-- Left Column -->
    <div class="oe-left-column">
        <?php $this->partial("partials/left-menu", array('exam' => $exam)) ?> 
    </div>
    <div class="oe-right-column">

        <?php if ($exam->published): ?>
                <?= Tag::image(array("img/published.gif", "style" => "z-index: 0; height: 65px; position: relative; float: right; top: -9px;")); ?>
        <?php endif; ?>

        <!-- Exam title and description: -->
        <h1 class="page">
            <?= strlen(trim($exam->name)) > 0 ? $exam->name : '&lt;Untitled exam&gt;' ?>
            <div class="tool-icons">

                <?php if ($this->user->hasCapability($exam, 'update')) : ?>
                        <a href="#" class="prevent exam-settings">
                            <i class="fa fa-gear" id="exam-settings" style="float:right;padding:3px"></i>
                        </a> 
                        <a href="#" class="prevent exam-security">
                            <i class="fa fa-lock" id="exam-security" style="float:right;padding:3px"></i>
                        </a>                
                        <a href="#" class="prevent exam-check">
                            <i class="fa fa-check-square" id="exam-check" style="float:right;padding:3px"></i>
                        </a>                
                        <a href="#" class="prevent exam-archive">
                            <i class="fa fa-file-archive-o" id="exam-archive" style="float:right;padding:3px"></i>
                        </a>                
                <?php endif; ?>
            </div>
        </h1>

        <?php if ($this->user->hasCapability($exam, 'update')) : ?>
                <div style="float: left;border: 1px dashed #ddddee;padding: 2px 10px 2px 10px;margin-bottom: 10px; width:100%; max-width: 30em"><?= $check->render(); ?></div>
        <?php endif; ?>

        <?php if ($this->user->hasCapability('question', 'create') && $exam->is_contributable): ?>
                <a href="#" class="add_new_qs">
                    <div style="display: block; float:right">
                        <span class="btn btn-success">
                            <i class="fa fa-plus-circle"></i>
                            <span>Add new question</span>
                        </span>
                    </div>                        
                </a>
        <?php endif; ?>

        <div class="seprator" style="border-bottom:0px">&nbsp;</div>

        <!-- Questions area: -->
        <div id="qs_area" style="float: left;margin-top: 1.5em;">

            <div id="default_msg_qs">
                There are no questions in this exam yet. <br>
            </div>

            <!-- Question line template: -->
            <div class="qs_area_line" q-id="" q-no="" style="display:none">
                <div class="qs_area_line_q_no">
                    <div class="q_no"></div>
                    <div class="q_score"></div>
                    <div class="q_line_op">
                        <?php if ($exam->is_published) : ?>
                                <a href="#" class="q-tool-item view-q" title="Preview question"><i class="fa fa-eye"></i></a>
                                <a href="#" class="q-tool-item edit-q published" title="Edit question"><i class="fa fa-pencil"></i></a>
                                <br>
                                <a href="#" class="q-tool-item remove-q" style="display: block" title="Flag question as removed from this exam"><i class="fa fa-caret-square-o-right"></i></a>
                                <a href="#" class="q-tool-item insert-q" style="display: none" title="Re-add removed question on this exam"><i class="fa fa-caret-square-o-left"></i></a>
                        <?php else : ?>
                                <a href="#" class="q-tool-item view-q" title="Preview question"><i class="fa fa-eye"></i></a>
                                <a href="#" class="q-tool-item edit-q editable" title="Edit question"><i class="fa fa-pencil"></i></a>
                                <br>
                                <a href="#" class="q-tool-item remove-q" style="display: block" title="Flag question as removed from this exam"><i class="fa fa-caret-square-o-right"></i></a>
                                <a href="#" class="q-tool-item insert-q" style="display: none" title="Re-add removed question on this exam"><i class="fa fa-caret-square-o-left"></i></a>
                                <a href="#" class="q-tool-item del-q" title="Delete question from this exam"><i class="fa fa-close"></i></a>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="qs_area_line_q_parts">
                    <div class="qs_area_line_q" style="display:none">
                        <div class="q_head">
                            <div style="padding-bottom:5px">
                                <span class="q_part_no" style="font-size:16px; padding-right:0px"></span>
                                <span class="q_part_pt" style="color:grey; font-size:10px"></span>
                            </div>
                            <span class="q_title"></span>
                        </div>
                        <div class="q_fields" style="float:left"></div>
                        <br style="clear:both"/>
                    </div>
                </div>   
            </div>   
        </div>

        <?php if ($this->user->hasCapability($exam, 'update') && $exam->is_editable): ?>
                <div id="exam_op_btns" style="clear: both;<?= !count($examQs) ? 'display:none' : '' ?>">
                    <center>
                        <a href="<?= $this->url->get('exam/' . $exam->id) ?>">
                            <span class="btn btn-default" style="color:#333333">
                                <i class="fa fa-chevron-circle-right"></i>
                                <span>Preview student view</span>
                            </span>
                        </a>
                    </center>
                </div>

        <?php elseif ($this->user->hasCapability('question', 'create') && $exam->is_editable): ?>
                <a href="<?= $this->url->get('exam/index'); ?>">
                    <div id="" style="margin-bottom: 10px">
                        <center>
                            <span class="btn btn-success">
                                <i class="fa fa-chevron-circle-right"></i>
                                <span>I am done with my questions. Notify exam creator.</span>
                            </span>
                        </center>
                    </div>
                </a>
        <?php endif; ?>
    </div>
</div>

<!-- Add / Edit question form that appears in light box -->
<div id="question-form-dialog-wrap" q-no="" style="display:none" title=""></div>

<!-- Student management form -->
<div id="manage-students" title="Manage students for exam" style="display:none"></div>

<!-- Exam settings -->
<div id="exam-settings-box" style="display:none" title="Exam settings" ></div>

<!-- Exam security -->
<div id="exam-security-box" style="display:none" title="Security and access control" ></div>

<!-- Exam status check -->
<div id="exam-check-box" style="display:none" title="Exam status check" ></div>

<!-- Exam archive tool -->
<div id="exam-archive-box" style="display:none" title="Offline tool for exam" >
    <h1>Exam export and archive tool</h1>
    <div class="alert alert-info gw-box fade in" style="padding-top: 8px; padding-bottom: 8px; position: inherit; width: unset; font-weight: normal; text-align: left">
        Use this tool to access exam content (i.e. questions) in format suitable for printing or archiving. 
        This is also the right tool to use if some students need to write this exam on paper.
    </div>
    <a style="display: none" href="<?= $this->url->get('exam/archive/' . $exam->id); ?>" id="exam-archive-action-online" target="_blank"></a>
    <a style="display: none" href="<?= $this->url->get('exam/archive/' . $exam->id) . '/download'; ?>" id="exam-archive-action-download"></a>
    <div class="st-line">
        <center>
            <span style="min-width: 9em" class="btn btn-default" id="exam-archive-online">
                <i class="fa fa-external-link"></i>
                <span>View Online</span>
            </span>
            <span style="min-width: 9em" class="btn btn-default" id="exam-archive-download">
                <i class="fa fa-file-archive-o"></i>
                <span>Download Archive</span>
            </span>
        </center>		
    </div>
    <hr>
    <div class="st-line">
        <center>
            <span style="min-width: 6em; float: right" class="btn btn-success" id="close-archive">
                <i class="fa fa-undo"></i>
                <span>Close</span>
            </span>
        </center>		
    </div>
</div>

<?php
// 
// Combine question JSON to initialize exam.
// 
$combinedJson = array();
$questionNo = 1;
foreach ($examQs as $qData) {
        // 
        // Add questId node:
        // 
        $qJson = json_decode($qData->quest, true);
        $qJson['questId'] = $qData->id;
        $qJson['canUpdate'] = 1;
        $qJson['status'] = $qData->status;

        $combinedJson[$questionNo++] = $qJson;
}
$combinedJson = (!count($combinedJson) ? "JSON.parse('{}')" : json_encode($combinedJson));

?>
<script language="javascript">
        var mngr = '<?= $exam->creator ?>';
        var user = '<?= $this->user->getPrincipalName() ?>';
        var mode = '<?= $mode ?>';
        var role = '<?= $role ?>';
        var examId = <?= $exam->id ?>;
        var qsJson = <?= $combinedJson ?>;
        var qsCorrectorsJson = {};
        var showAddQuestionView = <?= stristr($_SERVER['REQUEST_URI'], 'add-q') ? 'true' : 'false' ?>;
        var isNewExam = <?= stristr($_SERVER['REQUEST_URI'], 'new-exam') ? 'true' : 'false' ?>;
</script>
