<?= Phalcon\Tag::stylesheetLink('plugins/jqueryui/themes/blitzer/jquery-ui.css'); ?>
<?= Phalcon\Tag::stylesheetLink('plugins/jqueryui/themes/blitzer/jquery.ui.autocomplete.css'); ?>
<?= Phalcon\Tag::stylesheetLink('plugins/jqueryui/themes/blitzer/jquery.ui.timepicker.css'); ?>
<?= Phalcon\Tag::stylesheetLink('plugins/validation/css/validationEngine.jquery.css'); ?>
<?= Phalcon\Tag::stylesheetLink('css/opentip.css'); ?>

<?= Phalcon\Tag::javascriptInclude('js/opentip-jquery.min.js'); ?>
<?= Phalcon\Tag::javascriptInclude('plugins/jqueryui/jquery-ui.js'); ?>
<?= Phalcon\Tag::javascriptInclude('plugins/jqueryui/ui/jquery-ui-timepicker.js'); ?>
<?= Phalcon\Tag::javascriptInclude('js/modernizr.js') ?>
<?= Phalcon\Tag::javascriptInclude('plugins/ckeditor/ckeditor.js'); ?>
<?= Phalcon\Tag::javascriptInclude('plugins/ckeditor/adapters/jquery.js'); ?>
<?=Phalcon\Tag::javascriptInclude('plugins/validation/js/languages/jquery.validationEngine-en.js')?>
<?=Phalcon\Tag::javascriptInclude('plugins/validation/js/jquery.validationEngine.js')?>

<?= Phalcon\Tag::javascriptInclude('js/views/exam/create.js'); ?>

<?php use \OpenExam\Library\Security\Roles;?>

<!-- Left Column -->
<?php $this->partial("exam/shared/left-menu", array('exam' => $exam, 'capabilities' => $capabilities)) ?>

<!-- Main area -->         
<?php $canUpdateExam = $capabilities->hasCapability($exam, 'update');?>
<div id="container" class="left_menu_space" style="">
        <div id="breadcrumbsRow">&nbsp;</div>
        <div id="centerColWide">

                <? /* --Exam title and description-- */ ?>
                <h1>
                        <?php if($canUpdateExam):?>
                        <input id="exam-title" class="exam-title" type="text" placeholder="Write exam title here" value="<?=trim($exam->name)?>" />
                        <a href="#" class="prevent">
                                <i class="fa fa-gear" id="exam-settings"></i>
                        </a>
                        <?php else:?>
                        <?=trim($exam->name)?>
                        <?php endif;?>
                </h1>
                
                <?php if($canUpdateExam && in_array("editable", $exam->flags)):?>
                <textarea id="exam-desc"  style="width:99%;" rows="1" placeholder="Write exam description here"><?= trim($exam->descr) ?></textarea>
                <?php else:?>
                <div style="width:99%;"><?=trim($exam->descr)?></div>
                <?php endif;?>

                <? /* --seprator-- */ ?>
                <div class="seprator" style=" <?=(in_array("contributable", $exam->flags)) ? "margin-bottom:0px":""?>"></div>

		<?php if($canUpdateExam && in_array("contributable", $exam->flags)):?>
                <a href="#" style="font-size: 12px; float:right" class="add_new_qs">
                        <div style="display: block; float:right">
                                <span class="btn btn-success" style="padding:2px; font-size:11px">
                                        <i class="fa fa-plus-circle"></i>
                                        <span>Add a new question</span>
                                </span>
                        </div>                        
                </a>
                <?php endif;?>

                <? /* --Questions area-- */ ?>
                <div id="qs_area">
                
                        <? /* --default message when there are no questions-- */ ?>
                        <div id="default_msg_qs">
                                There are no questions in this exam yet. <br>
                                <?php /*if(($myRole == Roles::CONTRIBUTOR || $myRole == Roles::CREATOR) && in_array("editable", $exam->flags)):?>
                                <a href="#" style="font-size: 12px;" class="add_new_qs"><?= Phalcon\Tag::image("img/plus-button-2.png"); ?> Add a question</a>
                                <?php endif;*/?>
                        </div>

                        <? /* --Question lines-- */ ?>
                        <!-- question line template -->
                        <div class="qs_area_line" q-no="" style="display:none">
                                <div class="qs_area_line_q_no">
                                        <div class="q_no"></div>
                                        <div class="q_score"></div>
                                        <?php if($myRole == Roles::CREATOR && in_array("editable", $exam->flags)):?>
                                        <div class="q_line_op">
                                                <a href="#"><i class="fa fa-pencil edit-q" style="color:#004276"></i></a>
                                                <a href="#"><i class="fa fa-close del-q"></i></a>
                                        </div>
                                        <?php endif;?>
                                </div>
                                <div class="qs_area_line_q_parts">
                                        <div class="qs_area_line_q" style="display:none">
                                                <div class="q_head">
                                                        <span class="q_part_no"></span>
                                                        <span class="q_title"></span>
                                                </div>
                                                <div class="q_fields"></div>
                                        </div>
                                </div>   
                        </div>   
                </div>
                
		<?php if( $canUpdateExam && in_array("editable", $exam->flags) ):?>
                <div id="save_exam_btn">
                        <center>
                                <span class="btn btn-success">
                                        <i class="fa fa-chevron-circle-right"></i>
                                        <span>Exam is ready, publish this exam</span>
                                </span>
                        </center>
                </div>
		<?php endif;?>

                <!-- centerColWide --> 
        </div>
        <br clear="both">
        <!-- container --> 
</div>

<!--------------- Hidden Divs ----------------->     
<!-- Add / Edit question form that appears in light box -->
<div id="question-form-dialog-wrap" q-no="" style="display:none" title=""></div>

<!-- Exam settings -->
<div id="exam-settings-box" style="display:none">
	<div class="exam-settings-box">
        <div class="st-line">
                <label for="unit"><b>Organization:</b></label>
                <?php if($canUpdateExam && in_array("editable", $exam->flags)):?>
                <input type="text" value="<?= $exam->orgunit ?>" name="unit">
                <?php else:?>
                <?= $exam->orgunit ?>
		<?php endif;?>
        </div>

        <div class="st-line">
                <label for="start"><b>Exam Start time:</b></label>
                <?php if($canUpdateExam && in_array("editable", $exam->flags)):?>
                <input type="text" placeholder="yyyy-mm-dd hh:mm" value="<?=$exam->starttime?>" name="start" class="datepicker validate[required]">
                <?php else:?>
                <?=$exam->starttime?>
		<?php endif;?>
        </div>

        <div class="st-line">
                <label for="end"><b>Exam End time:</b></label>
                <?php if($canUpdateExam && in_array("editable", $exam->flags)):?>
                <input type="text" placeholder="yyyy-mm-dd hh:mm" value="<?=$exam->endtime?>" name="end" class="datepicker validate[required]">
                <?php else:?>
                <?=$exam->endtime?>
		<?php endif;?>
        </div>

        <div class="st-line">
                <label for="grade"><strong>Grades:</strong></label>
                <?php if($canUpdateExam && in_array("editable", $exam->flags)):?>
                <textarea title="Input name:value pairs on separate lines defining the Grade levels for this examination. The first line must be on form name:0, denoting the failed grade." name="grade" class="grade validate[required]" placeholder="<?=str_pad("U:0", 65, " ").str_pad("G:15", 60, " ") . "VG:20"?>"><?=trim($exam->grades)?></textarea>
                <?php else:?>
                <?=nl2br(trim($exam->grades))?>
		<?php endif;?>
        </div>

        <div class="st-line">
		<?php if($canUpdateExam && in_array("editable", $exam->flags)):?>
                <input type="checkbox" value="1" title="Expose names and contact information for people involved in the creation and correction process in the result PDF seen by the student." <?=(($exam->details == 1 || $exam->details == 3) ? 'checked="checked"':'')?> name="details[]" >
                Expose responsible people
                <?php else:?>
                <?=$exam->details == 1 || $exam->details == 3 ? '&#10004; Expose responsible people' : ''?>
		<?php endif;?>
                <br />
                
		<?php if($canUpdateExam && in_array("editable", $exam->flags)):?>
                <input type="checkbox" value="2" title="Include statistics like avarage/mean values and score distribution compared to other students in the result PDF seen by the student." <?=(($exam->details == 2 || $exam->details == 3) ? 'checked="checked"':'')?> name="details[]" >
                Include other students statistics
                <?php else:?>
                <?=$exam->details == 2 || $exam->details == 3 ? '&#10004; Include other students statistics' : ''?>
		<?php endif;?>
                <br>
        </div>
        <?php if($canUpdateExam && in_array("editable", $exam->flags)):?>
	<div class="st-line">
	        <center><input class="save-exam-settings" type="button" value="Save exam settings"></center>
        </div>   
        <?php endif;?> 
	<script language="javascript">
	jQuery(".exam-settings-box").validationEngine();
        </script>
	</div>
</div>

<?php 
	// combine question json to initialize exam
	$combinedJson = array();
	foreach($exam->getQuestions() as $qData) {
		
		// add questId node
		$qJson = json_decode($qData->quest, true);
		$qJson['questId'] = $qData->id;
		$qJson['canUpdate'] = ($capabilities->hasCapability($qData, 'update') && in_array("editable", $exam->flags) ? 1:0);
		
		$combinedJson[$qData->name] = $qJson;
	}
	$combinedJson = (!count($combinedJson) ? "JSON.parse('{}')" : json_encode($combinedJson));
?>
<script language="javascript">
	mngr	= '<?=$exam->creator?>';
	user	= '<?=$this->user->getPrincipalName()?>';
	examId 	= <?=$exam->id?>;
	qsJson 	= <?=$combinedJson?>;
	qsCorrectorsJson = {};
	showAddQuestionView = <?=stristr($_SERVER['REQUEST_URI'], 'add-q') ? 'true':'false'?>;
</script>