<?php

use Phalcon\Tag;

/*
 * Copyright (C) 2014-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    index.phtml
// 
// Author:  Anders Lövgren (BMC-IT)
// Author:  Ahsan Shahzad (Medfarm DoIT)
// 

?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <?= Tag::getTitle(); ?>
        <meta http-equiv="content-type" content="text/html" charset="UTF-8" />	
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <?= Tag::javascriptInclude('js/jquery.min.js?ver=3.2.1'); ?>        
        <?= Tag::javascriptInclude('js/utils.js?rev=1'); ?>

        <script language="javascript">
                var baseURL = '<?= $this->url->get() ?>';
        </script>
    </head>

    <style>
        @media screen {
            body.high-contrast:not(img) {
                filter: invert(100%);
                background-color: black;
            }
            body.high-contrast .top-image img {
                filter: invert(0%);            
            }
            body.high-contrast img {
                filter: invert(100%);
            }
        }
    </style>

    <body class="fixed-header <?= $theme ?>">
        <?= $this->getContent(); ?>

        <!-- Content to show when AJAX request is in progress -->
        <div id="ajax-loader" style="display:none">
            <i class="fa fa-spinner fa-pulse fa-3x fa-fw margin-bottom"></i>
        </div>
    </body>

    <?php if ($this->polyfill->setContent()) : ?>
            <?= Tag::javascriptInclude($this->polyfill->getPath()); ?>
    <?php endif; ?>

    <script>
            document.addEventListener("DOMContentLoaded", function (event) {
                window.status = "content-loaded";       // PDF rendering
            });
    </script>

</html>
