<?php

use Phalcon\Tag;

// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    index.phtml
// 
// Author:  Ahsan Shahzad (Medfarm DoIT)
// Author:  Anders Lövgren (BMC-IT)
// 

?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <?= Tag::getTitle(); ?>
        <meta http-equiv="content-type" content="text/html" charset="UTF-8" />	
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <?= Tag::javascriptInclude('js/jquery.min.js'); ?>        
        <?= Tag::javascriptInclude('js/utils.js'); ?>

        <script language="javascript">
                var baseURL = '<?= $this->url->get() ?>';
        </script>
    </head>

    <body>
        <?= $this->getContent(); ?>

        <!-- Content to show when AJAX request is in progress -->
        <div id="ajax_loader" style="display:none">
            <?= Tag::image(array("img/ajax-loader.gif", "class" => "ajax-loader")); ?>
        </div>

    </body>

</html>