<?php

use Phalcon\Tag;

// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    index.phtml
// 
// Author:  Anders Lövgren (BMC-IT)
// Author:  Ahsan Shahzad (Medfarm DoIT)
// 

?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <?= Tag::getTitle(); ?>
        <meta http-equiv="content-type" content="text/html" charset="UTF-8" />	
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <?= Tag::javascriptInclude('js/jquery.min.js'); ?>        
        <?= Tag::javascriptInclude('js/utils.js?rev=1'); ?>

        <script language="javascript">
                var baseURL = '<?= $this->url->get() ?>';
        </script>
    </head>

    <style>
        @media screen {
            body.high-contrast:not(img) {
                filter: invert(100%);
                background-color: black;
            }
            body.high-contrast .top-image img {
                filter: invert(0%);            
            }
            body.high-contrast img {
                filter: invert(100%);
            }
        }
    </style>

    <body class="fixed-header <?= $theme ?>">
        <?= $this->getContent(); ?>

        <!-- Content to show when AJAX request is in progress -->
        <div id="ajax-loader" style="display:none">
            <i class="fa fa-spinner fa-pulse fa-3x fa-fw margin-bottom"></i>
        </div>
    </body>

    <?php if ($this->polyfill->setContent()) : ?>
            <?= Tag::javascriptInclude($this->polyfill->getPath()); ?>
    <?php endif; ?>

    <script>
            document.addEventListener("DOMContentLoaded", function (event) {
                window.status = "content-loaded";       // PDF rendering
            });
    </script>

</html>
