<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    missing.phtml
// Created: 2015-04-22 11:58:23
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<div id="no-student-msg" class="data-missing">
    The query for current import task did not return any data. Please check for example the group name or course code.
</div>

<script>
        $(document).ready(function () {
            $('#import-students-by-file').hide();
            $('#import-students-by-table').hide();
            $('#import-students-by-group').hide();
        });
</script>
