<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    missing.phtml
// Created: 2015-04-22 11:58:23
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<div id="no-student-msg" style=" ">
    <em>The query for current import task did not return any data. Please check for example the group name or course code.</em>
</div>

<script>
        $(document).ready(function () {
            $('#import-students-by-file').hide();
            $('#import-students-by-table').hide();
            $('#import-students-by-group').hide();
        });
</script>
