<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    monitor.phtml
// Created: 2016-05-25 14:26:46
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<style>
    div.mbox {
        padding: 12px;
        margin: 10px;
        margin-top: 50px;
        box-shadow: 1px 1px 6px #999999;
        border-radius: 10px 10px 10px 10px;
        background: #ffffff;
        max-width: 1024px;
    }
    div.monitor {
        display: none;
    }
    div.counter {
        margin: 10px;
        width: 400px;
        height: 280px;
        border: 2px solid #eeeeee;
        border-radius: 5px;
        display: inline-block;
    }
    div.counter .header {
        padding-left: 10px;
        padding-top: 6px;
    }
    span.title {
        font-weight: bold;
        font-size: 1.2em;
        margin-left: 10px;
    }
    button.counter {
        min-width: 100px;
    }
</style>

<div class="mbox">
    <h1>Performance Monitor</h1>
    <div id="monitor-wrapper">
        <div class="monitor-buttons">
            <button id="server" class="btn btn-primary">Server</button>
            <button id="system" class="btn btn-default">System</button>
            <button id="apache" class="btn btn-default">Web Server</button>
            <button id="mysql"  class="btn btn-default">Database</button>
        </div>
        <div class="monitor server"></div>
        <div class="monitor system"></div>
        <div class="monitor apache"></div>
        <div class="monitor mysql"></div>

    </div>
</div>

<script src="<?= $this->url->get('js/chart.js') ?>"></script>
<script src="<?= $this->url->get('js/views/diagnostics/performance/counters.js') ?>"></script>

<script>
        $(document).ready(function () {

            function activate(monitor, context) {
                $("div .monitor").hide();
                $("div ." + monitor).show();

                console.log(monitor);
                counters.close();
                counters.open(monitor, context);
                counters.start();
            }

            $("button").click(function () {
                var monitor = $(this).attr('id');
                var context = $("div ." + monitor);

                $("button").addClass("btn-default");
                $(this).toggleClass("btn-default");

                activate(monitor, context);
            });

            counters.setUrl(baseURL + 'utility/diagnostics/performance');
            counters.setLimit(20);
            counters.setInterval(5);

            activate("server", $("div .server"));
        })
</script>
