<?php
/*
 * Copyright (C) 2016-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    index.phtml
// Created: 2016-04-28 18:17:09
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<style>
    dt {
        float: left;
        clear: left;
        width: 60%;
        margin: 0;
        padding: 0 .5em 0 0;
        text-align: right;
    }
    dd {
        margin: 0;
        padding: 0;
    }
    dt:after {
        content: ":";
    }    
    td.name {
        font-weight: bold;
    }
    td.datetime {
        font-style: italic;
    }
    a dt {
        color: graytext;
    }
    div #statistics-wrapper {

    }
    div.statistics-charts {

    }
    div.statistics-summary {
        min-width: 300px;
        max-width: 400px;
    }
    button.reload {
        float: right;
    }
    div#statistics-data td {
        padding: 3px;
    }
</style>

<h1>
    Statistics - <span id="statistics-organization"></span>
</h1>

<button class="btn btn-primary reload" onclick="location.href = '<?= $this->url->get("utility/statistics") ?>'">Refresh</button>

<div class="container">
    <div id="statistics-wrapper" class="row">
        <div class="statistics-summary col-md-4">
            <div class="organization-roles">
                <dl id="organization-roles-list"></dl>
            </div>
            <div class="organization-exams">
                <dl id="organization-exams-list"></dl>
            </div>
            <div class="organization-users">
                <dl id="organization-users-list"></dl>
            </div>
        </div>
        <div class="statistics-charts col-md-8">
            <div id="organization-pie-legend" class="pie-legend"></div>
            <canvas id="organization-pie-chart" width="400" height="300"></canvas>
        </div>
    </div>
</div>

<div id="statistics-data"></div>

<script src="<?= $this->url->get('js/chart.js') ?>"></script>
<script src="<?= $this->url->get('js/views/statistics/chart.js?rev=1') ?>"></script>
<script src="<?= $this->url->get('js/views/statistics/roles.js?rev=1') ?>"></script>
