<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    index.phtml
// Created: 2016-04-28 18:17:09
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<style>
    dt {
        float: left;
        clear: left;
        width: 60%;
        margin: 0;
        padding: 0 .5em 0 0;
        text-align: right;
    }
    dd {
        margin: 0;
        padding: 0;
    }
    dt:after {
        content: ":";
    }    
    td.name {
        font-weight: bold;
    }
    td.datetime {
        font-style: italic;
    }
    a dt {
        color: graytext;
    }
    div #statistics-wrapper {
        
    }
    div.statistics-charts {
        
    }
    div.statistics-summary {
        min-width: 300px;
        max-width: 400px;
    }
    button.reload {
            float: right;
    }
    div#statistics-data td {
        padding: 3px;
    }
</style>

<h1>
    Statistics - <span id="statistics-organization"></span>
</h1>

<button class="btn btn-primary reload" onclick="location.href='<?= $this->url->get("utility/statistics") ?>'">Refresh</button>

<div class="container">
    <div id="statistics-wrapper" class="row">
        <div class="statistics-summary col-md-4">
            <div class="organization-roles">
                <dl id="organization-roles-list"></dl>
            </div>
            <div class="organization-exams">
                <dl id="organization-exams-list"></dl>
            </div>
            <div class="organization-users">
                <dl id="organization-users-list"></dl>
            </div>
        </div>
        <div class="statistics-charts col-md-8">
            <div id="organization-pie-legend" class="pie-legend"></div>
            <canvas id="organization-pie-chart" width="400" height="300"></canvas>
        </div>
    </div>
</div>

<div id="statistics-data"></div>

<script src="<?= $this->url->get('js/chart.js') ?>"></script>
<script src="<?= $this->url->get('js/views/statistics/chart.js?rev=1') ?>"></script>
<script src="<?= $this->url->get('js/views/statistics/roles.js?rev=1') ?>"></script>
