<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    show404.phtml
// Created: 2015-02-24 03:24:47
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<?php $this->partial("error/partial/style"); ?>
<?php $this->partial("error/partial/script"); ?>

<h1 class="header">
    <i class="fa fa-exclamation-triangle" aria-hidden="true" style="color: orange"></i>
    Page not found:
</h1>

<p class="message">
    <?= $error->getMessage(); ?>
</p>

<div class="info">
    <p>The requested page seems to be missing. If you ended up here by following a link, please click on the <u>report button</u> to send an email to the system manager.</p>
    <button class="btn btn-primary" value="back"   onclick="window.history.back()">Back</button>
    <button class="btn btn-warning" value="report" onclick="return report_exception()">Report</button>
    <span id="notice" style="display: block"></span>
</div>
