<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    show404.phtml
// Created: 2015-02-24 03:24:47
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<style>
    h1.error {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }
</style>

<div style="<?= $style ?>">
    <h1 class="error">Page not found:</h1>
    <p><?= $exception->getMessage(); ?>
</div>
