<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    show503.phtml
// Created: 2015-02-24 03:25:04
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<?php $this->partial("error/partial/style"); ?>
<?php $this->partial("error/partial/script"); ?>

<h1 class="error">Service Unavailable:</h1>
<p class="error"><?= $error->getMessage(); ?></p>
<div class="info">
    <p>The web server is currently unable to handle the HTTP request due to a temporary overloading or maintenance of the server.</p>
    <p>You can click on the <u>retry button</u> below to send the request again. Click on the <u>report button</u> to send an email to the system manager.</p>
    <button class="btn btn-primary" value="retry"  onclick="document.location.href = ''">Retry</button>
    <button class="btn btn-warning" value="report" onclick="return report_exception()">Report</button>
    <span id="notice" style="display: block"></span>
</div>
