<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    show503.phtml
// Created: 2015-02-24 03:25:04
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<style>
    h1.error {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }

</style>

<br/>
<h1 class="error">Internal system error:</h1>
<p><?= $exception->getMessage(); ?>
