<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    showError.phtml
// Created: 2015-03-19 10:49:03
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<?php $this->partial("error/partial/style"); ?>
<?php $this->partial("error/partial/script"); ?>

<h1 class="error"><?= $error->getString(); ?></h1>
<p class="error"><?= $error->getMessage(); ?></p>

<div class="info">
    <p>There was an problem processing the last request. The error message might give you an clue on what is wrong, but many kind of errors are permanent and can't be resolved without further assistance from the system manager.</p>
    <p>You can click on the <u>retry button</u> below to try the request again. Click on the <u>report button</u> to send an email to the system manager.</p>
    <button class="btn btn-primary" value="retry"  onclick="document.location.href = ''">Retry</button>
    <button class="btn btn-warning" value="report" onclick="return report_exception()">Report</button>
    <span id="notice" style="display: block"></span>
</div>
