<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    showError.phtml
// Created: 2015-03-19 10:49:03
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<?php $this->partial("error/partial/style"); ?>
<?php $this->partial("error/partial/script"); ?>

<h1 class="header">
    <i class="fa fa-exclamation-circle" aria-hidden="true" style="color: red"></i>
    <?= $error->getString(); ?>
</h1>

<p class="message">
    <?= $error->getMessage(); ?>
</p>

<div class="info">
    <p>There was an problem processing the last request. The error message might give you an clue on what is wrong, but many kind of errors are permanent and can't be resolved without further assistance from the system manager.</p>
    <p>You can click on the <u>retry button</u> below to try the request again. Click on the <u>report button</u> to send an email to the system manager.</p>
    <button class="btn btn-primary" value="retry"  onclick="document.location.href = ''">Retry</button>
    <button class="btn btn-warning" value="report" onclick="return report_exception()">Report</button>
    <span id="notice" style="display: block"></span>
</div>
