<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    show503.phtml
// Created: 2015-02-24 03:25:04
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<?php $this->partial("error/partial/style"); ?>
<?php $this->partial("error/partial/script"); ?>

<h1 class="header">
    <i class="fa fa-exclamation-circle" aria-hidden="true" style="color: red"></i>
    Service temporary unavailable:
</h1>

<p class="message">
    <?= $error->getMessage(); ?>
</p>

<div class="info">
    <p>The web server is currently unable to handle the HTTP request due to a temporary overloading or maintenance of the server.</p>
    <p>You can click on the <u>retry button</u> below to send the request again. Click on the <u>report button</u> to send an email to the system manager.</p>
    <button class="btn btn-primary" value="retry"  onclick="document.location.href = ''">Retry</button>
    <button class="btn btn-warning" value="report" onclick="return report_exception()">Report</button>
    <span id="notice" style="display: block"></span>
</div>
