<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    showError.phtml
// Created: 2015-03-19 10:49:03
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<style>
    h1.error {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }
</style>

<div style="<?= $style ?>">
    <h1 class="error"><?= $error->getString(); ?></h1>
    <p><?= $error->getMessage(); ?>
</div>
