<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    show500.phtml
// Created: 2016-12-12 00:12:27
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<?php $this->partial("error/partial/style"); ?>
<?php $this->partial("error/partial/script"); ?>

<div class="oe-error">
    <h1 class="header">
        <i class="fa fa-exclamation-circle" aria-hidden="true" style="color: red"></i>
        Internal system error:
    </h1>

    <p class="message">
        <?= $error->getMessage(); ?>
    </p>

    <div class="info">
        <p>There was an error processing the request. It might be caused by a miss configuration or an external service no longer working.</p>
        <p>This kind of error is usually permanent and will persist until been taking cared of by someone. Please click on the <u>report button</u> to send an email to the system manager.</p>
        <button class="btn btn-warning" value="report" onclick="return report_exception()">Report</button>
        <span id="notice" style="display: block"></span>
    </div>
</div>
