<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    answers.phtml
// 
// Author:  Ahsan Shahzad (MedfarmDoIT)
//          Anders Lövgren (BMC-IT)
// 

$decoded = $exam->decoded;

if (strtotime($exam->endtime) < time()) {
        $exam->show_save = true;
} else {
        $exam->show_save = false;
}

?>

<?= Phalcon\Tag::stylesheetLink("css/pdf-rendering.css"); ?>

<style>
    div[correction="completed"] > div.q-body,
    div[correction="finalized"] > div.q-body {
        border-left: 10px solid white;
        padding-left: 10px;
    }
    div[correction="partial"] > div.q-body {
        border-left: 10px solid orange;
        padding-left: 10px;
    }
    div[correction="waiting"] > div.q-body,
    div[correction=""] > div.q-body {
        border-left: 10px solid green;
        padding-left: 10px;
    }

    div.correction-section-box {
        border-radius: 5px; 
        margin-left: 10px; 
        margin-top: 10px; 
        box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.2), 0 5px 20px 0 rgba(0, 0, 0, 0.2);    
        overflow: hidden;
        background-color: ghostwhite;
    }
    div.correction-section-head {
        background-color: lavender;
        padding: 10px;
    }

    div.student-answer-box {
        background-color: white;
        border: 1px solid #e0e0e0;
        border-radius: 5px;
        margin-top: 10px;
        padding: 15px;
        margin-bottom: 20px;
    }

    #mainview {
        background-color: rgba(0, 0, 0, 0.3);
        border-radius: 5px;
        width: 100%;        
    }
    #mainview h3 {
        color: white;
    }

    input.q-points:required {
        background-color: #ffffff;
    }
    input.q-points:required:invalid {
        background-color: #feff99;
    }    
    .savable {
        display: <?= $exam->show_save ? '' : 'none' ?>
    }
    @media print {
        .no-print {
            display: none;
        }
        input.q-points {
            padding: 10px;
        }
        body {
            font-size: smaller;
        }
    }
    @media screen {
        .on-print {
            display: none;
        }
    }
</style>

<h2 class="on-print">
    <?= Phalcon\Tag::image(array($this->config->brand->logo->file, "height" => "55px", "style" => "padding-right:20px")); ?><?= $exam->name ?>
</h2>

<div id="mainview">
    <h3><?= $decoded ? "Answer correction" : "Correct the answers" ?> for <?= $heading ?>.</h3>
    <?php foreach ($questions as $question): ?>
            <?php
            $correctAns = array();
            $qCorrectorList = array();

            foreach ($question->getCorrectors() as $qCorrector) {
                    $qCorrectorList[$qCorrector->id] = $qCorrector->user;
            }

            foreach ($answers as $answer) {
                    if ($answer->question_id == $question->id) {
                            $result = $answer->result;
                            break;
                    }
            }

            ?>

            <?php if ($loadBy == 'question'): ?>
                    <div class="q-wrapper correction-section-box">
                <?php else: ?>
                        <div class="q-wrapper correction-section-box" correction="<?= $result->correction ?>">
                    <?php endif; ?>

                    <?php if (!$decoded && $loadBy != 'question'): ?>
                            <?= Phalcon\Tag::image(array("img/not-corrected.gif", "style" => "position: absolute; z-index: 1; right: 15px; width: 5%; width: 60px;", "id" => $question->id . "-corrected", "class" => "not-corrected")); ?>
                    <?php endif; ?>
                    <div class="q-heading correction-section-head">
                        <span style="color:#333333; font-weight:normal"><i class="fa fa-pencil-square-o"></i> Question no. <?= $question->slot ?></span>
                    </div>

                    <?php
                    $questParts = json_decode($question->quest, true);
                    if (isset($questParts['highlight-q'])) :
                            unset($questParts['highlight-q']);
                    endif;

                    ?>
                    <div class="q-body" style="padding:10px; <?= (!in_array($this->user->getPrincipalName(), $qCorrectorList) ? "opacity:0.6" : "") ?>">
                        <?php
                        $qPartCounter = 1;
                        $perOptPoints = array();

                        ?>
                        <?php foreach ($questParts as $qPartTitle => $qPart): ?>
                                <div class="q-part-wrapper" style=" <?= $loadBy != 'question' ? '1px dashed #dedede' : 'none' ?>">

                                    <?php if (count($questParts) > 1): ?>
                                            <div style="q-part-heading">
                                                <span style="font-weight: bold; color:#4285f4">Part <?= $qPartTitle ?>:</span>
                                            </div>
                                    <?php endif; ?>

                                    <div class="q-part-body" >

                                        <div class="q-part-txt">
                                            <?= $qPart['q_text'] ?>
                                        </div>

                                        <div class="q-part-resources">
                                            <?php
                                            foreach ($qPart['resources'] as $resTitle => $resUrl) {
                                                    $type = basename(dirname($resUrl));
                                                    $path = $this->config->application->mediaDir . $type . DIRECTORY_SEPARATOR . basename(urldecode($resUrl));
                                                    $href = $this->url->get($resUrl);
                                                    $name = $resTitle;

                                                    // 
                                                    // Use resource viewer:
                                                    // 
                                                    $this->partial('partials/resource-file-viewer', array(
                                                            'type' => $type, 'path' => $path,
                                                            'href' => $href, 'name' => $name,
                                                            'url'  => $this->url
                                                    ));
                                            }

                                            ?>
                                        </div>

                                        <?php if ($qPart['ans_area']['type'] == 'choicebox'): ?>
                                                <div>
                                                    <?php if (count($qPart['ans_area']['data'])): ?>
                                                            <ul style="margin: 5px 0 0 30px">
                                                                <?php foreach ($qPart['ans_area']['data'] as $opt => $correct): ?>
                                                                        <?php if ($correct == '1'): ?>
                                                                                <li style="color:green"><?= $opt ?></li>
                                                                                <?php $correctAns[$question->id][$qPartTitle][] = $opt; ?>
                                                                        <?php else: ?>
                                                                                <li><?= $opt ?></li>        
                                                                        <?php endif; ?>
                                                                <?php endforeach; ?>
                                                            </ul>
                                                    <?php endif; ?>
                                                </div>

                                                <?php
                                                if (is_array($correctAns[$question->id][$qPartTitle]) && count($correctAns[$question->id][$qPartTitle])):
                                                        $perOptPoints[$question->id][$qPartTitle] = ($qPart['q_points'] / count($correctAns[$question->id][$qPartTitle]));
                                                endif;

                                                ?>

                                        <?php endif; ?>

                                        <?php
                                        if ($loadBy != 'question'):

                                                // filter answer for this question from list of answers
                                                $qSpecificAns = array();
                                                foreach ($answers as $answer) {
                                                        if ($answer->question_id == $question->id) {
                                                                $qSpecificAns[] = $answer;
                                                        }
                                                }

                                                ?>

                                                <?php
                                                foreach ($qSpecificAns as $qSpecAns):
                                                        $result = $qSpecAns->getResult();
                                                        $scoreData = (is_object($result) && $result->count() ? json_decode($result->score, true) : array());
                                                        if ($decoded || (count($scoreData) && $result->correction != 'partial')):

                                                                ?>
                                                                <script>
                                                                        $("#<?= $question->id ?>-corrected").hide();
                                                                        $("#<?= $question->id ?>-corrected").parent().find('.st-ans-ul').css('background-color', '#F9F9F9');
                                                                </script>
                                                        <?php endif; ?>

                                                        <div class="student-answer-box">
                                                            <div class="q-part-txt-student-ans">
                                                                <?php $ansData = json_decode($qSpecAns->answer, true); ?>
                                                                <span style="color:#990000;"><i class="fa fa-arrow-circle-right"></i></span> 
                                                                <span style="color:#000; font-weight:bold">Student's answer</span>
                                                                <?php
                                                                if (isset($correctAns[$question->id][$qPartTitle])) {
                                                                        $correctAnsPart = $correctAns[$question->id][$qPartTitle];
                                                                } else {
                                                                        $correctAnsPart = array();
                                                                }

                                                                ?>
                                                                <?php $totalCorrect = 0; ?>
                                                                <?php if (count($ansData[$qPartTitle]['ans'])): ?>
                                                                        <ul class="st-ans-ul" style="margin: 5px 0 0 30px; list-style:none; background-color:#F5FAF5; padding:5px; border-left:5px solid #f0f0f0; max-width:95%">
                                                                            <?php foreach ($ansData[$qPartTitle]['ans'] as $stAns): ?>
                                                                                    <?php if ($qPart['ans_area']['type'] == 'choicebox'): ?>
                                                                                            <li style="color:<?= (in_array($stAns, $correctAnsPart) ? 'green' : 'red') ?>">
                                                                                                <i class="fa fa-<?= (in_array($stAns, $correctAnsPart) ? 'check' : 'times') ?>"></i> 
                                                                                                <?= $stAns ?>
                                                                                                <?php in_array($stAns, $correctAnsPart) ? ++$totalCorrect : --$totalCorrect; ?>
                                                                                            </li>
                                                                                    <?php elseif ($qPart['ans_area']['type'] == 'canvas'): ?>
                                                                                            <li><img src="<?= $stAns['canvasUrl'] ?>" max-width="50%" /></li>
                                                                                    <?php else: ?>
                                                                                            <li><?= $stAns ?></li>
                                                                                    <?php endif; ?>
                                                                                    <?php if (empty($ansData[$qPartTitle]['ans'][0])): ?>
                                                                                            <li><i>Student did not answer this question.</i></li>
                                                                                    <?php endif; ?>
                                                                            <?php endforeach; ?>
                                                                            <?php
                                                                            if ($totalCorrect < 0) {
                                                                                    $totalCorrect = 0;
                                                                            }

                                                                            ?>
                                                                        </ul>
                                                                <?php else: ?>
                                                                        <span style="background-color:#FEFF99"><i>Student did not answer this question part.</i></span>
                                                                <?php endif; ?>
                                                            </div>
                                                            <?php if ($qPart['ans_area']['type'] == 'choicebox' && count($correctAnsPart) && $totalCorrect && $totalCorrect != count($correctAnsPart)) : ?>
                                                                    <div style="color:orange; margin-left:35px"><i class="fa fa-warning"></i>  Student's answer is partially correct </div>
                                                            <?php endif; ?>

                                                            <div class="q-part-student-score savable" style="padding-left: 35px; margin-top: 10px; display: <?= $qPart['q_points'] == 0 ? 'none' : '' ?>">
                                                                <i class="fa fa-certificate" style="color:#D84B4B"></i>
                                                                <span style="color:#000;">
                                                                    Points:
                                                                    <span style="margin-left: 15px">
                                                                        <?php
                                                                        // 
                                                                        // Fill in score if max is zero on this question part.
                                                                        // 
                                                                        if (isset($qPart['q_points']) && $qPart['q_points'] == 0 && !isset($scoreData[$qPartTitle])) {
                                                                                $scoreData[$qPartTitle] = 0;
                                                                                printf("<script>resyncableResults.push('%d')</script>\n", $result->answer_id);
                                                                        }

                                                                        // 
                                                                        // Define answer result score. Make sure to watch out for floatval('') == 0 ...
                                                                        // 
                                                                        if (isset($scoreData[$qPartTitle])) {
                                                                                $score = floatval($scoreData[$qPartTitle]);
                                                                        } elseif ($qPart['ans_area']['type'] == 'choicebox') {
                                                                                $score = round($perOptPoints[$question->id][$qPartTitle] * $totalCorrect, 2);
                                                                        } else {
                                                                                $score = '';
                                                                        }

                                                                        ?>
                                                                        <?php if (!$decoded && in_array($this->user->getPrincipalName(), $qCorrectorList)): ?>
                                                                                <input type="text" class="form-control q-points changeable" style="max-width: 80px" ans-id="<?= $qSpecAns->id ?>" res-id="<?= count($scoreData) ? $result->id : 0 ?>" q-part="<?= $qPartTitle ?>" value="<?= $score ?>" max-pt="<?= floatval($qPart['q_points']) ?>" required="required">								
                                                                        <?php else: ?>
                                                                                <?= floatval($scoreData[$qPartTitle]) ?>
                                                                        <?php endif; ?>	
                                                                    </span>
                                                                    <span style="color: #4285f4; float: right; margin-right: 10px">[Max: <?= floatval($qPart['q_points']) ?>]</span>
                                                                </span>
                                                            </div>
                                                        </div>

                                                        <?php if (count($qSpecificAns)): ?>
                                                                <?php if (!$decoded && in_array($this->user->getPrincipalName(), $qCorrectorList)): ?>
                                                                        <?php if (count($questParts) == $qPartCounter): ?>
                                                                                <div class="savable" style="padding-bottom: 10px; padding-left:35px">
                                                                                    <i class="fa fa-comments"></i>
                                                                                    Comments:<br />
                                                                                    <textarea class="form-control changeable no-print" placeholder="Add your comments here for the student" style="margin-left: 15px; width:30%" ans-id="<?= $qSpecAns->id ?>"><?= $result->comment ?></textarea>
                                                                                </div>
                                                                                <div class="savable" style="padding-bottom: 10px; padding-left: 45px;">
                                                                                    <input class="btn btn-success save-result no-print" type="button" ans-id="<?= $qSpecAns->id ?>" value="Save result for this question" corrector-id="<?= array_search($this->user->getPrincipalName(), $qCorrectorList) ?>">
                                                                                </div>
                                                                        <?php endif; ?>
                                                                <?php else: ?>
                                                                        <?php if (!empty($result->comment)): ?>                                                
                                                                                <div style="padding-top:8px">
                                                                                    <div>
                                                                                        <strong>Corrector's comments:</strong>
                                                                                    </div>
                                                                                    <div>
                                                                                        <?= $result->comment ?>
                                                                                    </div>
                                                                                </div>
                                                                        <?php endif; ?>
                                                                <?php endif; ?>

                                                                <div style="clear:both"></div>                                                
                                                        <?php endif; ?>         

                                                <?php endforeach; ?>
                                                <?php if (!count($qSpecificAns)): ?>
                                                        <span style="background-color:#FEFF99"><i>Student did not answer this question part.</i></span>
                                                        <script>$("#<?= $question->id ?>-corrected").hide();</script>
                                                <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php $qPartCounter++; ?>
                        <?php endforeach; ?>        

                        <?php if ($loadBy == 'question'): ?>
                                <div class="st-ans-box">
                                    <?php foreach ($answers as $answer): ?>
                                            <?php $result = $answer->getResult(); ?>
                                            <?php $scoreData = (is_object($result) && $result->count() ? json_decode($result->score, true) : array()); ?>
                                            <div class="correction-section-box" style="margin-top: 15px" correction="<?= $result->correction ?>">
                                                <?php if (!$decoded && (count($scoreData) == 0 || !in_array($result->correction, array('completed', 'finalized')))): ?>
                                                        <?= Phalcon\Tag::image(array("img/not-corrected.gif", "style" => "position: absolute; right: 25px; width: 5%; min-width: 60px;", "class" => "not-corrected")); ?>
                                                <?php endif; ?>
                                                <?php $student = $answer->student; ?>
                                                <div class="st-ans-box-heading correction-section-head">
                                                    <span style="color:#514E4E; font-weight:normal">
                                                        <i class="fa fa-user"></i>
                                                        <?php if ($exam->show_code): ?>
                                                                Students answer for this question (<?= $student->code ?>)
                                                        <?php else: ?>
                                                                Students answer for this question (<?= $student->id ?>)
                                                        <?php endif; ?>
                                                    </span>
                                                </div>
                                                <?php
                                                $ansData = json_decode($answer->answer, true);
                                                if (!isset($ansData)) {
                                                        $ansData = array();
                                                }
                                                if (isset($ansData['highlight-q'])) {
                                                        unset($ansData['highlight-q']);
                                                }

                                                ?>

                                                <div class="st-ans-box-body q-body" style="padding-top:15px; <?= (!in_array($this->user->getPrincipalName(), $qCorrectorList) ? "opacity:0.6;" : "") ?>">
                                                    <div class="st-ans-parts-wrapper" style="padding-bottom:15px;">
                                                        <?php $qPartCounter = 1; ?>
                                                        <?php foreach ($ansData as $qPartTitle => $qPart): ?>
                                                                <div class="st-ans-part" style="padding-bottom:5px">
                                                                    <?php if (count($ansData) > 1): ?>
                                                                            <div class="st-ans-part-title" style="padding-bottom:5px">
                                                                                <span style="color:#4285f4">Part <?= $qPartTitle ?>:</span>
                                                                            </div>
                                                                    <?php endif; ?>
                                                                    <div class="st-ans-part-content">
                                                                        <ul class="st-ans-ul" style="margin: 5px 0 0 30px; list-style:none; background-color:<?= (!$decoded && !count($scoreData)) ? '#F5FAF5' : '#F9F9F9' ?>; padding:5px; border-left:5px solid #f0f0f0; max-width:95%">
                                                                            <?php $totalCorrect = 0; ?>
                                                                            <?php
                                                                            if (isset($correctAns[$question->id][$qPartTitle])) {
                                                                                    $correctAnsPart = $correctAns[$question->id][$qPartTitle];
                                                                            } else {
                                                                                    $correctAnsPart = array();
                                                                            }

                                                                            ?>
                                                                            <?php foreach ($ansData[$qPartTitle]['ans'] as $stAns): ?>
                                                                                    <?php if ($qPart['type'] == 'choicebox'): ?>
                                                                                            <li style="color:<?= (in_array($stAns, $correctAnsPart) ? 'green' : 'red') ?>">
                                                                                                <i class="fa fa-<?= (in_array($stAns, $correctAnsPart) ? 'check' : 'times') ?>"></i> 
                                                                                                <?= $stAns ?>
                                                                                                <?php in_array($stAns, $correctAnsPart) ? ++$totalCorrect : --$totalCorrect; ?>
                                                                                            </li>
                                                                                    <?php elseif ($qPart['type'] == 'canvas'): ?>
                                                                                            <li><img src="<?= $stAns['canvasUrl'] ?>" max-width="50%" /></li>
                                                                                    <?php else: ?>
                                                                                            <li><?= $stAns ?></li>
                                                                                    <?php endif; ?>

                                                                                    <?php if (empty($ansData[$qPartTitle]['ans'][0])): ?>
                                                                                            <li><i>Student did not answer this question.</i></li>
                                                                                    <?php endif; ?>
                                                                            <?php endforeach; ?>
                                                                            <?php
                                                                            if ($totalCorrect < 0) {
                                                                                    $totalCorrect = 0;
                                                                            }

                                                                            ?>

                                                                            <?php if ($qPart['type'] == 'choicebox' && $totalCorrect && $totalCorrect != count($correctAnsPart)) : ?>
                                                                                    <li style="color:orange"><i class="fa fa-warning"></i> Student's answer is partially correct </li>
                                                                            <?php endif; ?>
                                                                        </ul>
                                                                    </div>

                                                                    <div class="q-part-student-score savable" style="padding-top: 10px; padding-left: 35px; margin-bottom: 10px; display: <?= $questParts[$qPartTitle]['q_points'] == 0 ? 'none' : '' ?>">
                                                                        <i class="fa fa-certificate" style="color:#D84B4B"></i>
                                                                        <span style="color:#000;">
                                                                            Points:
                                                                            <?php
                                                                            // 
                                                                            // Fill in score if max is zero on this question part.
                                                                            // 
                                                                            if (isset($qPart['q_points']) && $qPart['q_points'] == 0 && !isset($scoreData[$qPartTitle])) {
                                                                                    $scoreData[$qPartTitle] = 0;
                                                                                    printf("<script>resyncableResults.push('%d')</script>\n", $answer->id);
                                                                            }

                                                                            ?>

                                                                            <?php if (!$decoded && in_array($this->user->getPrincipalName(), $qCorrectorList)): ?>
                                                                                    <input type="text" class="form-control q-points changeable" style="max-width: 80px" ans-id="<?= $answer->id ?>" res-id="<?= count($scoreData) ? $result->id : 0 ?>" q-part="<?= $qPartTitle ?>" value="<?= isset($scoreData[$qPartTitle]) ? $scoreData[$qPartTitle] : ($qPart['type'] == 'choicebox' ? round($perOptPoints[$question->id][$qPartTitle] * $totalCorrect, 2) : '') ?>"  max-pt="<?= floatval($questParts[$qPartTitle]['q_points']) ?>" required="required">
                                                                            <?php else: ?>
                                                                                    <?= floatval($scoreData[$qPartTitle]) ?>
                                                                            <?php endif; ?>
                                                                            <span style="color: #4285f4; float: right; margin-right: 10px">[Max: <?= $questParts[$qPartTitle]['q_points'] ?>]</span>
                                                                        </span>
                                                                    </div>

                                                                    <?php if (!$decoded && in_array($this->user->getPrincipalName(), $qCorrectorList)): ?>
                                                                            <?php if (count($ansData) == $qPartCounter): ?>
                                                                                    <div class="savable" style="padding-top: 10px; padding-left:35px">
                                                                                        <i class="fa fa-comments"></i>
                                                                                        Comments:<br />
                                                                                        <textarea class="form-control changeable no-print" placeholder="Add your comments here for the student" style="margin-left: 15px; width:30%" ans-id="<?= $answer->id ?>"><?= $result->comment ?></textarea>
                                                                                    </div>

                                                                                    <div class="savable no-print" style="padding-top: 10px; padding-left: 45px;">
                                                                                        <input class="btn btn-success save-result no-print" type="button" ans-id="<?= $answer->id ?>" value="Save this result" corrector-id="<?= array_search($this->user->getPrincipalName(), $qCorrectorList) ?>">
                                                                                    </div>
                                                                            <?php endif; ?>
                                                                    <?php else: ?>
                                                                            <?php if (!empty($result->comment)): ?>
                                                                                    <div>
                                                                                        <div>
                                                                                            <strong>Corrector's comments:</strong>
                                                                                        </div>
                                                                                        <div>
                                                                                            <?= $result->comment ?>
                                                                                        </div>
                                                                                    </div>
                                                                            <?php endif; ?>
                                                                    <?php endif; ?>
                                                                    <div style="clear:both"></div>                                                

                                                                </div>
                                                                <?php $qPartCounter++; ?>
                                                        <?php endforeach; ?>

                                                        <?php if (!count($ansData)): ?>
                                                                <span style="background-color:#FEFF99"><i>Student did not answer this question part.</i></span>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            </div>
                                    <?php endforeach; ?>
                                </div>
                        <?php endif; ?>
                    </div>
                </div>
        <?php endforeach; ?>
        <br />
    </div>
</div>
<?php if ($decoded == false) : ?>
        <div class="no-print" style="position: fixed; top: 55px; right: 70px; padding: 10px; background-color: whitesmoke; border-radius: 5px; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.2), 0 5px 20px 0 rgba(0, 0, 0, 0.2); z-index: 2">
            <div>
                <?php
                printf("<a href=\"#\" style=\"float: right; padding: 5px\" onclick=\"return render_pdf_document('%s','%s')\" title=\"Download current view as PDF document\"><i class=\"fa fa-file-pdf-o fa-2x\" aria-hidden=\"true\"></i></a>\n", urlencode($this->request->get("_url")), $this->url->get("utility/render/pdf"));
                printf("<a href=\"#\" style=\"float: right; padding: 5px\" onclick=\"return online_url_document('%s')\" title=\"View online in print friendly format\"><i class=\"fa fa-print fa-2x\" aria-hidden=\"true\"></i></a>\n", $this->url->get($this->request->get('_url')));

                ?>
            </div>
            <hr>
            <input type="button" class="btn btn-success btn-lg save-all-result savable" corrector-id="<?= array_search($this->user->getPrincipalName(), $qCorrectorList) ?>" value="Save all results »">
            <div style="padding-left: 10px; padding-top: 5px">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" class="hide-completed">
                        Hide fully corrected answers
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" class="hide-resources">
                        Hide media and resource files
                    </label>
                </div>
            </div>
        </div>
<?php endif; ?>

<form id="download-pdf" action="" style="display: none">
    <input id="download-url" type="hidden" name="url" value="">
    <input type="submit">
</form>

<script>
        // 
        // Trigger download of PDF document:
        // 
        function render_pdf_document(url, render) {
            window.location.href = render + '?url=' + url;
            return false;
        }

        // 
        // Trigger print of URL:
        // 
        function online_url_document(url) {
            window.location.href = url + "#print";
            return false;
        }

        // 
        // Popup print dialog if hash-bang is set:
        // 
        document.addEventListener("DOMContentLoaded", function () {
            if (window.location.hash && window.location.hash === '#print') {
                window.print();
            }
        });

</script>
