
<?php 
$overallQuestScore = array();
$totalExamScore = $totalStudentScore = 0;

$students  = $exam->getStudents();

$grades = preg_split('/[\r\n]+/', $exam->grades);
$examGrades = array();
foreach ($grades as $grade) :
	$t = explode(":", $grade);
	$examGrades[$t[0]] =  $t[1];
	$avgGrades[$t[0]] = 0;
endforeach;
arsort($examGrades);

?>

<!-- Main area -->
<div id="container" class="left_menu_space" style="width:100%">
        <div id="centerColWide" style="width:95%">
                <div id="mainview">
                        <h3>Answer correction</h3>
                        <p>This table shows all answers from students to questions for the examination <strong>"<?=$exam->name?>"</strong>. </p>
                        <p>Correct answers by student (rows), by question (column) or individual (by index). You can only correct answers for questions published by yourself or those you have been assigned the role as corrector of.</p>
			<div style="margin:25px">
                                <table class="tablesorter">
                                        <tbody>
                                                <tr>
                                                        <th>Code </th>
                                                        <?php foreach($questions as $question):?>
                                                                <th style="width:55px; text-align:center; ">
                                                                  <div style="text-align: center">
                                                                  	<a class="fb fancybox.ajax" href="<?=$this->url->get('exam/'.$exam->id.'/correction/question/'.$question->id)?>">Q<?=$question->name?></a>
                                                                  </div>
                                                                  <div style="font-weight:normal; font-size:10px; font-style:italic">Max: <?=sprintf("%1.1f", $question->score)?></div>
                                                                </th>
                                                                <?php $totalExamScore += $question->score;?>
                                                        <?php endforeach;?>
                                                        <th>Percent </th>
                                                        <th>Grade </th>
                                                </tr>
						<?php foreach($students as $student):?>
                                                <tr>
                                                        <td style="border-bottom:1px #dedede solid; border-right:5px solid #DDDDDD"><a class="fb fancybox.ajax" href="<?=$this->url->get('exam/'.$exam->id.'/correction/student/'.$student->id)?>"><?=$student->code?></a></td>
							<?php $totalStudentScore = 0;?>
							<?php foreach($questions as $question):
                                                        
                                                                //$totalPoints += $question->score;
                                                                $result = NULL;
                                                                $qScore = 0;
                                                                $answer = $question->getAnswers("student_id = '".$student->id."'");
                                                                if($answerd = $answer->count()) :
                                                                
                                                                        $result = $answer->getFirst()->getResult();
                                                                        if(is_object($result) && $result->count()) :
                                                                        
                                                                                foreach(json_decode($result->score, true) as $part => $score):
                                                                                        $qScore+=$score;
                                                                                endforeach;
                                                                                
                                                                                $totalStudentScore+=$qScore;
                                                                                $overallQuestScore[$question->id][] = $qScore;
                                                                        endif;	
                                                                        
                                                                endif;
                                                                ?>
                                                                <?php //$ansResult = count($answers) ? $answers[0]->getResult() : array()?>
                                                                
                                                                        <?php /*foreach($answers as $ans):?>
                                                                                <?php $result = $ans->getResult()?>
                                                                                        <?php $pointsGained += $result->score;?>
                                                                        <?php endforeach; */?>
                                                                        
                                                                <?php 
                                                                // find color code
                                                                $cLink = true;
                                                                if(!$answerd) :
                                                                        $cc = 'na';
                                                                        $cLink = false;
                                                                elseif(is_object($result) && $result->count())  :
                                                                        $cc = 'ac';
                                                                else :
                                                                        $cc = 'nc';
                                                                endif;
                                                                ?>
                                                                <td class="cc <?=$cc?>">
                                                                        <?php if($cLink):?>
                                                                        <a class="fb fancybox.ajax" 
                                                                        href="<?=$this->url->get('exam/'.$exam->id.'/correction/answer/'.$answer->getFirst()->id)?>">
                                                                                <?=(is_object($result) && $result->count())?sprintf("%1.1f", $qScore):'<i class="fa fa-check-square-o"></i>'?>
                                                                        </a>
                                                                        
                                                                        <?php else:?>
                                                                        <i class="fa fa-ban"></i>
                                                                        <?php endif;?>
                                                                </td>

                                                        <?php endforeach;?>
                                                        <td style="border-bottom:1px #dedede solid; background-color:#FFFFCC; text-align:center">
								<?=sprintf("%1.1f", ($totalStudentScore/$totalExamScore)*100)?>%
                                                                <?php
								if($answerd):
									$avgPercentage[] = sprintf("%1.1f", ($totalStudentScore/$totalExamScore)*100); 
								endif;	
								?>
                                                        </td>
                                                        <?php 
                                                        foreach($examGrades as $grade => $limit) :
                                                                if($totalStudentScore >= $limit) :
									end($examGrades);
									if(key($examGrades) == $grade):
										$colorScheme = 'background-color:#FF6B4F; color:#FFFFCC';
									else:
                                                                        	$colorScheme = 'background-color:#8BC540; color:#41612c';
									endif;
                                                                        break;
                                                                endif;
                                                        endforeach;
							$avgGrades[$grade]++; 
                                                        ?>
                                                        <td class="gru" style="border-bottom:1px #dedede solid; text-align:center; font-weight:bold; <?=$colorScheme?>">
								<?=$grade?>
                                                        </td>
                                                </tr>
						<?php endforeach;?>
                                                <tr class="avarage">
                                                        <th align="right" style="vertical-align:top">Avarage:</th>
                                                        <?php foreach($questions as $q):?>
                                                        	<?php $avg = sprintf("%1.1f", array_sum($overallQuestScore[$q->id])/count($overallQuestScore[$q->id]));?>
                                                        	<td title="Answers: <?=count($overallQuestScore[$q->id])?> Percent: <?=(count($students)/count($overallQuestScore[$q->id]))*100?>%" class="cc aa">
									<?=$avg?>
                                                                </td>
                                                        <?php endforeach;?>
                                                        
                                                        <td class="cc aa">
								<?=sprintf("%1.1f", array_sum($avgPercentage)/count($avgPercentage))?>%
                                                        </td>
                                                        <td title="Answers: 1 Percent: 500%" class="cc aa" style="text-align:right; margin:0; padding:0">
                                                          <?php foreach($examGrades as $grade => $limit):?>
                                                          	<div style="padding:1px; "><b><?=$grade?></b>: <?=$avgGrades[$grade]?></div>
                                                          <?php endforeach;?>
                                                        </td>
                                                        
                                                </tr>
                                        </tbody>
                                </table>
                        </div>        
                        <h5>Color Codes</h5>
                        <p>Following are the color codes used in the score board:</p>
                        <table style="margin:0">
                                <tbody>
                                        <tr class="colorcode">
                                                <td class="cc ac">&nbsp;</td>
                                                <td>Answer has been corrected.</td>
                                        </tr>
                                        <!--
                                        <tr class="colorcode">
                                                <td class="cc no">&nbsp;</td>
                                                <td>This answer should be corrected by another person.</td>
                                        </tr>
                                        -->
                                        <tr class="colorcode">
                                                <td class="cc na">&nbsp;</td>
                                                <td>No answer was given for this question.</td>
                                        </tr>
                                        <tr class="colorcode">
                                                <td class="cc nc">&nbsp;</td>
                                                <td>The answer has not yet been corrected.</td>
                                        </tr>
                                        <!--
                                        <tr class="colorcode">
                                                <td class="cc qr">&nbsp;</td>
                                                <td>Question is flagged as removed (no scores for this question is counted).</td>
                                        </tr>
                                        <tr class="colorcode">
                                                <td class="cc qu">&nbsp;</td>
                                                <td>This question was not assigned to this student.</td>
                                        </tr>
                                        -->
                                </tbody>
                        </table>
                        <!--
                        <h5>Download Scoreboard</h5>
                        <p>Click <a href="?exam=711&amp;mode=save">here</a> to download the score board.</p>-->
                </div>
        </div>
        <br clear="both">
        <!-- container --> 
</div>

<!--------------- Hidden Divs -----------------> 
<? //=Phalcon\Tag::stylesheetLink('plugins/validation/css/validationEngine.jquery.css'); ?>
<? //=Phalcon\Tag::javascriptInclude('plugins/validation/js/languages/jquery.validationEngine-en.js')?>
<? //=Phalcon\Tag::javascriptInclude('plugins/validation/js/jquery.validationEngine.js')?>

<script language="javascript">
$(document).ready(function () {
        $('.fb').fancybox({
                        'width': "100%", 
                        'height': "95%", 
                        'autoSize': false,
                        helpers : { 
                            overlay : {closeClick: false}
                        },
                        afterClose: function() {
                                location.reload();
                        }
        });
	
	$(document).on('click', '.save-result', function() {
		
		var saveResultBtn = $(this);
		var correctorComents = $(saveResultBtn).parent().find('textarea').val();
		var resultJson = {};
		var resId = ansId = 0;
		$(this).closest('.q-body').find('.q-points').each(function(index, element) {
			resultJson[$(element).attr('q-part')] = $.isNumeric($(element).val()) ? $(element).val() : 0;
                        ansId = $(element).attr('ans-id');
			resId = $(element).attr('res-id');
                });

		// send ajax requedt to update student's socre
		if(resId != 0) {
			param = {id:resId, "score":JSON.stringify(resultJson), "comment":correctorComents};
			action= 'update';
		} else {
			param = {"answer_id":ansId,"score":JSON.stringify(resultJson), "comment":correctorComents};
			action= 'create';
		}
		
		ajax (
			baseURL + 'core/ajax/corrector/result/' + action,
			param,
			function(rData) {
				$(saveResultBtn).closest('.q-body').parent().find('.not-corrected').hide('500');
			}
		);
	});
	
});	
</script>

<!--
<script>
	jQuery(document).ready(function(){
		// binds form submission and fields to the validation engine
		jQuery("#q-part-student-score").validationEngine();
		$(".saved-result").click(function(){
			alert("dd");
			jQuery("#q-part-student-score").validationEngine('validate');
		})
	});

</script>
-->