<?php

// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    form.phtml
// 
// Author:  Ahsan Shahzad (MedfarmDoIT)
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 


use OpenExam\Library\Security\Roles;
use OpenExam\Models\Question;
use Phalcon\Tag;

// 
// Create empty question if rendered from question/create:
// 
if (is_null($question)) {
        $question = new Question();
        $question->id = 0;
}

$qParts = json_decode($question->quest, true);
$totalQParts = count($qParts);

if ($role == Roles::CONTRIBUTOR) {
        $question->show_correctors = false;
} else {
        $question->show_correctors = true;
}

if ($exam->published) {
        $question->is_editable = false;
} else {
        $question->is_editable = true;
}

if ($question->status == 'removed') {
        $question->is_editable = true;
}

?>

<style>
    #q-parts-wrapper .ui-state-active {
        background: none repeat scroll 0 0 #c6e1ec !important;
        color: #3d7489 !important;
    }
    #q-parts-wrapper .ui-state-default {
        border-radius: 0px;
        padding-top: 0.8em;
    }
    .q_resources {
        border: 1px dashed #e2e2e2;
        margin-top: 10px;
        background-color: #f9f9f9;
        padding: 10px 0 6px;
    }
    .q_resources .add_resources a {
        color: #C02E3C;
        font-weight: normal;
        line-height: 1.25;
        margin-left: 2px;
        padding-left: 15px;
    }
    .q_resources ul {
        list-style: none;
        margin: 5px 0 0;
    }    
    .q_resources ul li {
        background-color: #f2f2f2;
        border: 1px solid #e2e2e2;
        float: left;
        margin-right: 8px;
        padding: 0 5px;
    }
    .q_resources ul li i {
        cursor: pointer;
    }    
    .ans_type_selector_box_wrap {
        border: 1px dashed #dedede;
        margin-bottom: 5px;
    }
    .ans_type_selector_box {
        margin: 10px;
    }
    .ans_type_selector_box label {
        font-weight: normal;
    }
    .ans_type {
        display: none;
        margin-left: 25px;
        padding-bottom: 5px;
    }
    .add-new-sortable {
        padding-left: 15px;        
    }
    .q-corrector-area {
        color: grey;
        font-weight: normal;
        border: 1px solid #e1e1e1;
        padding: 8px;
        width: 350px;
        border-radius: 3px;
    }
</style>

<!-- Question form that appears in dialog -->
<div  id="question-form" style="padding-top:20px; ">
    <div id="qPartTabs" class="<?= $question->is_editable ? '' : 'oe-disabled'; ?>">
        <?php $tabCounter = 1 ?>
        <ul id="q-part-tabs" style=" <?= ($totalQParts <= 1 ? "display:none" : "") ?>">
            <li><a href="#q-part-<?= $tabCounter ?>">Part a</a><span class="ui-icon ui-icon-close" role="presentation">Remove Tab</span></li>
            <?php for ($tabCounter; $tabCounter < $totalQParts; $tabCounter++): ?>
                    <li><a href="#q-part-<?= $tabCounter + 1 ?>">Part
                            <?= chr($tabCounter + 97) ?>
                        </a><span class="ui-icon ui-icon-close" role="presentation">Remove Tab</span></li>
            <?php endfor; ?>
        </ul>
        <div id="q-parts-wrapper">
            <?php
            $i = 1;
            do {
                    $qPartTitle = chr($i + 96);

                    ?>
                    <div id="q-part-<?= $i ?>" class="q-part" style="padding:<?= ($tabCounter <= 1 ? "0px" : "1em 1.4em") ?>;">
                        <div class="accordion">

                            <h3>Write question</h3>
                            <div>
                                <article class="ac-large">
                                    <div>
                                        <?php $qText = $qParts[$qPartTitle]['q_text']; ?>
                                        <textarea id="q_text<?= $i ?>" class="write_q_ckeditor" style="width:99%;" rows="1" placeholder="Write your question here"><?= $qText ?>
                                        </textarea>
                                        <div class="q_resources lib_resources">
                                            <div class="add_resources">
                                                <a class="add_media" href="#">
                                                    <i class="fa fa-plus-square" aria-hidden="true" style="color: limegreen;"></i>
                                                    <span> Add supplementary materials</span>
                                                </a>
                                            </div>
                                            <ul class="lib_resources_list">
                                                <?php if (count($qParts[$qPartTitle]['resources'])): ?>
                                                        <?php foreach ($qParts[$qPartTitle]['resources'] as $rTitle => $rLink): ?>
                                                                <li> 
                                                                    <i class="fa fa-close resource-item-remove"></i> 
                                                                    <i class="fa fa-pencil resource-item-edit"></i> 
                                                                    <a target="_blank" file-path="<?= $rLink ?>" href="<?= $this->url->get($rLink) ?>"><?= empty($rTitle) ? urldecode(basename($rLink)) : $rTitle ?></a> 
                                                                    </i> 
                                                                </li>
                                                        <?php endforeach; ?>
                                                <?php endif; ?>
                                            </ul>
                                            <div style="clear:both"></div>
                                        </div>
                                    </div>
                                </article>
                            </div>

                            <h3>Answer options</h3>
                            <?php $qAnsType = $qParts[$qPartTitle]['ans_area']['type'] ?>
                            <div class="answering_options">
                                <article class="ac-large">
                                    <div style="padding:10px">
                                        <div class="ans_type_selector_box_wrap">
                                            <div class="ans_type_selector_box">
                                                <label>
                                                    <input class="ans_type_selector" type="radio" value="textbox" <?= ($qAnsType == 'textbox') ? 'checked="checked"' : '' ?> />
                                                    <span> Single line text box</span> 
                                                </label>
                                            </div>
                                            <div class="ans_type" style=" <?= ($qAnsType == 'textbox') ? 'display:block' : 'display:none' ?>">
                                                <input type="text" style="width:350px" class="readable form-control"/>
                                            </div>
                                        </div>
                                        <div class="ans_type_selector_box_wrap">
                                            <div class="ans_type_selector_box">
                                                <label>
                                                    <input type="radio"  class="ans_type_selector" value="textarea" <?= ($qAnsType == 'textarea') ? 'checked="checked"' : '' ?>/>
                                                    <span>Multi line text box</span> 
                                                </label>
                                            </div>
                                            <div class="ans_type" style=" <?= ($qAnsType == 'textarea') ? 'display:block' : 'display:none' ?>">
                                                <?= Tag::image(array("img/ckeditor.png", "width" => '40%')); ?>
                                                <div style="margin-top: 5px; padding-left: 15px; border-left: 3px solid #dddddd">
                                                    <?php
                                                    if (isset($qParts[$qPartTitle]['ans_area']['word_count'])) {
                                                            $wordcount = (int) $qParts[$qPartTitle]['ans_area']['word_count'];
                                                            $wordother = !in_array($wordcount, array(-1, 100, 250, 500));
                                                    } else {
                                                            $wordcount = -1;
                                                            $wordother = false;
                                                    }

                                                    if (isset($qParts[$qPartTitle]['ans_area']['spell_check'])) {
                                                            $spellcheck = (bool) $qParts[$qPartTitle]['ans_area']['spell_check'];
                                                    } else {
                                                            $spellcheck = false;
                                                    }

                                                    ?>
                                                    Word Count: 
                                                    <form class="word-count-selector" action="">
                                                        <input type="radio" name="word-count" value="-1" <?= $wordcount == -1 ? 'checked="checked"' : '' ?>>
                                                        <span style="margin-right: 25px; margin-left: 5px"> 
                                                            Unlimited
                                                        </span>
                                                        <input type="radio" name="word-count" value="100"  <?= $wordcount == 100 ? 'checked="checked"' : '' ?>>
                                                        <span style="margin-right: 25px; margin-left: 5px"> 
                                                            100
                                                        </span> 
                                                        <input type="radio" name="word-count" value="250"  <?= $wordcount == 250 ? 'checked="checked"' : '' ?>>
                                                        <span style="margin-right: 25px; margin-left: 5px"> 
                                                            250
                                                        </span>
                                                        <input type="radio" name="word-count" value="500" <?= $wordcount == 500 ? 'checked="checked"' : '' ?>>
                                                        <span style="margin-right: 25px; margin-left: 5px"> 
                                                            500
                                                        </span>      
                                                        <input type="radio" name="word-count" value="<?= $wordother ? $wordcount : "" ?>" class="word-count-unlimited" <?= $wordother ? 'checked="checked"' : '' ?>>
                                                        <span style="margin-right: 10px; margin-left: 5px"> 
                                                            Other: 
                                                        </span>      
                                                        <input type="text" value="<?= $wordother ? $wordcount : "" ?>" onchange="this.closest('form').querySelectorAll('.word-count-unlimited')[0].value = this.value" class="form-control">
                                                    </form>
                                                </div>
                                                <div style="margin-top: 5px; padding-left: 15px; border-left: 3px solid #dddddd">
                                                    <input type="checkbox" name="spell-check" <?= $spellcheck ? 'checked="checked"' : '' ?>>
                                                    <span style="margin-right: 10px; margin-left: 5px"> 
                                                        Enable spell checker
                                                    </span>      
                                                </div>
                                            </div>
                                        </div>
                                        <div class="ans_type_selector_box_wrap">
                                            <div class="ans_type_selector_box">
                                                <label>
                                                    <input type="radio"  class="ans_type_selector" value="choicebox" <?= ($qAnsType == 'choicebox') ? 'checked="checked"' : '' ?>/>
                                                    <span>Choice box</span> 
                                                </label>
                                            </div>
                                            <div class="ans_type" style=" <?= ($qAnsType == 'choicebox') ? 'display:block' : 'display:none' ?>">
                                                <div class="qline_wrapper">
                                                    <div class="choice_q qline" style="width:100%">
                                                        <div class="question_opts" style="padding-bottom:5px">
                                                            <?php if (count($qParts[$qPartTitle]['ans_area']['data'])): ?>
                                                                    <?php foreach ($qParts[$qPartTitle]['ans_area']['data'] as $optText => $checked): ?>
                                                                            <div style="padding-top:5px">
                                                                                <span class="delopt hideable">
                                                                                    <i class="fa fa-minus-circle" aria-hidden="true" style="color: red"></i>                                                        
                                                                                </span>
                                                                                <input type="checkbox" class="readable" <?= $checked ? 'checked="checked"' : '' ?>>
                                                                                <div contenteditable="true" ckeditor="choice" style="display: inline-block"><?= $optText ?></div> 
                                                                            </div>
                                                                    <?php endforeach; ?>
                                                            <?php else: ?>
                                                                    <?php for ($j = 1; $j <= 3; $j++) : ?>
                                                                            <?php $optTxt = "Option " . $j . " - click to edit"; ?>
                                                                            <div style="padding-top:5px">
                                                                                <span class="delopt hideable">
                                                                                    <i class="fa fa-minus-circle" aria-hidden="true" style="color: red"></i>                                                        
                                                                                </span>
                                                                                <input type="checkbox" class="readable">
                                                                                <div contenteditable="true" ckeditor="choice" style="display: inline-block" class="editabletext"><?= $optTxt ?></div>
                                                                            </div>
                                                                    <?php endfor; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                        <span class="add-new-sortable hideable">
                                                            <i class="fa fa-plus-square" aria-hidden="true" style="color: limegreen;"></i>
                                                            <a href="#" style="color:grey" onClick="return false">Add new option</a>
                                                        </span> 
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="ans_type_selector_box_wrap">
                                            <div class="ans_type_selector_box">
                                                <label>
                                                    <input type="radio"  class="ans_type_selector" value="canvas" <?= ($qAnsType == 'canvas') ? 'checked="checked"' : '' ?>/>
                                                    <span>Drawing Canvas</span> 
                                                </label>
                                            </div>
                                            <div class="ans_type" style=" <?= ($qAnsType == 'canvas') ? 'display:block' : 'display:none' ?>">
                                                <div class="qline_wrapper">
                                                    <?= Tag::image(array("img/canvas.png", "width" => '40%')); ?>
                                                </div>
                                                <div class="q_resources lib_canvas">
                                                    <div class="add_resources">
                                                        <a class="set_canvas_background" href="#">
                                                            <i class="fa fa-plus-square" aria-hidden="true" style="color: limegreen;"></i>
                                                            <span> Select background image</span>
                                                        </a>
                                                    </div>
                                                    <ul class="lib_canvas_background">
                                                        <?php if ($qParts[$qPartTitle]['ans_area']['back']): ?>
                                                                <?php foreach ($qParts[$qPartTitle]['ans_area']['back'] as $rTitle => $rLink): ?>
                                                                        <li> 
                                                                            <i class="fa fa-close resource-item-remove"></i> 
                                                                            <i class="fa fa-pencil resource-item-edit"></i> 
                                                                            <a target="_blank" file-path="<?= $rLink ?>" href="<?= $this->url->get($rLink) ?>"><?= empty($rTitle) ? urldecode(basename($rLink)) : $rTitle ?></a> 
                                                                            </i> 
                                                                        </li>
                                                                <?php endforeach; ?>
                                                        <?php endif; ?>
                                                    </ul>
                                                    <div style="clear:both"></div>
                                                </div>                                                
                                            </div>
                                        </div>
                                </article>
                            </div>

                            <h3>Points</h3>
                            <div>
                                <div style="min-height:200px"> Maximum points:
                                    <input type="text" class="q-part-points form-control" style="width:50px" value="<?= floatval($qParts[$qPartTitle]['q_points']) ?>" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php
                    $i++;
            } while ($i <= $tabCounter);

            ?>
        </div>
    </div>
    <?php if ($question->show_correctors) : ?>
            <br style="clear:both" />
            <div style="margin:0px 10px 10px;" id="q_correctors">
                <article class="ac-large">
                    <div style="font-weight:bold"> Question Correctors: 
                        <a href="#" id="uu-id4" data-model="corrector" qid='<?= $question->id ?>' class="search-catalog-service prevent">
                            <i class="fa fa-plus-circle" aria-hidden="true" style="color: limegreen"></i>
                        </a> 
                        <br>
                        <div class="q-corrector-area">
                            <ul class="q_corrector_list" style="list-style:none; margin:0px">
                                <!-- corrector item template -->
                                <li style="display: none">
                                    <i class="fa fa-minus-circle" aria-hidden="true" style="color: red" class="del-corrector"></i>
                                    <span data-user="" data-rec="" class="left-col-user"></span>
                                </li>
                                <?php foreach ($question->correctors as $corrector): ?>
                                        <li>
                                            <a href="#" class="del-corrector">
                                                <i class="fa fa-minus-circle" aria-hidden="true" style="color: red"></i>
                                                <span data-user="<?= $corrector->user ?>" data-rec="<?= $corrector->id ?>" class="left-col-user">
                                                    <?= $corrector->display ?>
                                                </span>
                                            </a>
                                        </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </article>
            </div>
    <?php endif; ?>
</div>

<!-- Dialog for resource selection -->
<div  id="media-library" style="display:none" title="Media file manager"></div>

<script language="javascript">
        var tabId = tabCounter = <?= ($totalQParts ? $totalQParts + 1 : 2) ?>;
        var qId = <?= $question->id ?>;
        var qIsEditable = <?= $question->is_editable ? 1 : 0 ?>;
        var role = '<?= $role ?>';
</script>

<script ckeditor="choice">
        // 
        // Use custom config for ckeditor bound on elements having 
        // ckeditor="choice" as custom attribute.
        // 
        CKEDITOR.on('instanceCreated', function (event) {
            var editor = event.editor;
            if (editor.element.getAttribute('ckeditor') === "choice") {
                editor.on('configLoaded', function () {
                    editor.config.toolbar = [
                        {
                            name: 'clipboard',
                            groups: ['clipboard', 'undo'],
                            items: ['Cut', 'Copy', 'Paste', '-', 'Undo', 'Redo']
                        },
                        {
                            name: 'basicstyles',
                            groups: ['basicstyles', 'cleanup'],
                            items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript']
                        },
                        {
                            name: 'insert',
                            items: ['Smiley', 'SpecialChar']
                        }
                    ];
                });
            }
        });

        // 
        // Remove standard characters, add greek alphabeth instead:
        // 
        CKEDITOR.config.specialChars = [
            "Α", "Β", "Γ", "Δ", "Ε", "Ζ", "Η", "Θ", "Ι", "Κ", "Λ", "Μ", "Ν", "Ξ", "Ο", "Π", "Ρ", "Σ", "Τ", "Υ", "Φ", "Χ", "Ψ", "Ω",
            "α", "β", "γ", "δ", "ε", "ζ", "η", "θ", "ι", "κ", "λ", "μ", "ν", "ξ", "ο", "π", "ρ", "σ", "τ", "υ", "φ", "χ", "ψ", "ω",
            "€", "‘", "’", "“", "”", "–", "—", "¡", "¢", "£", "¤", "¥", "¦", "§", "¨", "©", "ª", "«", "¬", "®", "¯", "°", "²", "³", "´", "µ", "¶", "·", "¸", "¹", "º", "»", "¼", "½", "¾", "¿",
            "À", "Á", "Â", "Ã", "Ä", "Å", "Æ", "Ç", "È", "É", "Ê", "Ë", "Ì", "Í", "Î", "Ï", "Ð", "Ñ", "Ò", "Ó", "Ô", "Õ", "Ö", "×", "Ø", "Ù", "Ú", "Û", "Ü", "Ý", "Þ", "ß",
            "à", "á", "â", "ã", "ä", "å", "æ", "ç", "è", "é", "ê", "ë", "ì", "í", "î", "ï", "ð", "ñ", "ò", "ó", "ô", "õ", "ö", "÷", "ø", "ù", "ú", "û", "ü", "ý", "þ", "ÿ",
            "Œ", "œ", "Ŵ", "Ŷ", "ŵ", "ŷ", "‚", "‛", "„", "…", "™", "►", "•", "→", "⇒", "⇔", "♦", "≈"
        ];

        // 
        // Inline ckeditor on elements with ckeditor="choice" attribute:
        // 
        $(document).find('div[ckeditor="choice"]').each(function (index, element) {
            CKEDITOR.inline(element);
        });
</script>
<!-- User search support -->
<?php $this->partial("partials/user-search", array('staff' => $staff)) ?>

<!-- Include question form javascript -->
<?= Tag::javascriptInclude('js/views/question/form.js') ?>
