<!-- BISMILLAH-->

<!-- question content row ends --> 
<div class='col-xs-12'>

        <!-- question title row -->
        <?php /*
        <div class='row'>
                <div class='col-sm-12'> 
                        
                        <!-- question title -->
                        <div class='page-header'>
                                <h1 class='pull-left' style="font-size:24px"> <i class="icon-q<?=$quest->name?>"></i>
                                        <span><?=$qJson['a']['q_text']?></span> 
                                </h1>
                                <!--<div class='pull-right'> Right_area </div>-->
                        </div>
                        <!-- question title ends --> 
                        
                </div>
        </div>
	*/?>
	<?php if($testMode):?>
        <div class="alert alert-info alert-dismissable" style="margin:15px 0px;">  
                <strong>Test mode activated.</strong> <br />
		You are currently previewing these questions in test mode. Please note that your Answers will <strong>not</strong> be saved.<br />
                If you see any issues, please feel free to <a href="#">contact us</a>.
                Click <a href="<?=$this->url->get('exam/index')?>">here</a> to return back on exam management page.
        </div>
        <?php endif;?>
        
	<?php if(!$testMode && $viewMode == 'all'):?>
        <div class="alert alert-info alert-dismissable" style="margin:15px 0px;">  
                <a href="#" data-dismiss="alert" class="close">×</a>
                Here you can preview all of your answers. Please <a href="<?=$this->url->get('auth/logout')?>">sign out</a> and close all opened browser windows, once you are satisfied with your answers.
        </div>
        <?php endif;?>


	<?php foreach($quest as $qKey => $qObj):
		if(!$qObj->id)
			continue;
	?>
	
        <?php
        $qParts  = json_decode($qObj->quest, true);
        $answerData = json_decode($answer[$qObj->id]->answer, true);
        ?>
        <!-- question content row -->
        <div class="row" style="margin-top:15px">
        
                <div class="col-sm-12">
                        <div class="box bordered-box blue-border">
                                <div class="box-content box-double-padding" style="font-family:verdana; <?=$viewMode == 'all' ? 'border-bottom: 10px solid #F34541':''?>">
                                	<i class="q-no icon-q<?=$qObj->name?> text-contrast">:</i>
                                        <?php $partCount = 1;?>
                                        <?php foreach($qParts as $qPart => $qPartData):?>
                                        
                                        <?php if(count($qParts) > 1):?>
					<span class="q-part-title"><?=$qPart?>.</span>                                        	
                                        <?php endif;?>
                                        
					<span class="q-part-pts" style=" <?=$qPart=='a' ? 'border-radius: 0 0 5px' : ''?>"><?=sprintf("%02d", $qPartData['q_points'])?> pt.</span>
                                        
                                        <div style="margin-bottom: 0;" class="form q-part" data-id="<?=$qPart?>" >
                                                <fieldset>
                                                        <div class="q-part-ans-area col-sm-7 col-sm-offset-1">
                                                                <div class="q-part-text" style="padding-bottom:10px">
                                                                	<label><?=$qPartData['q_text']?></label>
                                                                </div>
                                                                
                                                                <?php if($viewMode == 'all'): ?>
                                                                
									<?php if(is_array($qPartData['ans_area']['data']) && count($qPartData['ans_area']['data'])):?>
                                                                        <div>
                                                                        	<ul>
											<?php foreach($qPartData['ans_area']['data'] as $qPartOpt => $ans):?>
                                                                                        <li><?=$qPartOpt?></li>
                                                                                        <?php endforeach;?>
                                                                                </ul>
                                                                        </div>                                                                        
                                                                	<?php endif;?>
                                                                        
                                                                        <div style="color:#F45956; padding-top:15px">Your Answer:</div>
                                                                        <?php if(!empty($answerData[$qPart]['ans'][0])):?>
                                                                        <div style="background-color:#F4F4F4; border-left: 5px solid #dedede; padding:10px">
                                                                                <?php if(count($answerData[$qPart]['ans']) > 1):?>
                                                                                <ul>
                                                                                        <?php foreach($answerData[$qPart]['ans'] as $optAns):?>
                                                                                                <li><?=$optAns?></li>
                                                                                        <?php endforeach;?>
                                                                                </ul>
                                                                                <?php else:?>
                                                                                <?=$answerData[$qPart]['ans'][0]?>
                                                                                <?php endif;?>
                                                                        </div>
                                                                        <?php else:?>
                                                                        <i>You haven't answerd this part.</i>
                                                                        <?php endif;?>
                                                                <?php else:?>
	                                                                <div class="form-group q-part-ans-type" data-id="<?=$qPartData['ans_area']['type']?>">
                                                                	<?php if($qPartData['ans_area']['type'] == 'textbox'):?>
                                                                        	
                                                                                <input type="text" style="font-size:11px" class="form-control changeable" value="<?=$answerData[$qPart]['ans'][0]?>" placeholder="Write your answer here ..." />
                                                                                
                                                                	<?php elseif($qPartData['ans_area']['type'] == 'canvas'):?>
                                                                        
                                                                                <input type="text" style="font-size:11px" class="form-control changeable" value="<?=$answerData[$qPart]['ans'][0]?>"  />
                                                                                
                                                                	<?php elseif($qPartData['ans_area']['type'] == 'choicebox'):?>
                                                                        
                                                                                <div class="col-md-10">
                                                                                	<?php $i = 0;?>
                                                                                	<?php foreach($qPartData['ans_area']['data'] as $qPartOpt => $ans):?>
                                                                                        <div class="checkbox">
                                                                                                <label>
													<input type="checkbox" value="<?=$qPartOpt?>" class="changeable" <?=isset($answerData[$qPart]['ans']) && in_array($qPartOpt, $answerData[$qPart]['ans']) ? 'checked="checked"' : ''?>>
                                                                                                        <?=$qPartOpt?>
                                                                                                </label>
                                                                                        </div>
                                                                                        <?php $i++;?>
                                                                                	<?php endforeach;?>
                                                                                </div>                                                                        
                                                                                
                                                                	<?php else:?>
                                                                                <textarea id="q-<?=$qObj->name?>_part-<?=$qPart?>" class="form-control changeable ckeditor"><?=$answerData[$qPart]['ans'][0]?></textarea>
                                                                        <?php endif;?>
                                                                	</div>
                                                                <?php endif;?>
                                                        </div>
                                                        <?php if(count($qPartData['resources'])):?>
							<div class="q-part-resource-area col-sm-4" style="width:40.3333%">
                                                                <div class="box">
                                                                        <div class="lead" style="font-size:15px"> 
                                                                        	<i class="icon-file-text-alt text-contrast"></i> Supplementary material 
                                                                        </div>
                                                                        <?php foreach($qPartData['resources'] as $resTitle => $resUrl) :?>
                                                                        <div style="margin-bottom:15px; ">
										<?php 
										$type = basename(dirname($resUrl)).'s';
										$path = $this->config->application->mediaDir.$type.DIRECTORY_SEPARATOR.basename(urldecode($resUrl));
										$mimeType = finfo_file(finfo_open(FILEINFO_MIME_TYPE), $path);
										?>
                                                                                <div>
	                                                                            <a class="fancybox" rel="fancybox" href="<?=$resUrl?>" title="<?=$resTitle?>">
                                                                                        <?php if(stristr($mimeType, "image/")):?>
                                                                                        <img style="max-width:400px" class="img-zoom" src='<?=$resUrl?>' data-zoom-image="<?=$resUrl?>"/>
                                                                                        <?php else:?>
                                                                                        <a class="media {width:400}" href="<?=$resUrl?>"></a> 
                                                                                        <a target="_blank" href="<?=$resUrl?>" style="font-size:9px">Download this file</a>
                                                                                        <?php endif;?>
                                                                                    </a>    
                                                                                </div>
                                                                                <div>
                                                                                        <small class="text-muted" style="padding:5px"><?=$resTitle?></small> <br />
                                                                                </div>
                                                                        </div>
                                                                        <?php endforeach;?>
                                                                </div>
                                                        </div>                                            
                                                        <?php endif;?>            
                                                </fieldset>
                                                <?php if($partCount++ != count($qParts)):?>
                                                <hr class="q-part-seprator hr-normal" />
                                                <?php endif;?>
                                        </div>
                                        <?php endforeach;?>
					
                                        <div style="margin:0px 15px " class="actions">
                                                <div class="row q-actions">
                                                	<?php if($viewMode == 'single'): ?>
                                                                <div style="padding-bottom:25px">
                                                                        <label style="font-weight:normal">
                                                                        <input type="checkbox" id="highlight_q" value="1" class="changeable" <?=$answerData['highlight-q'] == 'yes' ? 'checked':''?> <?=$testMode ? 'disabled':''?>>
                                                                         <span style="font-size:14px">I would like to review my answer for this question later on, so mark it.</span>
                                                                         </label>
                                                                </div>
                                                                <?php if($qObj->name != '1'):?>
                                                                <a href="<?=$this->url->get('exam/'.$exam->id.'/question/'.($qObj->name-1))?>">
                                                                        <button class="btn btn-xs btn-prev"><i class="icon-arrow-left"></i> Prev. Question </button>
                                                                </a>
                                                                <?php endif;?>
                                                                
                                                                <?php if($qObj->name != count($questions)):?>
                                                                <a href="<?=$this->url->get('exam/'.$exam->id.'/question/'.($qObj->name+1))?>">
                                                                        <button class="btn btn-xs btn-success btn-next"> Next Question <i class="icon-arrow-right"></i></button>
                                                                </a>
                                                                <?php else:?>
                                                                <a href="<?=$this->url->get('exam/'.$exam->id.'/question/all')?>">
                                                                        <button class="btn btn-xs btn-success btn-next"><i class="icon-list"></i> Preview your answers for all questions</button>
                                                                </a>
                                                                <?php endif;?>
                                                        <?php else:?>
                                                                <a href="<?=$this->url->get('exam/'.$exam->id.'/question/'.($qObj->name))?>">
                                                                        <button class="btn btn-xs btn-success btn-prev"><i class="icon-pencil"></i> Change your Answer for this question </button>
                                                                </a>
							<?php endif;?>
                                                </div>
                                        </div>
                        	</div>
                      </div>        
                                        
                </div>
        </div>
        <?php endforeach;?>
</div>

<div class="ans-sync-msg">Saving ... </div>
<div id="exam-instructions" class="hero-unit" style="min-width:800px; display:none; font-family:Verdana, Geneva, sans-serif;">
        <div class="head"><?=Phalcon\Tag::image(array("img/uu_logo.svg", "height"=>"55px", "style"=>"padding-right:20px"));?>
        	<span style="color: #c2100c">Exam instructions: <?=$exam->name?></span>
        </div>
        <?=$exam->descr?>
</div>

<?=Phalcon\Tag::javascriptInclude('js/jquery.media.js'); ?>
<?=Phalcon\Tag::javascriptInclude('js/jquery.elevatezoom.js'); ?>
<?=Phalcon\Tag::javascriptInclude('plugins/ckeditor/ckeditor.js');?>
<?=Phalcon\Tag::javascriptInclude('plugins/ckeditor/adapters/jquery.js');?>
<?=Phalcon\Tag::javascriptInclude('js/views/question/view.js'); ?>
<script language="javascript" type="text/javascript">
	<?php if(!$testMode && $viewMode == 'single'):?>
	var qName   = <?=$qObj->name?>;
	var ansId   = <?=$answer[$qObj->id]->id?>;
	<?php else:?>
	var ansId   = 'None!';
	<?php endif;?>
	
	var count = <?=(strtotime($exam->starttime) - strtotime("now"))?>;
</script> 
