<!-- BISMILLAH-->

<?php
$qParts     = json_decode($quest->quest, true);
$questions  = $exam->getQuestions();
$answerData = json_decode($answer->answer, true);
?>

<!-- question content row ends --> 
<div class='col-xs-12'>

        <!-- question title row -->
        <?php /*
        <div class='row'>
                <div class='col-sm-12'> 
                        
                        <!-- question title -->
                        <div class='page-header'>
                                <h1 class='pull-left' style="font-size:24px"> <i class="icon-q<?=$quest->name?>"></i>
                                        <span><?=$qJson['a']['q_text']?></span> 
                                </h1>
                                <!--<div class='pull-right'> Right_area </div>-->
                        </div>
                        <!-- question title ends --> 
                        
                </div>
        </div>
	*/?>
        <!-- question content row -->
        <div class="row" style="margin-top:15px">
                <div class="col-sm-12">
                        <div class="box bordered-box blue-border">
                                <div class="box-content box-double-padding" style="font-family:verdana">
                                	<i class="q-no icon-q<?=$quest->name?> text-contrast">:</i>
                                        <?php $partCount = 1;?>
                                        <?php foreach($qParts as $qPart => $qPartData):?>
                                        
                                        <?php if(count($qParts) > 1):?>
					<span class="q-part-title"><?=$qPart?>.</span>                                        	
                                        <?php endif;?>
                                        
					<span class="q-part-pts" style=" <?=$qPart=='a' ? 'border-radius: 0 0 5px' : ''?>"><?=sprintf("%02d", $qPartData['q_points'])?> pt.</span>
                                        
                                        <div style="margin-bottom: 0;" class="form q-part" data-id="<?=$qPart?>" >
                                                <fieldset>
                                                        <div class="q-part-ans-area col-sm-7 col-sm-offset-1">
                                                                <div class="q-part-text">
                                                                	<label><?=$qPartData['q_text']?></label>
                                                                </div>
                                                                <div class="form-group q-part-ans-type" data-id="<?=$qPartData['ans_area']['type']?>">
                                                                	<?php if($qPartData['ans_area']['type'] == 'textbox'):?>
                                                                        	
                                                                                <input type="text" style="font-size:11px" class="form-control changeable" value="<?=$answerData[$qPart]['ans'][0]?>" placeholder="Write your answer here ..." />
                                                                                
                                                                	<?php elseif($qPartData['ans_area']['type'] == 'canvas'):?>
                                                                        
                                                                                <input type="text" style="font-size:11px" class="form-control changeable" value="<?=$answerData[$qPart]['ans'][0]?>"  />
                                                                                
                                                                	<?php elseif($qPartData['ans_area']['type'] == 'choicebox'):?>
                                                                        
                                                                                <div class="col-md-10">
                                                                                	<?php $i = 0;?>
                                                                                	<?php foreach($qPartData['ans_area']['data'] as $qPartOpt => $ans):?>
                                                                                        <div class="checkbox">
                                                                                                <label>
													<input type="checkbox" value="<?=$qPartOpt?>" class="changeable" <?=isset($answerData[$qPart]['ans']) && in_array($qPartOpt, $answerData[$qPart]['ans']) ? 'checked="checked"' : ''?>>
                                                                                                        <?=$qPartOpt?>
                                                                                                </label>
                                                                                        </div>
                                                                                        <?php $i++;?>
                                                                                	<?php endforeach;?>
                                                                                </div>                                                                        
                                                                                
                                                                	<?php else:?>
                                                                                <textarea id="q-<?=$quest->name?>_part-<?=$qPart?>" class="form-control changeable ckeditor"><?=$answerData[$qPart]['ans'][0]?></textarea>
                                                                        <?php endif;?>
                                                                </div>
                                                        </div>
                                                        <?php if(count($qPartData['resources'])):?>
							<div class="q-part-resource-area col-sm-4" style="width:40.3333%">
                                                                <div class="box">
                                                                        <div class="lead" style="font-size:15px"> 
                                                                        	<i class="icon-file-text-alt text-contrast"></i> Supplimentry material 
                                                                        </div>
                                                                        <?php foreach($qPartData['resources'] as $resTitle => $resUrl) :?>
                                                                        <div style="margin-bottom:15px; ">
										<?php 
										$type = basename(dirname($resUrl)).'s';
										$path = $this->config->application->mediaDir.$type.DIRECTORY_SEPARATOR.basename($resUrl);
										$mimeType = finfo_file(finfo_open(FILEINFO_MIME_TYPE), urldecode($path)); 
										?>
                                                                                <div>
	                                                                            <a class="fancybox" rel="fancybox" href="<?=$resUrl?>" title="<?=$resTitle?>">
                                                                                        <?php if(stristr($mimeType, "image/")):?>
                                                                                        <img style="max-width:300px" class="img-zoom" src='<?=$resUrl?>' data-zoom-image="<?=$resUrl?>"/>
                                                                                        <?php else:?>
                                                                                        <a class="media {width:480, height:425}" href="<?=$resUrl?>"></a> 
                                                                                        <a target="_blank" href="<?=$resUrl?>" style="font-size:9px">Download this file</a>
                                                                                        <?php endif;?>
                                                                                    </a>    
                                                                                </div>
                                                                                <div>
                                                                                        <small class="text-muted" style="padding:5px"><?=$resTitle?></small> <br />
                                                                                </div>
                                                                        </div>
                                                                        <?php endforeach;?>
                                                                </div>
                                                        </div>                                            
                                                        <?php endif;?>            
                                                </fieldset>
                                                <?php if($partCount++ != count($qParts)):?>
                                                <hr class="q-part-seprator hr-normal" />
                                                <?php endif;?>
                                        </div>
                                        <?php endforeach;?>
					
                                        <div style="margin:0px 15px " class="actions">
                                                <div class="row q-actions">
                                                        <div style="padding-bottom:25px">
                                                                <label style="font-weight:normal">
                                                                <input type="checkbox" id="highlight_q" value="1" class="changeable" <?=$answerData['highlight-q'] == 'yes' ? 'checked':''?>>
                                                                 <span style="font-size:14px">I would like to review my answer for this question later on, so mark it.</span>
                                                                 </label>
                                                        </div>
                                                        <?php if($quest->name != '1'):?>
                                                        <a href="<?=$this->url->get('exam/'.$exam->id.'/question/'.($quest->name-1))?>">
                                                        	<button class="btn btn-xs btn-prev"><i class="icon-arrow-left"></i> Prev. Question </button>
                                                        </a>
                                                        <?php endif;?>
                                                        
                                                        <?php if($quest->name != count($questions)):?>
                                                        <a href="<?=$this->url->get('exam/'.$exam->id.'/question/'.($quest->name+1))?>">
                                                        	<button class="btn btn-xs btn-success btn-next"> Next Question <i class="icon-arrow-right"></i></button>
                                                        </a>
                                                        <?php endif;?>
                                                </div>
                                        </div>
                        	</div>
                      </div>        
                                        
                </div>
        </div>
</div>

<div class="ans-sync-msg">Saving ... </div>
<div id="exam-instructions" class="hero-unit" style="min-width:800px; display:none; font-family:Verdana, Geneva, sans-serif;">
        <div class="head"><?=Phalcon\Tag::image(array("img/uu_logo.svg", "height"=>"55px", "style"=>"padding-right:20px"));?>
        	<span style="color: #c2100c">Exam instructions: <?=$exam->name?></span>
        </div>
        <?=$exam->descr?>
</div>

<?=Phalcon\Tag::javascriptInclude('js/jquery.media.js'); ?>
<?=Phalcon\Tag::javascriptInclude('js/jquery.elevatezoom.js'); ?>
<?=Phalcon\Tag::javascriptInclude('plugins/ckeditor/ckeditor.js');?>
<?=Phalcon\Tag::javascriptInclude('plugins/ckeditor/adapters/jquery.js');?>
<?=Phalcon\Tag::javascriptInclude('js/views/question/view.js'); ?>
<script language="javascript" type="text/javascript">
	var qName   = <?=$quest->name?>;
	var ansId = <?=$answer->id?>;
	var count = <?=(strtotime($exam->starttime) - strtotime("now"))?>;
</script> 
