<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    cardbox.phtml
// Created: 2016-11-29 01:59:53
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>
<style>
    div.mbox {
        padding: 20px;
        margin: 10px;
        margin-top: 50px;
        box-shadow: 1px 1px 6px #999999;
        border-radius: 10px 10px 10px 10px;
        background: #ffffff;
        max-width: 1024px;
    }
</style>

<div class="mbox">
    <?= $this->getContent() ?>
</div>
