<?php
/*
 * Copyright (C) 2016-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    cardbox.phtml
// Created: 2016-11-29 01:59:53
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>
<style>
    div.mbox {
        padding: 20px;
        margin: 10px;
        box-shadow: 1px 1px 6px #999999;
        border-radius: 10px 10px 10px 10px;
        background: #ffffff;
    }
    div.card-box {
        margin-left: 30px;
    }
    div.card {
        float: left;
        width: 25%;
        border-radius: 3px;
        border: 1px solid lightgray;
        min-height: 120px;
    }
    div.card-block {
        margin: 5px;
        padding: 15px;
        padding-top: 0px;
    }
    p.card-text {
        min-height: 50px;
    }
    ul.card {
        list-style: disc;
        display: none;
    }
    div.card .btn {
        margin-right: 10px;
    }
    @media print { 
        ul.card {
            display: block;
        }
        .no-print {
            display: none;
        }
        .pagebreak { 
            page-break-before: always; 
        }
    }
</style>

<div class="mbox">
    <?= $this->getContent() ?>
</div>
