<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    cardbox.phtml
// Created: 2016-11-29 01:59:53
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>
<style>
    div.mbox {
        padding: 20px;
        margin: 10px;
        margin-top: 50px;
        box-shadow: 1px 1px 6px #999999;
        border-radius: 10px 10px 10px 10px;
        background: #ffffff;
        max-width: 1024px;
    }
    div.card-box {
        margin-left: 30px;
    }
    div.card {
        float: left;
        width: 25%;
        border-radius: 3px;
        border: 1px solid lightgray;
        min-height: 120px;
    }
    div.card-block {
        margin: 5px;
        padding: 15px;
        padding-top: 0px;
    }
    p.card-text {
        min-height: 50px;
    }
    ul.card {
        list-style: disc;
        display: none;
    }
    div.card .btn {
        margin-right: 10px;
    }
    @media print { 
        ul.card {
            display: block;
        }
        .no-print {
            display: none;
        }
        .pagebreak { 
            page-break-before: always; 
        }
    }
</style>

<div class="mbox">
    <?= $this->getContent() ?>
</div>
