<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    error.phtml
// Created: 2016-12-11 18:13:16
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 
//
// View layout for displaying an error message.
// 

?>

<div style="<?= $style ?>">
    <?= $this->getContent() ?>
    <span id="notice" style="display: none"></span>
</div>
