<?php

use Phalcon\Mvc\User\Component;
use Phalcon\Tag;

// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    main.phtml
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// Author:  Ahsan Shahzad (MedfarmDoIT)
// 

?>

<?php
// 
// Add profiling check point:
// 
$this->profiler->add("view");

?>

<!-- CSS -->
<?= Tag::stylesheetLink('bootstrap3/css/bootstrap.min.css'); ?>
<?= Tag::stylesheetLink('bootstrap3/css/bootstrap-theme.min.css'); ?>
<?= Tag::stylesheetLink('bootstrap3/css/bootstrap-datetimepicker.min.css'); ?>

<?= Tag::stylesheetLink('plugins/jquery-ui/jquery-ui.min.css'); ?>

<?= Tag::stylesheetLink("css/standard.css"); ?>
<?= Tag::stylesheetLink("css/accordion.css"); ?>

<?= Tag::stylesheetLink("css/font-awesome.min.css"); ?>
<?= Tag::stylesheetLink("plugins/fancybox-master/dist/jquery.fancybox.min.css"); ?>

<!-- Javascript -->
<?= Tag::javascriptInclude('js/moment.min.js'); ?>
<?= Tag::javascriptInclude('bootstrap3/js/bootstrap.min.js'); ?>
<?= Tag::javascriptInclude('bootstrap3/js/bootstrap-datetimepicker.min.js'); ?>
<?= Tag::javascriptInclude('plugins/fancybox-master/dist/jquery.fancybox.min.js'); ?>

<?= Tag::javascriptInclude('plugins/jquery-ui/jquery-ui.min.js'); ?>

<?php

class NavigateMenuActivator extends Component
{

        private $_crtl;
        private $_user;

        public function __construct($ctrl, $user)
        {
                $this->_crtl = $ctrl;
                $this->_user = $user;
        }

        public function active($ctrl, $public = true)
        {
                $result = "visible";

                if (is_array($ctrl) && in_array($this->_crtl, $ctrl)) {
                        $result = "active";
                } elseif ($ctrl == $this->_crtl) {
                        $result = "active";
                }
                if ($public == false && is_null($this->_user)) {
                        $result = false;
                }

                return $result;
        }

}

$ctrl = $this->dispatcher->getControllerName();
$user = $this->user->getUser();

$link = new NavigateMenuActivator($ctrl, $user);

if ($theme == 'high-contrast') {
        $theme_high_contrast = "active";
} else {
        $theme_high_contrast = "";
}

?>

<!-- Header area -->
<div id="oe-header"> 

    <!-- Top navigation -->
    <div class="component"> 

        <!-- Logo -->
        <div class="top-image">
            <h1 class="logo"> <a href="<?= $this->config->brand->logo->link ?>">
                    <?= Tag::image(array($this->config->brand->logo->file, "style" => $this->config->brand->logo->style)); ?>
                </a> <span class="alt-logo"><?= $this->config->brand->logo->link ?></span> </h1>
        </div>

        <!-- Logo Text -->
        <div class="top-site hidden-xs">
            <h1 class="site-name"> <a href="http://openexam.io">OpenExam</a><span class="hidden-sm"> - online examination system</span></h1>
        </div>

        <!-- User control -->
        <div style="position: absolute; top: 10px; right: 25px">
            <?php if ($this->user->roles->isAdmin() == false) : ?>
                    <span class="btn btn-default">
                        <i class="fa fa-user"></i> <?= $this->catalog->getName() ?>
                    </span>
            <?php else : ?>
                    <span class="btn btn-default" style="color: #c1002b;">
                        <i class="fa fa-user"></i> <?= $this->catalog->getName() ?>
                    </span>
            <?php endif; ?>
        </div>
    </div>

    <!-- Top menu -->
    <div id="oe-top-menu"> 
        <nav class="navbar navbar-inverse" style="z-index: 1">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>                        
                    </button>
                    <a class="navbar-brand hidden-sm hidden-md hidden-lg" href="<?= $this->url->get() ?>">OpenExam</a>  
                </div>

                <div class="collapse navbar-collapse" id="myNavbar">
                    <!-- Left side menu items -->
                    <ul class="nav navbar-nav">
                        <!-- Home -->
                        <?php if (($active = $link->active("index"))) : ?>
                                <li class="<?= $active ?>">
                                    <?= Tag::linkTo('', 'Home') ?>
                                </li>
                        <?php endif; ?>

                        <!-- My Exams -->
                        <?php if (($active = $link->active("exam", false))) : ?>
                                <li class="<?= $active ?>">
                                    <?= Tag::linkTo('exam/index', 'My Exams') ?>
                                </li>
                        <?php endif; ?>
                    </ul>

                    <!-- Right side menu items -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Tasks -->
                        <?php if (($active = $link->active("task", false))) : ?>
                                <li class="dropdown <?= $active ?>">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Task
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <?php if ($this->user->roles->hasRole('teacher')) : ?>
                                                <li>
                                                    <?= Tag::linkTo('exam/create', 'Create Exam...') ?>
                                                </li>
                                        <?php endif; ?>
                                        <?php if ($this->user->roles->hasRole('contributor')) : ?>
                                                <li>
                                                    <?= Tag::linkTo('task/contribute', 'Contribute Questions') ?>
                                                </li>
                                        <?php endif; ?>
                                        <?php if ($this->user->roles->hasRole('corrector')) : ?>
                                                <li>
                                                    <?= Tag::linkTo('task/correct', 'Correct Answers') ?>
                                                </li>
                                        <?php endif; ?>
                                        <?php if ($this->user->roles->hasRole('invigilator')) : ?>
                                                <li>
                                                    <?= Tag::linkTo('task/invigilate', 'Invigilate Exam') ?>
                                                </li>
                                        <?php endif; ?>
                                        <?php if ($this->user->roles->hasRole('decoder')) : ?>
                                                <li>
                                                    <?= Tag::linkTo('task/decode', 'Decode Exam') ?>
                                                </li>
                                        <?php endif; ?>
                                        <?php if ($this->user->roles->hasRole('student')) : ?>
                                                <li>
                                                    <?= Tag::linkTo('task/result', 'Download Results') ?>
                                                </li>
                                        <?php endif; ?>
                                    </ul>
                                </li>
                        <?php endif; ?>

                        <!-- Tools -->
                        <?php if (($active = $link->active(array("monitor", "statistics"), false))) : ?>
                                <li class="dropdown <?= $active ?>">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Tools
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <?= Tag::linkTo('utility/statistics', 'Statistics') ?>
                                        </li>
                                        <li>
                                            <?= Tag::linkTo('utility/monitor/diagnostics', 'Diagnostics') ?>
                                        </li>
                                        <li role="separator" class="divider"></li>
                                        <li class="<?= $theme_high_contrast ?>">
                                            <a href="#" id="theme-high-contrast">
                                                <i class="fa fa-adjust" aria-hidden="true"></i>
                                                High Contrast
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                        <?php endif; ?>

                        <!-- Help -->
                        <?php if (($active = $link->active("help"))) : ?>
                                <li class="dropdown <?= $active ?>">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Help
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <?= Tag::linkTo('help/manual/teacher', 'Teacher Manual') ?>
                                        </li>
                                        <li>
                                            <?= Tag::linkTo('help/manual/student', 'Student Manual') ?>
                                        </li>
                                        <li>
                                            <?= Tag::linkTo(array('help/manual', 'Show All...', 'target' => '_blank', 'title' => 'Open page with manuals in other languages and formats in new window.')) ?>
                                        </li>
                                        <li>
                                            <?= Tag::linkTo('about', 'About') ?>
                                        </li>
                                    </ul>
                                </li>
                        <?php endif; ?>

                        <!-- Logon -->
                        <?php if (($active = $link->active("auth"))) : ?>
                                <?php if ($this->user->getUser()) : ?>
                                        <li>
                                            <?= Tag::linkTo('auth/logout', '<i class="fa fa-unlock-alt"></i> Logout') ?>
                                        </li>
                                <?php else : ?>
                                        <li class="dropdown <?= $active ?>">
                                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Login
                                                <span class="caret"></span>
                                            </a>
                                            <ul class="dropdown-menu"><?php
                                                foreach ($authenticators as $name => $auth) {
                                                        if ($auth->visible) {
                                                                print Tag::tagHtml("li");
                                                                print Tag::linkTo(array(
                                                                            sprintf("auth/login/%s", $name),
                                                                            sprintf("<i class=\"fa\"></i> %s", $auth['desc'])
                                                                ));
                                                                print Tag::tagHtmlClose("li");
                                                        }
                                                }

                                                ?></ul>
                                        </li>
                                <?php endif; ?>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>            
    </div>
</div>

<!-- Content area -->
<div id="oe-container">
    <div id="ajax-message" class="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <p id="ajax-message-content"></p>
    </div>
    <?= $this->getContent() ?>
</div>

<!-- Footer area -->
<div id="oe-footer">
    <div class="footer-text">
        <div class="sidfot vcard" style="width: auto;"> &copy; 2010-<?= date('Y') ?> <a class="url fn org" href="http://www.uu.se/">Uppsala University</a> <a class="url fn org" href="http://www.bmc.uu.se/">BMC</a> </div>
    </div>
</div>
