    <!-- / bootstrap -->
    <?=Phalcon\Tag::stylesheetLink('thin-layout/stylesheets/bootstrap/bootstrap.css');?>
    <!-- / theme file -->
    <?=Phalcon\Tag::stylesheetLink(array('thin-layout/stylesheets/light-theme.css', "media"=>"all", "id"=>"color-settings-body-color"));?>
    <!-- / coloring file 
    <?php //Phalcon\Tag::stylesheetLink(array('thin-layout/stylesheets/theme-colors.css', "media"=>"all", "rel"=>"stylesheet"));?>-->
    <?=Phalcon\Tag::stylesheetLink('thin-layout/stylesheets/text-zoom.css');?>
    <?=Phalcon\Tag::stylesheetLink("plugins/fancy-box/source/jquery.fancybox.css");?>        
    
    <!--[if lt IE 9]>
      <?php //Phalcon\Tag::javascriptInclude('thin-layout/javascripts/ie/html5shiv.js');?>	
      <?php //Phalcon\Tag::javascriptInclude('thin-layout/javascripts/ie/respond.min.js');?>	
    <![endif]-->

    <!-- / jquery -->
    <?=Phalcon\Tag::javascriptInclude('thin-layout/javascripts/jquery/jquery.min.js');?>	
    <!-- / jquery mobile (for touch events) -->
    <?php //Phalcon\Tag::javascriptInclude('thin-layout/javascripts/jquery/jquery.mobile.custom.min.js');?>	
    <!-- / jquery migrate (for compatibility with new jquery) [required] -->
    <?=Phalcon\Tag::javascriptInclude('thin-layout/javascripts/jquery/jquery-migrate.min.js');?>	
    <!-- / jquery ui -->
    <?php //Phalcon\Tag::javascriptInclude('thin-layout/javascripts/jquery/jquery-ui.min.js');?>
    <!-- / jQuery UI Touch Punch -->
    <?php //Phalcon\Tag::javascriptInclude('thin-layout/javascripts/plugins/jquery_ui_touch_punch/jquery.ui.touch-punch.min.js');?>
    <!-- / bootstrap  -->
    <?=Phalcon\Tag::javascriptInclude('thin-layout/javascripts/bootstrap/bootstrap.js');?>
    <!-- / modernizr -->
    <?php //Phalcon\Tag::javascriptInclude('thin-layout/javascripts/plugins/modernizr/modernizr.min.js');?>    
    <!-- / retina -->
    <?php //Phalcon\Tag::javascriptInclude('thin-layout/javascripts/plugins/retina/retina.js');?>    
    <!-- / theme file  -->
    <?=Phalcon\Tag::javascriptInclude('thin-layout/javascripts/theme.js');?>  
    <?=Phalcon\Tag::javascriptInclude('thin-layout/javascripts/zoom.min.js');?>
    <!-- fancy box -->
    <?=Phalcon\Tag::javascriptInclude('plugins/fancy-box/source/jquery.fancybox.js');?>            
    
    
    <?php
	$start 	= date_create(strtotime($exam->starttime) > strtotime("now") ? $exam->starttime : "now");
	$end 	= date_create($exam->endtime);
	
	$timeLeft = $start->diff($end);
	$secDiff = (int)$end->format('U') - (int)$start->format('U');
	
	$answerData = json_decode($answer->answer, true); //highlight-q
    ?>

    <header>
      <nav class='navbar navbar-default navbar-fixed-top'>
        <a class='navbar-brand' href='<?=$this->url->get('exam/'.$exam->id)?>'>
          <?= Phalcon\Tag::image("thin-layout/images/logo.png"); ?>
        </a>
        <a class='toggle-nav btn pull-left' href='#'>
          <i class='icon-reorder'></i>
        </a>
        <ul class='nav'>
<li class='dropdown light only-icon'>
            <a class='dropdown-toggle' data-toggle='dropdown' href='#'>
              <i class='icon-cog'></i>
            </a>
            <ul class='dropdown-menu color-settings' style="font-size:12px">
              <li class='color-settings-body-color'>
                <div class='color-title' style="font-weight: bold; color:#DB4741; text-align:center"> Change Font style</div>
                <div class="box">
                    <div class="zoom" id="demo"></div>
                </div>
                <br style="clear:both" />
              </li>
            </ul>
          </li>        
          
	  <li class="dropdown dark user-menu">
            <a class='dropdown-toggle' data-toggle='dropdown' href="#">
              <span class="user-name">Catharina Svensson &nbsp;<span style="color:#f9c271">19860704-1234</span><!--#FFFF66--></span>
              <b class='caret'></b>
            </a>
	    <ul class='dropdown-menu' style="width:275px">
              <!--<li class='divider'></li>-->
              <li>
                <a href='<?=$this->url->get('auth/logout')?>'>
                  <i class='icon-signout'></i>
                  Sign out
                </a>
              </li>
            </ul>
          </li>
        </ul>
        
        <div style="float:right; padding:5px 1%; font-size:20px; color:#F9C271; background-color:#F34541"><!--#F8A325-->
          <i class="icon-time"></i>
          <span style="margin-top:25px" id="timer">
	  	<?=$timeLeft->format('%H:%I:%S')?>
          </span>
        </div>        
      </nav>
    </header>
    <!-- page header ends -->

    
    <!-- page wrapper -->
    <?php $allQs = $exam->getQuestions();?>
    <div id='wrapper'>
      <?php if(isset($viewMode)):?>
      <div id='main-nav-bg'></div>
      <!-- main navigation -->
      <nav id='main-nav' class='<?=is_object($allQs) && $allQs->count() <= 10 ? 'main-nav-fixed' : ''?>'> <!--class='main-nav-fixed'-->
        <div class='navigation'>
          <ul class='nav nav-stacked'>
                    <li class=''>
                              <a href='#exam-instructions' class="fancybox">
                                <div style="float:left; width:20%"><i class='icon-book'></i></div>
                                <div style="float:left; width:80%"><span>Exam Instructions</span></div>
                              </a>
                    </li>
        	    <?php foreach($allQs as $question):?>
                    <?php $questionData = json_decode($question->quest);?>

                    <li class='<?=($viewMode == 'single' && $question->name == $quest[0]->name ? 'active' : '')?>' id="q<?=$question->name?>_short">
                              <a href="<?=$this->url->get('exam/'.$exam->id.'/question/'.$question->name)?>" style=" <?=(in_array($question->id, $highlightedQs) === TRUE ? 'background-color: #FEFF99;':'')?>"><!--#FBC676-->
                                      <div style="float:left; width:20%"><i class="icon-q<?=$question->name?>" ></i></div>
                                      <div style="float:left; width:80%; max-height:30px"><span><?=substr(strip_tags($questionData->a->q_text), 0, 65)?></span></div>
                              </a>
                    </li>
                    <?php endforeach;?>
                    <li class='<?=($viewMode == 'all' ? 'active' : '')?>'>
                              <a href='<?=$this->url->get('exam/'.$exam->id.'/question/all')?>'>
                                <div style="float:left; width:20%"><i class='icon-list'></i></div>
                                <div style="float:left; width:80%"><span>Preview your answers</span></div>
                              </a>
                    </li>
          </ul>
        </div>
      </nav>
      <?php endif;?>
      <!-- main navigation ends -->
      
      <!-- main content area -->
      <section id='content'>
        <div class='container'>
          <div class='row' id='content-wrapper'>
          	<?=$this->getContent()?>  
          </div>
          
          <!-- Footer area -->
          <footer id='footer'>
            <div class='footer-wrapper'>
              <div class='row'>
                <div class='col-sm-6 text'>
                  Copyright &copy; 2014 Uppsala Universitet
                </div>
              </div>
            </div>
          </footer>
          <!-- Footer area ends -->
          
        </div>
      </section>
      <!-- main content area ends -->
      
    </div>
    
    <!-- wrapper ends -->
    <script type="text/javascript">
	$("document").ready(function(){
		$("#demo").zoom({
			    path: "#content-wrapper"
			    //show/hide				
			    , show_zoom: true //font-size
			    , show_alignment: false //text-align
			    , show_font_family: false //font-family
			    , show_bold: true //font-weight
			    , show_colors: true //color
			    , show_reset: true //reset
		
			     //default properties
			    , font_size: "14"
			    , font_family: "Arial"
			    , font_weight: "normal"
			    , line_height_step: 3
			    , text_align: "left"
			    , color: "#333333"
			    , cookies: true
			    , expiration: -1 //cookies expiration in days (-1 = cookies expire when browser is closed)
			    , colors: ["#333333", "#000000", "#006300", "#774500", "#2918C9", "#4F2C7A", "#518E2D", "#96122C"]
		});

		$(document).on('click', '.fullscreen', function() {
			var docElm = document.getElementById($(this).attr('isfor'));
			if (docElm.requestFullscreen) {
			    docElm.requestFullscreen();
			}
			else if (docElm.msRequestFullscreen) {
			    docElm.msRequestFullscreen();
			}
			else if (docElm.mozRequestFullScreen) {
			    docElm.mozRequestFullScreen();
			}
			else if (docElm.webkitRequestFullScreen) {
			    docElm.webkitRequestFullScreen();
			}
		});
	});
	    
	/*----------------------------------------------------------*/ 
	/*	Count down timer related functions for exam	    */
	/*----------------------------------------------------------*/
	
	<?php if(strtotime($exam->starttime) <= strtotime("now")):?>
	var count 	= <?=$secDiff?>;
	var counter	= setInterval(timer, 1000); 
	<?php endif;?>
	
	function timer () {
		count=count-1;
		if (count <= 0)
		{
			syncAnswers(true);
			alert("Exam time has been finished");
			clearInterval(counter);
			return;
		}
		$("#timer").html(toHHMMSS(count));
	}
	function toHHMMSS (sec) {
		var sec_num = parseInt(sec, 10);
		var hours   = Math.floor(sec_num / 3600);
		var minutes = Math.floor((sec_num - (hours * 3600)) / 60);
		var seconds = sec_num - (hours * 3600) - (minutes * 60);
	
		if (hours   < 10) {hours   = "0"+hours;}
		if (minutes < 10) {minutes = "0"+minutes;}
		if (seconds < 10) {seconds = "0"+seconds;}
		var time    = hours+':'+minutes+':'+seconds;
		return time;
	}
	
    </script>
