<!-- / bootstrap -->
<?= Phalcon\Tag::stylesheetLink('thin-layout/stylesheets/bootstrap/bootstrap.css'); ?>

<!-- / theme file -->
<?= Phalcon\Tag::stylesheetLink(array('thin-layout/stylesheets/light-theme.css', "media" => "all", "id" => "color-settings-body-color")); ?>
<?= Phalcon\Tag::stylesheetLink('thin-layout/stylesheets/text-zoom.css'); ?>
<?= Phalcon\Tag::stylesheetLink("plugins/fancy-box/source/jquery.fancybox.css"); ?>        

<!-- / jquery -->
<?= Phalcon\Tag::javascriptInclude('thin-layout/javascripts/jquery/jquery.min.js'); ?>	

<!-- / jquery migrate (for compatibility with new jquery) [required] -->
<?= Phalcon\Tag::javascriptInclude('thin-layout/javascripts/jquery/jquery-migrate.min.js'); ?>
<?= Phalcon\Tag::javascriptInclude('js/jquery.cookie.js'); ?>

<!-- / bootstrap  -->
<?= Phalcon\Tag::javascriptInclude('thin-layout/javascripts/bootstrap/bootstrap.js'); ?>

<!-- / theme file  -->
<?= Phalcon\Tag::javascriptInclude('thin-layout/javascripts/theme.js'); ?>  
<?= Phalcon\Tag::javascriptInclude('thin-layout/javascripts/zoom.min.js'); ?>

<!-- fancy box -->
<?= Phalcon\Tag::javascriptInclude('plugins/fancy-box/source/jquery.fancybox.js'); ?>            

<!-- Video.js - HTML5 video with flowplayer dropin -->
<?= Phalcon\Tag::javascriptInclude('js/video.min.js'); ?>
<?= Phalcon\Tag::stylesheetLink('css/video-js.min.css'); ?>

<?php
$answerData = json_decode($answer->answer, true); // highlight-q
$testMode = $exam->creator == $this->user->getPrincipalName();

if (isset($exam->starttime) && isset($exam->endtime)) {
        $stime = strtotime($exam->starttime);
        $etime = strtotime($exam->endtime);
        $tdiff = $etime - $stime;
        $count = false;
}
if (time() > $stime) {
        $tdiff = $etime - time();
        $count = true;
}
if ($testMode) {
        $tdiff = 0;
        $count = false;
}
$tt = (object) array(
            'dd' => floor(($tdiff / (3600 * 24))),
            'hh' => floor(($tdiff / 3600) % 24),
            'mm' => floor((($tdiff % 3600) / 60)),
            'ss' => floor($tdiff % 60)
);
if ($tt->dd != 0) {
        $tdisp = sprintf("%02d:%02d:%02d (+%d days)", $tt->hh, $tt->mm, $tt->ss, $tt->dd);
} else {
        $tdisp = sprintf("%02d:%02d:%02d", $tt->hh, $tt->mm, $tt->ss);
}

?>

<header>
    <nav class='navbar navbar-default navbar-fixed-top'>
        <a class='navbar-brand' href='<?= $this->url->get('exam/index') ?>'>
            <?= Phalcon\Tag::image("thin-layout/images/logo.png"); ?>
        </a>
        <a class='toggle-nav btn pull-left' href='#'>
            <i class='icon-reorder'></i>
        </a>
        <?php if ($testMode): ?>
                <a href="<?= $this->url->get('exam/index') ?>" class="toggle-nav btn url">
                    <i class="icon-ok-circle" style="color:#F4E374"> 
                        <span style='color:#fff; font-family:"open sans","Lucida Grande",Lucida,Verdana,Helvetica,sans-serif'>Finish Test mode and return back</span>
                    </i>
                </a>
        <?php endif; ?>

        <ul class='nav'>
            <li class='dropdown light only-icon'>
                <a class='dropdown-toggle' data-toggle='dropdown' href='#'>
                    <i class='icon-cog'></i>
                </a>
                <ul class='dropdown-menu color-settings' style="font-size:12px">
                    <li class='color-settings-body-color'>
                        <div class='color-title' style="font-weight: bold; color:#DB4741; text-align:center"> Change Font style</div>
                        <div class="box">
                            <div class="zoom" id="demo"></div>
                        </div>
                        <br style="clear:both" />
                    </li>
                </ul>
            </li>        

            <li class="dropdown dark user-menu">
                <a class='dropdown-toggle' data-toggle='dropdown' href="#">
                    <span class="user-name"><?= $this->helper->getCatalogAttribute($this->user->getPrincipalName(), 'name') ?> &nbsp;
                        <span style="color:#f9c271"><?= $this->helper->getCatalogAttribute($this->user->getPrincipalName(), 'pnr') ?></span><!--#FFFF66--></span>
                    <b class='caret'></b>
                </a>
                <ul class='dropdown-menu' style="width:275px">
                    <!--<li class='divider'></li>-->
                    <li>
                        <a href='<?= $this->url->get('auth/logout') ?>'>
                            <i class='icon-signout'></i>
                            Sign out
                        </a>
                    </li>
                </ul>
            </li>
        </ul>

        <div style="float:right; padding:5px 1%; font-size:20px; color:#F9C271; background-color:#BE2435"><!--#F8A325-->
            <i class="icon-time"></i>
            <span style="margin-top:25px" id="timer"><?= $tdisp ?></span>
        </div>        
    </nav>
</header>
<!-- page header ends -->

<!-- page wrapper -->
<?php $allQs = $exam->getQuestions(array("order" => "slot")); ?>
<div id='wrapper'>
    <?php if (isset($viewMode)): ?>
            <div id='main-nav-bg'></div>
            <!-- main navigation -->
            <nav id='main-nav' class='<?= is_object($allQs) && $allQs->count() <= 8 ? 'main-nav-fixed' : '' ?>'> <!--class='main-nav-fixed'-->
                <div class='navigation'>
                    <ul class='nav nav-stacked'>
                        <li class=''>
                            <a href='#general-instructions' class="fancybox">
                                <div style="float:left; width:20%"><i class='icon-book'></i></div>
                                <div style="float:left; width:80%"><span>General instructions</span></div>
                            </a>
                        </li>
                        <li class=''>
                            <a href='#exam-instructions' class="fancybox">
                                <div style="float:left; width:20%"><i class='icon-book'></i></div>
                                <div style="float:left; width:80%"><span>Exam specific instructions</span></div>
                            </a>
                        </li>
                        <li class='<?= ($viewMode == 'all' ? 'active' : '') ?>'>
                            <a class="sync-answer" href="#" hlink="<?= $this->url->get('exam/' . $exam->id . '/question/all') ?>">
                                <div style="float:left; width:20%"><i class='icon-signout'></i></div>
                                <div style="float:left; width:80%"><span>Preview your answers and Quit</span></div>
                            </a>
                        </li>
                        <?php foreach ($allQs as $qNo => $question): ?>
                                <?php $questionData = json_decode($question->quest); ?>

                                <li class='<?= ($viewMode == 'single' && $question->id == $quest[0]->id ? 'active' : '') ?>' id="q<?= $qNo + 1 ?>_short">
                                    <a class="sync-answer" href="#" hlink="<?= $this->url->get('exam/' . $exam->id . '/question/' . $question->id) ?>" style=" <?= (in_array($question->id, $highlightedQs) === TRUE ? 'background-color: #FEFF99;' : '') ?>"><!--#FBC676-->
                                        <div style="float:left; width:20%"><i class="icon-q<?= $qNo + 1 ?>" ></i></div>
                                        <div style="float:left; width:80%; max-height:27px"><span><?= substr(strip_tags($questionData->a->q_text), 0, 58) ?></span></div>
                                    </a>
                                </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </nav>
    <?php endif; ?>
    <!-- main navigation ends -->

    <!-- main content area -->
    <section id='content'>
        <div class='container'>
            <div class='row' id='content-wrapper'>
                <?= $this->getContent() ?>  
            </div>

            <!-- Footer area -->
            <footer id='footer'>
                <div class='footer-wrapper'>
                    <div class='row'>
                        <div class='col-sm-6 text'>
                            Copyright &copy; 2010-<?= date('Y') ?> Uppsala University
                        </div>
                    </div>
                </div>
            </footer>
            <!-- Footer area ends -->

        </div>
    </section>
    <!-- main content area ends -->

</div>

<!-- wrapper ends -->
<script type="text/javascript">
        $("document").ready(function () {
            $("#demo").zoom({
                path: "#content-wrapper"
                        //show/hide				
                , show_zoom: true //font-size
                , show_alignment: false //text-align
                , show_font_family: false //font-family
                , show_bold: true //font-weight
                , show_colors: true //color
                , show_reset: true //reset

                        //default properties
                , font_size: "14"
                , font_family: "Arial"
                , font_weight: "normal"
                , line_height_step: 3
                , text_align: "left"
                , color: "#333333"
                , cookies: true
                , expiration: -1 //cookies expiration in days (-1 = cookies expire when browser is closed)
                , colors: ["#333333", "#000000", "#006300", "#774500", "#2918C9", "#4F2C7A", "#518E2D", "#96122C"]
            });

            $(document).on('click', '.fullscreen', function () {
                var docElm = document.getElementById($(this).attr('isfor'));
                if (docElm.requestFullscreen) {
                    docElm.requestFullscreen();
                }
                else if (docElm.msRequestFullscreen) {
                    docElm.msRequestFullscreen();
                }
                else if (docElm.mozRequestFullScreen) {
                    docElm.mozRequestFullScreen();
                }
                else if (docElm.webkitRequestFullScreen) {
                    docElm.webkitRequestFullScreen();
                }
            });
        });

        // 
        // Count down timer related functions for exam:
        // 
<?php if (!$testMode): ?>
                var tdiff = <?= $tdiff ?>;
                var stime = <?= $stime ?>;
                var etime = <?= $etime ?>;

                timer();        // Single shot for setting clock

        <?php if ($count): ?>
                        var counter = setInterval(timer, 1000);
        <?php endif; ?>

                function timer() {
                    if (tdiff < 0)
                    {
                        syncAnswers(true, '<?= $this->url->get('exam/index'); ?>');
                        alert("The exam time is up. Please logout and close the browser. We wish you good luck!");
                        clearInterval(counter);
                        return;
                    } else if (tdiff == 300) {
                        alert("Remaining time for this exam is 5 minutes.");
                        tdiff = etime - Math.round(+new Date() / 1000);         // Needs reschedule
                    }
                    $("#timer").html(toHHMMSS(tdiff--));
                }

                function toHHMMSS(tsec) {
                    var tt = {
                        dd: Math.floor((tsec / (3600 * 24))),
                        hh: Math.floor((tsec / 3600) % 24),
                        mm: Math.floor((tsec % 3600) / 60),
                        ss: Math.floor((tsec % 60))
                    };

                    if (tt.hh < 10) {
                        tt.hh = "0" + tt.hh;
                    }
                    if (tt.mm < 10) {
                        tt.mm = "0" + tt.mm;
                    }
                    if (tt.ss < 10) {
                        tt.ss = "0" + tt.ss;
                    }

                    var time = tt.hh + ':' + tt.mm + ':' + tt.ss;

                    if (tt.dd > 0) {
                        time += ' (+' + tt.dd + ' days)';
                    }

                    return time;
                }
<?php endif; ?>
</script>
