<?php

// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    library.phtml
// 
// Author:  Ahsan Shahzad (Medfarm DoIT)
// Author:  Anders Lövgren (QNET)
// 

use Phalcon\Tag;

function set_resource_defaults($type, $resource, $url)
{
        if ($type == 'image') {
                $resource->img = $url->get($resource->path);
        } else {
                $resource->img = $url->get('img/file-icon.png');
        }
        if (!isset($resource->name)) {
                $resource->name = basename($resource->path);
        }
}

?>

<?= Tag::stylesheetLink('plugins/jquery-file-upload/css/jquery.fileupload.css'); ?>
<?= Tag::javascriptInclude('plugins/jquery-file-upload/js/jquery.fileupload.js'); ?>
<?= Tag::javascriptInclude('js/views/media/library.js?rev=1'); ?>

<style>
    .lib-item {
        display: inline-block;
        height: 120px;
        width: 100px;
        margin: 0 5px 10px 0;
        border: 3px solid black;
        border-radius: 5px;
        background-color: black;
        color: white;
        box-shadow: 2px 3px 10px 1px #bbc;
        overflow: hidden;
    }
    .lib-item .image {
        height: 75px;
    }
    .lib-item .text {
        text-align: center;
    }
    .lib-item .tools {
        padding: 0 5px 0 5px;
    }
    .lib-item .tools .left {
        display: inline-block;
    }
    .lib-item .tools .right {
        display: inline-block;
        float: right;
    }

    a.lib-item-edit,
    a.lib-item-del,
    a.lib-item-share
    {
        color: #666666;
    }
    a.lib-item-edit:hover {
        color: deepskyblue;
    }
    a.lib-item-del:hover {
        color: orangered;
    }
    a.lib-item-share:hover {
        color: greenyellow;
    }

    .lib-item.selected {
        filter: grayscale(100) invert(100);
    }
    .lib-item.appended {
        width: 100%;
        height: 100%;        
    }
    .lib-item.expanded {
        width: 100%;
        height: 100%;        
    }
    .lib-item.expanded .image,
    .lib-item.appended .image {
        height: 100%;
    }

    .lib-item-display {
        float: right;
        margin: 8px;
        top: 0;
        right: 0;
        position: absolute;
    }
    .lib-item-display a {
        color: #c1002b;
        text-decoration: none;
    }

    .lib-resource-image {
        height: 100%;
        width: 100%;
    }

    .fileinput-button {
        height: 100%;
        width: 100%;
    }

    #lib-selected-list {
        margin-top: 10px;
    }
    #lib-default-msg,
    .lib-missing-msg {
        color: lightsteelblue;
        text-align: center;
    }

    #fileupload {
        margin: 0;
        padding: 0;
        height: 100%;
        width: 100%;
    }
</style>

<div class="alert alert-info alert-dismissable">
    <a class='close' data-dismiss='alert' href='#'>&times;</a>
    Select resource files from the media library containing your personal files from previous uploads or files shared by other people. 
    You can choose to share your personal files with others if you like or keep them private.
</div>

<div id="lib-item-edit" style="display: none;">
    <span id="lib-item-title"></span>
    <div class="lib-item-save" id="lib-item-name" style="display: none">
        <label>
            Resource name
            <input type="text" class="form-control update-lib-item-name" value="">
        </label>
    </div>
    <div class="lib-item-save" id="lib-item-share" style="display: none">
        <label>
            This resource can be used                
            <select class="form-control update-lib-item-shared">
                <option value="private">Only by me</option>
                <option value="exam">By co-workers on this exam</option>
                <option value="group">For anyone in my department or group</option>
                <option value="global">By everyone else</option>
            </select>
        </label>
    </div>
    <br>
    <span class="btn btn-success update-lib-item-details" media-id=""> Save</span>
</div>

<!-- Template for library item -->
<div id="lib-item-template">
    <div class="lib-item" media-id="" style="display:none"> 
        <div class="image">
            <a class="select-resource" href="#"> 
                <img src="" class="lib-resource-image"> 
            </a>
        </div>
        <div class="tools">
            <div class="left">
                <a href="#" class="lib-item-edit">
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                </a>
                <a href="#" class="lib-item-del">
                    <i class="fa fa-times" aria-hidden="true"></i>
                </a>
            </div>
            <div class="right">
                <a href="#" class="lib-item-share" item-share="exam">
                    <i class="fa fa-share-alt" aria-hidden="true"></i>
                </a>
            </div>
        </div>
        <div class="text"></div>
    </div>
</div>

<!-- The media library -->
<div class="row">

    <div class="col-sm-9" id="lib-items-available">
        <div class="lib-header">
            <h3>Media library</h3>
        </div>

        <div id="media-types">
            <ul>
                <?php foreach (array_keys($sres) as $type): ?>
                        <li><a href="#<?= $type ?>-tab"><?= ucfirst($type) ?></a></li>
                <?php endforeach; ?>
            </ul>

            <div class="lib-item-display">
                <a href="#" id="lib-item-personal" title="Show personal files">
                    <i class="fa fa-2x fa-user" aria-hidden="true"></i>
                </a>
                <a href="#" id="lib-item-expand" title="Expand current display">
                    <i class="fa fa-2x fa-arrows-alt" aria-hidden="true"></i>
                </a>
            </div>

            <?php foreach (array_keys($sres) as $type): ?>
                    <div id="<?= $type ?>-tab">

                        <!-- Shared resources -->
                        <div class="lib-tab-area">
                            <?php if (!count($sres[$type])): ?>
                                    <div class="lib-missing-msg">No shared <?= $type ?> resources was found. </div>
                            <?php endif; ?>

                            <?php foreach ($sres[$type] as $resource): ?>
                                    <?php set_resource_defaults($type, $resource, $this->url) ?>

                                    <div class="lib-item" media-id="<?= $resource->id ?>"> 
                                        <div class="image">
                                            <a class="select-resource" href="<?= $resource->path ?>"> 
                                                <img src="<?= $resource->img ?>" class="lib-resource-image"> 
                                            </a>
                                        </div>
                                        <div class="tools">
                                            <div class="left">
                                                <a href="#" class="lib-item-edit">
                                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                                </a>
                                                <a href="#" class="lib-item-del">
                                                    <i class="fa fa-times" aria-hidden="true"></i>
                                                </a>
                                            </div>
                                            <div class="right">
                                                <a href="#" class="lib-item-share" item-share="<?= $resource->shared ?>" personal="false">
                                                    <i class="fa fa-share-alt" aria-hidden="true"></i>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="text">
                                            <?= $resource->name ?>
                                        </div>
                                    </div>
                            <?php endforeach; ?>
                        </div>

                        <!-- Personal resources -->
                        <div class="lib-tab-area lib-personal" id="lib-personal-<?= $type ?>" style="display:none">
                            <h4>Personal files:</h4>
                            <?php if (!count($pres[$type])) : ?>
                                    <div class="lib-missing-msg">No personal <?= $type ?> resources was found. </div>
                            <?php endif; ?>

                            <?php foreach ($pres[$type] as $resource): ?>
                                    <?php set_resource_defaults($type, $resource, $this->url) ?>

                                    <div class="lib-item" media-id="<?= $resource->id ?>"> 
                                        <div class="image">
                                            <a class="select-resource" href="<?= $resource->path ?>"> 
                                                <img src="<?= $resource->img ?>" class="lib-resource-image"> 
                                            </a>
                                        </div>
                                        <div class="tools">
                                            <div class="left">
                                                <a href="#" class="lib-item-edit">
                                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                                </a>
                                                <a href="#" class="lib-item-del">
                                                    <i class="fa fa-times" aria-hidden="true"></i>
                                                </a>
                                            </div>
                                            <div class="right">
                                                <a href="#" class="lib-item-share" item-share="<?= $resource->shared ?>" personal="true">
                                                    <i class="fa fa-share-alt" aria-hidden="true"></i>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="text">
                                            <?= $resource->name ?>
                                        </div>
                                    </div>
                            <?php endforeach; ?>
                        </div>

                    </div>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="col-sm-3" id="lib-items-selected">
        <div class="lib-header">
            <h3>Selected files</h3>
        </div>

        <div class="btn btn-success fileinput-button">
            <i class="fa fa-plus-square fa-2x"></i>
            <span style="white-space: normal"><p>Drag and drop or click to upload files from your computer</p></span> 
            <!-- The file input field used as target for the file upload widget -->
            <input class="form-control" type="file" multiple="" name="files[]" id="fileupload">
        </div> 

        <div id="lib-selected-list">
            <div id="lib-default-msg">
                <div> No files have been uploaded or selected yet. </div>
            </div>
        </div>

    </div>
</div>

<script language="javascript">
        var user = '<?= $this->user->getPrincipalName() ?>';
</script>
