<?php
/*
 * Copyright (C) 2016-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    diagnostics.phtml
// Created: 2016-06-06 23:04:34
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<style>
    div #summary {
        display: none;
    }
    div #details {
        margin-top: 20px;
    }
    .hide {
        display: none!important;
    }
    div.status {
        padding: 20px;
        margin-bottom: 10px;
        max-width: 400px;
        font-size: 1.2em;
        border-radius: 5px;
    }
    div #status-success {
        display: none;
        background-color: #eeffdd;
        border: 1px solid greenyellow;
    }
    div #status-failure {
        display: none;
        background-color: #fffedd;
        border: 1px dashed #ff9d00;
    }
    #success-icon {
        color: green;
    }
    #failure-icon {
        color: orange;
    }
    #summary button {
        min-width: 130px;
    }
    div.card {
        border: 1px solid #eeeeff;
        border-radius: 8px;
        min-width: 270px;
        background-color: #fefeff;
        padding: 10px;
        max-width: 270px;
        margin-top: 20px;
        margin-left: 20px;
    }
    div.card .title {
        color: #9999bb;
        border-radius: 8px;
        background-color: #ffffff;
        text-align: center;
        font-weight: bold;
        border-bottom: 1px solid #eeeeff;
        padding: 5px;
        margin-bottom: 10px;
    }
    span.head {
        margin-left: 20px;
        font-weight: bold;
    }
    span.sect {
        margin-left: 40px;
        font-weight: bold;
        font-style: italic;
    }
    span.item {
        margin-left: 60px;
    }
    span.failed {
        color: red;
    }
</style>

<h1>System Diagnostics</h1>
<div id="summary">
    <div id="status-success" class="status"><i id="success-icon" class="fa fa-thumbs-up"></i> No problem detected</div>
    <div id="status-failure" class="status"><i id="failure-icon" class="fa fa-thumbs-down"></i> Problem detected!</div>
    <button class="btn btn-primary timer">Pause Update</button>
    <button class="btn btn-success details">Show Details</button>
</div>
<div id="details" class="hide row"></div>

<script src="<?= $this->url->get('js/views/monitor/diagnostics.js?rev=1') ?>"></script>

<script>
        $(document).ready(function () {

            if (oe_module_loaded("monitor-diagnostics")) {
                return;
            }

            // 
            // Handle pause/resume update event:
            // 
            $("button.timer").click(function () {
                if (diagnostics.isRunning()) {
                    diagnostics.stop();
                } else {
                    diagnostics.start();
                }
            });

            // 
            // Handle show details event:
            // 
            $("button.details").click(function () {
                $("#details").toggleClass('hide');
                if ($("#details").is(":visible")) {
                    $("button.details").html("Hide Details");
                    diagnostics.useDetails(true);
                } else {
                    $("button.details").html("Show Details");
                    diagnostics.useDetails(false);
                }
                if (diagnostics.hasDetails() && diagnostics.isRunning()) {
                    diagnostics.update();
                }
            });

            // 
            // Begin update using default settings.
            // 
            diagnostics.start();
        });
</script>
