<?php
/*
 * Copyright (C) 2016-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    index.phtml
// Created: 2016-05-25 14:26:27
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<h1>System Monitoring</h1>

<p>Click on one of the buttons below to start.</p>

<ul><li>The performance page displays various counters useful for diagnostic bottlenecks in the system (like CPU, memory or network utilization).</li>
    <li>The diagnostics page is used to monitor health of system services (for example authentication or directory services).</li>
</ul>
<br/>
<p><i class="fa fa-exclamation"></i> These tools are strictly for system monitoring and are probably of zero to none interest for ordinary users.</p>
<br/>
<div>
    <button id="performance" class="btn btn-primary">Performance</button>
    <button id="diagnostics" class="btn btn-primary">Diagnostics</button>
</div>

<script>
        if (oe_module_loaded("monitor-index")) {
            return;
        }

        $("#performance").click(function () {
            location.href = "performance";
        });
        $("#diagnostics").click(function () {
            location.href = "diagnostics";
        });
</script>