<?php

// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    index.phtml
// 
// Author:  Ahsan Shahzad (MedfarmDoIT)
// 
?>

<div class="hero-unit" style="padding-top:18px; margin-top:40px;">
    <h1>Welcome!</h1>
    <br />
    <p>This system let you do examination online, see <a href="help.php">Help</a> for more information. </p>
    <h3>Are you ready to begin the examination?</h3>
    <div>Click on <a class="fancybox fancybox.ajax" href="<?=$this->url->get('auth/login')?>">Login</a> and you will be prompted to logon using your UU-ID (CAS logon).</div>
</div>

<div class="row">
    <div class="span4">
        <h2>Are you a Teacher? </h2>
        <p>
        	<iframe width="300" frameborder="0" src="http://media.medfarm.uu.se/play/video/embed/3830"></iframe>
                Please feel free to contact us if you need more help regarding OpenExam ...<br />
                <a href="#">Do you want to read more?</a>
        </p>
    </div>
    <div class="span4">
        <h2>Are you a Student? </h2>
        <p>
                <iframe width="300" src="http://media.medfarm.uu.se/play/video/embed/3174" frameborder="0"></iframe>
                Please feel free to contact us if you need more help regarding OpenExam ...<br />
                <a href="#">Are you ready to take your exam?</a>
        </p>
    </div>
    <div class="span4">
        <h2>Important Notification</h2>
        <p>
        <span style="color:#3a87ad">2014-11-18</span><br />
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
    </div>
    <div class="span4">
        <h2>OpenExam Demo </h2>
        <p>
        <ul style="margin-top:0px; margin-bottom:15px">
        	<li>Are you a teacher? <a href="#">Try!</a></li>
                <li>Are you a student? <a href="#">Try!</a></li>
        </ul>
        <div id="msg-box" class="alert" style="font-weight:normal;text-align:left; position: inherit; width:90%; padding:8px 8px 8px 14px">Please note that demo mode is for test purposes only. All data gets deleted automatically, without any notification.</div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
    </div>
</div>
