<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    finished.phtml
// Created: 2015-03-13 15:56:03
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<?= Phalcon\Tag::stylesheetLink('css/signup.css?rev=1'); ?>

<style>
    h1.signup {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }  
</style>

<div class="signup">
    <h1 class="signup">Signup finished!</h1>
    <p>
        Your signup request is now completed. Click on the button below to start use the system.
    </p>
    <hr/>
    <p>
        <input class="btn btn-green" type="submit" name="start" value="Continue" onclick="window.location.assign('<?= $startpage ?>')" title="Click on this button to start using the system."/>
    </p>
</div>
