<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    missing.phtml
// Created: 2015-03-27 03:34:21
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<?= Phalcon\Tag::stylesheetLink('css/signup.css'); ?>

<style>
    h1.signup {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }  
</style>

<div class="signup">
    <h1 class="signup">Missing affiliation</h1>
    <p>
        It appears like you are neither an employee or student. Your affiliation
        is queried from the catalog service that might be missing this information.
    </p>
    <p>
        If you think this is a bug, please contact the system administrator for
        further assistants in solving this issue.
    </p>
</div>
