<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    missing.phtml
// Created: 2015-03-27 03:34:21
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<?= Phalcon\Tag::stylesheetLink('css/signup.css?rev=1'); ?>

<style>
    h1.signup {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }  
</style>

<div class="signup">
    <h1 class="signup">Missing affiliation</h1>
    <p>
        It appears like you are neither an employee or student. Your affiliation
        is queried from the catalog service that might be missing this information.
    </p>
    <p>
        If you think this is a bug, please contact the system administrator for
        further assistants in solving this issue.
    </p>
</div>
