<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    remove.phtml
// Created: 2015-03-27 04:57:20
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<?= Phalcon\Tag::stylesheetLink('css/signup.css?rev=1'); ?>

<style>
    h1.signup {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }  
</style>

<div class="signup">
    <h1 class="signup">Removed!</h1>
    <?php if ($employee) { ?>
            <p>
                Your role as a teacher in the system have now been removed. You will still
                have access to the exams you are or have been participating in, e.g. as a corrector.
            </p>
    <?php } else { ?>
            You have now been removed as a student from the example examinations. You will
            still have access to your real examinations.
    <?php } ?>
</div>
