<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    remove.phtml
// Created: 2015-03-27 04:57:20
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<?= Phalcon\Tag::stylesheetLink('css/signup.css?rev=1'); ?>

<style>
    h1.signup {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }  
</style>

<div class="signup">
    <h1 class="signup">Removed!</h1>
    <?php if ($employee) { ?>
            <p>
                Your role as a teacher in the system have now been removed. You will still
                have access to the exams you are or have been participating in, e.g. as a corrector.
            </p>
    <?php } else { ?>
            You have now been removed as a student from the example examinations. You will
            still have access to your real examinations.
    <?php } ?>
</div>
