
<?= $this->getContent(); ?>

<div class="hero-unit">
        <h1>Welcome to Open exam system</h1>
</div>

<div class="row">
        <div class="span4">
                <h2>Contribute in exam </h2>
                <p>Exam 1 </p>
                <p>Exam 2 </p>
        </div>
        <div class="span4">
                <h2>Decode an exam</h2>
                <p>Exam 1 </p>
                <p>Exam 2 </p>
        </div>
        <div class="span4">
                <h2>Correct an exam </h2>
                <p>Exam 1 </p>
                <p>Exam 2 </p>
        </div>
</div>
