<?php

namespace OpenExam\Models;

use Exception;
use OpenExam\Tests\Phalcon\TestCase;
use OpenExam\Tests\Phalcon\TestModelAccess;
use OpenExam\Tests\Phalcon\TestModelBasic;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-15 at 08:53:37.
 * 
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class AdminTest extends TestCase
{

        protected function setUp()
        {
                $this->getDI()->get('user')->setPrimaryRole(null);
        }

        /**
         * @group model
         */
        public function testProperties()
        {
                $values = array(
                        'user' => 'user1'
                );

                try {
                        $helper = new TestModelBasic(new Admin());
                        $helper->tryPersist();
                        self::fail("Excepted constraint violation exception");
                } catch (Exception $exception) {
                        // Expected exception
                }

                try {
                        $helper = new TestModelBasic(new Admin());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail($exception);
                }

                $values = array(
                        'user'         => 'user1',
                        'non_existing' => 666
                );
                try {
                        $helper = new TestModelBasic(new Admin());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail("Unexcepted constraint violation exception");
                }
        }

        /**
         * @group model
         * @group security
         */
        public function testAccess()
        {
                $helper = new TestModelAccess(new Admin());
                $helper->testModelAccess();
        }

        /**
         * @covers OpenExam\Models\Admin::getSource
         * @group model
         */
        public function testGetSource()
        {
                $object = new Admin();
                $expect = "admins";
                $actual = $object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
