<?php

namespace OpenExam\Models;

use Exception;
use OpenExam\Models\Admin;
use OpenExam\Tests\Phalcon\TestModel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-15 at 08:53:37.
 * 
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class AdminTest extends TestModel
{

        public function __construct()
        {
                parent::__construct(new Admin());
        }

        /**
         * @covers OpenExam\Models\Admin::properties
         * @group model
         */
        public function testProperties()
        {
                $values = array(
                        'user' => 'user1'
                );

                try {
                        $helper = new TestModel(new Admin());
                        $helper->tryPersist();
                        self::fail("Excepted constraint violation exception");
                } catch (Exception $exception) {
                        // Expected exception
                }

                try {
                        $helper = new TestModel(new Admin());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail($exception);
                }

                $values = array(
                        'user'         => 'user1',
                        'non_existing' => 666
                );
                try {
                        $helper = new TestModel(new Admin());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail("Unexcepted constraint violation exception");
                }
        }

        /**
         * @covers OpenExam\Models\Admin::getSource
         * @group model
         */
        public function testGetSource()
        {
                $expect = "admins";
                $actual = $this->object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
