<?php

namespace OpenExam\Models;

use OpenExam\Tests\Phalcon\TestModel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-15 at 11:38:53.
 * 
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class AnswerTest extends TestModel
{

        public function __construct()
        {
                parent::__construct(new Answer());
        }

        /**
         * @covers OpenExam\Models\Answer::properties
         * @group model
         */
        public function testProperties()
        {
                $values = array(
                        'student_id'  => Student::findFirst()->id,
                        'question_id' => Question::findFirst()->id
                );

                try {
                        $helper = new TestModel(new Answer());
                        $helper->tryPersist();
                        self::fail("Excepted constraint violation exception");
                } catch (\Exception $exception) {
                        // Expected exception
                }

                try {
                        $helper = new TestModel(new Answer());
                        $helper->tryPersist($values);
                } catch (\Exception $exception) {
                        self::fail($exception);
                }

                $helper->checkDefaults(array(
                        'answered' => false
                ));

                $values = array(
                        'student_id'  => Student::findFirst()->id,
                        'question_id' => Question::findFirst()->id,
                        'answered'    => true,
                        'answer'      => 'Answer text',
                        'comment'     => 'Comment text'
                );
                try {
                        $helper = new TestModel(new Answer());
                        $helper->tryPersist($values);
                } catch (\Exception $exception) {
                        self::fail($exception);
                }

                $values = array(
                        'student_id'   => Student::findFirst()->id,
                        'question_id'  => Question::findFirst()->id,
                        'non_existing' => 666
                );
                try {
                        $helper = new TestModel(new Answer());
                        $helper->tryPersist();
                        self::fail("Excepted constraint violation exception");
                } catch (\Exception $exception) {
                        // Expected exception
                }
        }

        /**
         * @covers OpenExam\Models\Answer::getSource
         * @group model
         */
        public function testGetSource()
        {
                $expect = "answers";
                $actual = $this->object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
