<?php

namespace OpenExam\Models;

use OpenExam\Tests\Phalcon\TestModel;

/**
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class CorrectorModel extends Corrector
{

        public function initialize()
        {
                parent::initialize();
        }

}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-17 at 04:33:42.
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class CorrectorTest extends TestModel
{

        public function __construct()
        {
                parent::__construct(new CorrectorModel());
        }

        /**
         * @group model
         */
        public function testRelations()
        {
                $corrector = Corrector::findFirst();
                self::assertNotNull($corrector);

                self::assertNotEquals($corrector->question->count(), 0);
                self::assertTrue(count($corrector->question) == 1);
        }

        /**
         * @covers OpenExam\Models\Corrector::initialize
         * @group model
         */
        public function testProperties()
        {
                $values = array(
                        'question_id' => Question::findFirst()->id,
                        'user'        => 'user1'
                );

                try {
                        $helper = new TestModel(new Corrector());
                        $helper->tryPersist();
                        self::fail("Excepted constraint violation exception");
                } catch (\Exception $exception) {
                        // Expected exception
                }

                try {
                        $helper = new TestModel(new Corrector());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail($exception);
                }

                $values = array(
                        'question_id'  => Question::findFirst()->id,
                        'user'         => 'user1',
                        'non_existing' => 666   // ignored wihout error
                );
                try {
                        $helper = new TestModel(new Corrector());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail("Unexcepted constraint violation exception");
                }
        }

        /**
         * @covers OpenExam\Models\Corrector::getSource
         * @group model
         */
        public function testGetSource()
        {
                $expect = "correctors";
                $actual = $this->object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
