<?php

namespace OpenExam\Models;

use Exception;
use OpenExam\Tests\Phalcon\TestModel;

/**
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class FileModel extends File
{

        public function initialize()
        {
                parent::initialize();
        }

}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-21 at 15:11:16.
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class FileTest extends TestModel
{

        public function __construct()
        {
                parent::__construct(new FileModel());
        }

        /**
         * @group model
         */
        public function testRelations()
        {
                $file = File::findFirst();
                self::assertNotNull($file);

                self::assertNotEquals($file->answer->count(), 0);
                self::assertTrue(count($file->answer) == 1);
        }

        /**
         * @group model
         */
        public function testProperties()
        {
                $values = array(
                        'answer_id' => Answer::findFirst()->id,
                        'name'      => 'Name1',
                        'path'      => '/tmp/path',
                        'type'      => 'video',
                        'subtype'   => 'mp4'
                );

                try {
                        $helper = new TestModel(new File());
                        $helper->tryPersist();
                        self::fail("Excepted constraint violation exception");
                } catch (Exception $exception) {
                        // Expected exception
                }

                try {
                        $helper = new TestModel(new File());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail($exception);
                }

                $values = array(
                        'answer_id'    => Answer::findFirst()->id,
                        'name'         => 'Name1',
                        'path'         => '/tmp/path',
                        'type'         => 'video',
                        'subtype'      => 'mp4',
                        'non_existing' => 666   // ignored wihout error
                );
                try {
                        $helper = new TestModel(new File());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail("Unexcepted constraint violation exception");
                }

                // 
                // Test shared property:
                // 
                $media = new File();
                $media->assign($values);
                $media->save();
        }

        /**
         * @covers OpenExam\Models\Contributor::getSource
         * @group model
         */
        public function testGetSource()
        {
                $expect = "files";
                $actual = $this->object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
