<?php

namespace OpenExam\Models;

use OpenExam\Tests\Phalcon\TestModel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-15 at 18:50:00.
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class LockTest extends TestModel
{

        public function __construct()
        {
                parent::__construct(new Lock());
        }

        /**
         * @group model
         */
        public function testRelations()
        {
                $lock = Lock::findFirst();
                self::assertNotNull($lock);

                self::assertNotEquals($lock->exam->count(), 0);
                self::assertNotEquals($lock->computer->count(), 0);

                self::assertTrue(count($lock->exam) == 1);
                self::assertTrue(count($lock->computer) == 1);
        }

        /**
         * @group model
         */
        public function testProperties()
        {
                $values = array(
                        'computer_id' => Computer::findFirst()->id,
                        'exam_id'     => Exam::findFirst()->id
                );


                try {
                        $helper = new TestModel(new Lock());
                        $helper->tryPersist();
                        self::fail("Excepted constraint violation exception");
                } catch (\Exception $exception) {
                        // Expected exception
                }

                try {
                        $helper = new TestModel(new Lock());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail($exception);
                }

                $values = array(
                        'computer_id' => Computer::findFirst()->id,
                        'exam_id'     => Exam::findFirst()->id,
                        'aquired'     => date('Y-m-d H:i:s')
                );
                try {
                        $helper = new TestModel(new Lock());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail("Unexcepted constraint violation exception");
                }

                $values = array(
                        'computer_id'  => Computer::findFirst()->id,
                        'exam_id'      => Exam::findFirst()->id,
                        'non_existing' => 666   // ignored wihout error
                );
                try {
                        $helper = new TestModel(new Lock());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail("Unexcepted constraint violation exception");
                }
        }

        /**
         * @covers OpenExam\Models\Lock::getSource
         * @group model
         */
        public function testGetSource()
        {
                $expect = "locks";
                $actual = $this->object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
