<?php

namespace OpenExam\Models;

use Exception;
use OpenExam\Tests\Phalcon\TestCase;
use OpenExam\Tests\Phalcon\TestModelAccess;
use OpenExam\Tests\Phalcon\TestModelBasic;

/**
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class LockModel extends Lock
{

        public function initialize()
        {
                parent::initialize();
        }

}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-15 at 18:50:00.
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class LockTest extends TestCase
{

        protected function setUp()
        {
                $this->getDI()->get('user')->setPrimaryRole(null);
        }

        /**
         * @group model
         */
        public function testRelations()
        {
                $lock = Lock::findFirst();
                self::assertNotNull($lock);

                self::assertNotEquals(0, $lock->exam->count());
                self::assertNotEquals(0, $lock->computer->count());

                self::assertTrue(count($lock->exam) == 1);
                self::assertTrue(count($lock->computer) == 1);
        }

        /**
         * @group model
         */
        public function testProperties()
        {
                $values = array(
                        'computer_id' => Computer::findFirst()->id,
                        'exam_id'     => Exam::findFirst()->id
                );

                try {
                        $helper = new TestModelBasic(new Lock());
                        $helper->tryPersist();
                        self::error("Excepted constraint violation exception");
                } catch (Exception $exception) {
                        // Expected exception
                }

                try {
                        $helper = new TestModelBasic(new Lock());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::error($exception);
                }

                $values = array(
                        'computer_id' => Computer::findFirst()->id,
                        'exam_id'     => Exam::findFirst()->id,
                        'aquired'     => date('Y-m-d H:i:s')
                );
                try {
                        $helper = new TestModelBasic(new Lock());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::error("Unexcepted constraint violation exception");
                }

                $values = array(
                        'computer_id'  => Computer::findFirst()->id,
                        'exam_id'      => Exam::findFirst()->id,
                        'non_existing' => 666   // ignored wihout error
                );
                try {
                        $helper = new TestModelBasic(new Lock());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::error("Unexcepted constraint violation exception");
                }
        }

        /**
         * @group model
         * @group security
         */
        public function testAccess()
        {
                $helper = new TestModelAccess(new Lock());
                $helper->testModelAccess();
        }

        /**
         * @covers OpenExam\Models\Lock::getSource
         * @group model
         */
        public function testGetSource()
        {
                $object = new LockModel();
                $expect = "locks";
                $actual = $object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
