<?php

namespace OpenExam\Models;

use OpenExam\Models\ModelBase;
use OpenExam\Tests\Phalcon\TestCase;

class ExampleModel extends ModelBase
{

        public function initialize()
        {
                parent::initialize();
        }

}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-19 at 03:15:59.
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class ModelBaseTest extends TestCase
{

        private $object;

        public function setUp()
        {
                $this->object = new ExampleModel();
        }

        /**
         * @covers OpenExam\Models\ModelBase::initialize
         * @group model
         */
        public function testInitialize()
        {
                $this->object->initialize();
        }

        /**
         * @covers OpenExam\Models\ModelBase::getName
         * @group model
         */
        public function testGetName()
        {
                $expect = 'examplemodel';
                $actual = $this->object->getName();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
