<?php

namespace OpenExam\Models;

use Exception;
use OpenExam\Tests\Phalcon\TestCase;
use OpenExam\Tests\Phalcon\TestModelAccess;
use OpenExam\Tests\Phalcon\TestModelBasic;

/**
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class ResourceModel extends Resource
{

        public function initialize()
        {
                parent::initialize();
        }

}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-21 at 15:11:59.
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class ResourceTest extends TestCase
{

        protected function setUp()
        {
                $this->getDI()->get('user')->setPrimaryRole(null);
        }

        /**
         * @group model
         */
        public function testRelations()
        {
                $resource = Resource::findFirst();
                self::assertNotNull($resource);

                self::assertNotEquals(0, $resource->exam->count());
                self::assertTrue(count($resource->exam) == 1);
        }

        /**
         * @group model
         */
        public function testProperties()
        {
                $values = array(
                        'exam_id' => Exam::findFirst()->id,
                        'name'    => 'Name1',
                        'path'    => '/tmp/path',
                        'type'    => 'video',
                        'subtype' => 'mp4',
                        'user'    => 'user1@example.com'
                );

                try {
                        $helper = new TestModelBasic(new Resource());
                        $helper->tryPersist();
                        self::error("Excepted constraint violation exception");
                } catch (Exception $exception) {
                        // Expected exception
                }

                try {
                        $helper = new TestModelBasic(new Resource());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::error($exception);
                }

                $helper->checkDefaults(array(
                        'shared' => Resource::SHARED_EXAM
                ));

                $values = array(
                        'exam_id'      => Exam::findFirst()->id,
                        'name'         => 'Name1',
                        'path'         => '/tmp/path',
                        'type'         => 'video',
                        'subtype'      => 'mp4',
                        'user'         => 'user1@example.com',
                        'non_existing' => 666   // ignored wihout error
                );
                try {
                        $helper = new TestModelBasic(new Resource());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::error("Unexcepted constraint violation exception");
                }

                $values = array(
                        'exam_id' => Exam::findFirst()->id,
                        'name'    => 'Name1',
                        'path'    => '/tmp/path',
                        'type'    => 'video',
                        'subtype' => 'mp4',
                        'user'    => 'user1@example.com',
                        'shared'  => 'unknown' // should fail at validation
                );
                try {
                        $helper = new TestModelBasic(new Resource());
                        $helper->tryPersist($values);
                        self::error("Excepted constraint violation exception");
                } catch (Exception $exception) {
                        // Expected exception
                }
        }

        /**
         * @group model
         * @group security
         */
        public function testAccess()
        {
                $helper = new TestModelAccess(new Resource());
                $helper->testModelAccess();
        }

        /**
         * @covers OpenExam\Models\Contributor::getSource
         * @group model
         */
        public function testGetSource()
        {
                $object = new ResourceModel();
                $expect = "resources";
                $actual = $object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
