<?php

namespace OpenExam\Models;

use Exception;
use OpenExam\Models\Room;
use OpenExam\Tests\Phalcon\TestCase;
use OpenExam\Tests\Phalcon\TestModelAccess;
use OpenExam\Tests\Phalcon\TestModelBasic;

class RoomModel extends Room
{

        public function initialize()
        {
                parent::initialize();
        }

}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-15 at 08:53:37.
 * 
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class RoomTest extends TestCase
{

        protected function setUp()
        {
                $this->getDI()->get('user')->setPrimaryRole(null);
        }

        /**
         * @group model
         */
        public function testRelations()
        {
                $room = Computer::findFirst()->room;
                self::assertNotNull($room);

                self::assertNotEquals(0, $room->computers->count());
                self::assertTrue(count($room->computers) > 0);
        }

        /**
         * @group model
         */
        public function testProperties()
        {
                $values = array(
                        'name'        => 'Name1',
                        'description' => 'Description1'
                );

                try {
                        $helper = new TestModelBasic(new Room());
                        $helper->tryPersist();
                        self::error("Excepted constraint violation exception");
                } catch (Exception $exception) {
                        // Expected exception
                }

                try {
                        $helper = new TestModelBasic(new Room());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::error($exception);
                }
        }

        /**
         * @group model
         * @group security
         */
        public function testAccess()
        {
                $helper = new TestModelAccess(new Room());
                $helper->testModelAccess();
        }

        /**
         * @covers OpenExam\Models\Room::getSource
         * @group model
         */
        public function testGetSource()
        {
                $object = new RoomModel();
                $expect = "rooms";
                $actual = $object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
