<?php

namespace OpenExam\Models;

use Exception;
use OpenExam\Tests\Phalcon\TestCase;
use OpenExam\Tests\Phalcon\TestModelAccess;
use OpenExam\Tests\Phalcon\TestModelBasic;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-20 at 12:38:54.
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class SessionTest extends TestCase
{

        protected function setUp()
        {
                $this->getDI()->get('user')->setPrimaryRole(null);
        }

        /**
         * @covers OpenExam\Models\Session::initialize
         * @group model
         */
        public function testProperties()
        {
                $values = array(
                        'session_id' => md5(time()),
                        'data'       => serialize(array('auth' => array('user' => 'user1', 'type' => 'cas'))),
                        'created'    => time()
                );

                try {
                        $helper = new TestModelBasic(new Session());
                        $helper->tryPersist();
                        self::error("Excepted constraint violation exception");
                } catch (Exception $exception) {
                        // Expected exception
                }

                try {
                        $helper = new TestModelBasic(new Session());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::error($exception);
                }

                $values = array(
                        'session_id' => md5(time()),
                        'data'       => serialize(array('auth' => array('user' => 'user1', 'type' => 'cas'))),
                        'created'    => time(),
                        'updated'    => time() + 1
                );
                try {
                        $helper = new TestModelBasic(new Session());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::error("Unexcepted constraint violation exception");
                }
        }

        /**
         * @group model
         * @group security
         */
        public function testAccess()
        {
                $helper = new TestModelAccess(new Session());
                $helper->testModelAccess();
        }

        /**
         * @covers OpenExam\Models\Session::getSource
         * @group model
         */
        public function testGetSource()
        {
                $object = new Session();
                $expect = "sessions";
                $actual = $object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
