<?php

namespace OpenExam\Models;

use Exception;
use OpenExam\Tests\Phalcon\TestModelAccess;
use OpenExam\Tests\Phalcon\TestModelBasic;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-20 at 12:38:54.
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class SessionTest extends TestModelBasic
{

        public function __construct()
        {
                parent::__construct(new Session());
        }

        protected function setUp()
        {
                $this->getDI()->get('user')->setPrimaryRole(null);
        }

        /**
         * @covers OpenExam\Models\Session::initialize
         * @group model
         */
        public function testProperties()
        {
                $values = array(
                        'session_id' => md5(time()),
                        'data'       => serialize(array('auth' => array('user' => 'user1', 'type' => 'cas'))),
                        'created'    => time()
                );

                try {
                        $helper = new TestModelBasic(new Session());
                        $helper->tryPersist();
                        self::fail("Excepted constraint violation exception");
                } catch (Exception $exception) {
                        // Expected exception
                }

                try {
                        $helper = new TestModelBasic(new Session());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail($exception);
                }

                $values = array(
                        'session_id' => md5(time()),
                        'data'       => serialize(array('auth' => array('user' => 'user1', 'type' => 'cas'))),
                        'created'    => time(),
                        'updated'    => time() + 1
                );
                try {
                        $helper = new TestModelBasic(new Session());
                        $helper->tryPersist($values);
                } catch (Exception $exception) {
                        self::fail("Unexcepted constraint violation exception");
                }
        }

        /**
         * @group model
         * @group security
         */
        public function testAccess()
        {
                $values = array(
                        'session_id' => md5(time()),
                        'data'       => serialize(array('auth' => array('user' => 'user1', 'type' => 'cas'))),
                        'created'    => time()
                );

                $helper = new TestModelAccess(new Session(), $values);
                $helper->testModelAccess();
        }

        /**
         * @covers OpenExam\Models\Session::getSource
         * @group model
         */
        public function testGetSource()
        {
                $expect = "sessions";
                $actual = $this->object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

}
