<?php

namespace OpenExam\Models;

use OpenExam\Library\Security\User;
use OpenExam\Tests\Phalcon\TestModel;
use OpenExam\Tests\Phalcon\UniqueUser;

/**
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class QuestionModel extends Question
{

        public function initialize()
        {
                parent::initialize();
        }

}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-15 at 19:49:10.
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class QuestionTest extends TestModel
{

        /**
         * The model resource name.
         */
        const MODEL = 'question';

        /**
         * @group model
         */
        public function testRelations()
        {
                $object = Question::findFirstById($this->sample->getSample(self::MODEL)['id']);
                self::assertNotNull($object);

                self::assertNotEquals(0, $object->answers->count());
                self::assertTrue(count($object->answers) > 0);

                self::assertNotEquals(0, $object->correctors->count());
                self::assertTrue(count($object->correctors) > 0);

                self::assertNotEquals(0, $object->exam->count());
                self::assertTrue(count($object->exam) == 1);

                self::assertNotEquals(0, $object->topic->count());
                self::assertTrue(count($object->topic) == 1);
        }

        /**
         * @covers OpenExam\Models\Question::getSource
         * @group model
         */
        public function testGetSource()
        {
                $object = new QuestionModel();
                $expect = "questions";
                $actual = $object->getSource();
                self::assertNotNull($actual);
                self::assertEquals($expect, $actual);
        }

        /**
         * Test model behavior.
         * @group model
         */
        public function testBehavior()
        {
                $user = $this->getDI()->get('user');

                /**
                 * Test ownership:
                 */
                // 
                // Test caller on create:
                // 
                $expect = $user->getPrincipalName();
                $object = new Question();
                $object->assign($this->sample->getSample('question', false));
                $object->user = null;

                self::assertTrue($object->create());
                self::assertNotNull($object->user);
                self::assertTrue(is_string($object->user));

                $actual = $object->user;
                self::assertEquals($expect, $actual);

                $object->delete();

                // 
                // Test custom user on create:
                //                 
                $expect = 'user@example.com';
                $object = new Question();
                $object->assign($this->sample->getSample('question', false));
                $object->user = $expect;

                self::assertTrue($object->create());
                self::assertNotNull($object->user);
                self::assertTrue(is_string($object->user));

                $actual = $object->user;
                self::assertEquals($expect, $actual);

                // 
                // Test caller on update:
                // 
                $expect = $user->getPrincipalName();
                $object->user = $user->getPrincipalName();

                self::assertTrue($object->update());
                self::assertNotNull($object->user);
                self::assertTrue(is_string($object->user));

                $actual = $object->user;
                self::assertEquals($expect, $actual);

                // 
                // Test custom user on update:
                // 
                $expect = 'user@example.com';
                $object->user = $expect;

                self::assertTrue($object->update());
                self::assertNotNull($object->user);
                self::assertTrue(is_string($object->user));

                $actual = $object->user;
                self::assertEquals($expect, $actual);

                $object->delete();

                /**
                 * Test UUID:
                 */
                $object = new Question();
                $object->assign($this->sample->getSample('question', false));

                self::assertTrue($object->create());
                self::assertNotNull($object->uuid);
                self::assertTrue(is_string($object->uuid));

                $object->uuid = null;
                $object->update();
                self::assertNotNull($object->uuid);

                $expect = 'qtest123-1670-59b3-1ede-efb502ed';
                $object->uuid = $expect;
                $object->update();
                $actual = $object->uuid;
                self::assertEquals($actual, $expect);

                $object->delete();

                /**
                 * Test caller added as corrector:
                 */
                $expect = $user->getPrincipalName();
                $object = new Question();
                $object->assign($this->sample->getSample('question', false));
                $object->user = $expect;

                self::assertTrue($object->create());
                self::assertTrue($object->correctors->count() != 0);
                $corrector = $object->correctors[0];
                self::assertNotNull($corrector);
                self::assertEquals($expect, $corrector->user);

                $object->delete();

                $object = new Question();
                $object->assign($this->sample->getSample('question', false));
                $object->create();

                // 
                // Test filter text:
                // 
                foreach (array('quest', 'answer', 'comment') as $field) {
                        $object->$field = '<!--[if gte mso 9]><xml>test1<![endif]-->test2\n<!--[if gte mso 9]><xml>test1<![endif]--><br/>test3\n\n<t >test4</t><!--[if gte mso 9]><xml>test5<![endif]-->';
                        $expect = 'test2\n<br/>test3\n\n<t >test4</t>';

                        self::assertTrue($object->update());
                        self::assertNotNull($object->$field);
                        self::assertTrue(is_string($object->$field));

                        $actual = $object->$field;
                        self::assertEquals($expect, $actual);
                }

                $object->delete();
        }

        /**
         * @covers OpenExam\Models\Question::create
         * @group model
         */
        public function testCreate()
        {
                $user = new User();
                $roles = $this->capabilities->getRoles();

                self::info("+++ pass: primary role unset");
                foreach ($roles as $role) {
                        $user->setPrimaryRole(null);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL, false));
                        self::assertTrue($this->create($model, $user, true));
                        $this->cleanup($model);
                }

                $user = new User();
                $roles = $this->capabilities->getRoles();

                self::info("+++ fail: user not authenticated");
                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL, false));
                        self::assertTrue($this->create($model, $user, false));
                        $this->cleanup($model);
                }

                $user = new User((new UniqueUser())->user);
                $roles = $this->capabilities->getRoles();

                self::info("+++ fail: user without roles");
                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL, false));
                        self::assertTrue($this->create($model, $user, false));
                        $this->cleanup($model);
                }

                $user = $this->getDI()->get('user');
                $roles = $this->capabilities->getRoles(self::MODEL);

                self::info("rolemap=%s", print_r($roles, true));

                self::info("+++ pass: user has roles");
                foreach ($roles as $role => $actions) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL, false));
                        if (in_array('create', $actions)) {
                                self::assertTrue($this->create($model, $user, true));   // action allowed
                        } else {
                                self::assertTrue($this->create($model, $user, false));  // action denied
                        }
                        $this->cleanup($model);
                }
        }

        /**
         * @covers OpenExam\Models\Question::update
         * @group model
         */
        public function testUpdate()
        {
                $user = new User();
                $roles = $this->capabilities->getRoles();

                self::info("+++ pass: primary role unset");
                foreach ($roles as $role) {
                        $user->setPrimaryRole(null);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL));
                        self::assertTrue($this->update($model, $user, true));
                }

                $user = new User();
                $roles = $this->capabilities->getRoles();

                self::info("+++ fail: user not authenticated");
                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL));
                        self::assertTrue($this->update($model, $user, false));
                }

                $user = new User((new UniqueUser())->user);
                $roles = $this->capabilities->getRoles();

                self::info("+++ fail: user without roles");
                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL));
                        self::assertTrue($this->update($model, $user, false));
                }

                $user = $this->getDI()->get('user');
                $roles = $this->capabilities->getRoles(self::MODEL);

                self::info("sample=%s", print_r($this->sample->getSample(self::MODEL), true));
                self::info("rolemap=%s", print_r($roles, true));

                self::info("+++ pass: user has roles");
                foreach ($roles as $role => $actions) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL));
                        if (in_array('update', $actions)) {
                                self::assertTrue($this->update($model, $user, true));   // action allowed
                        } else {
                                self::assertTrue($this->update($model, $user, false));  // action denied
                        }
                }
        }

        /**
         * @covers OpenExam\Models\Question::delete
         * @group model
         */
        public function testDelete()
        {
                $user = new User();
                $roles = $this->capabilities->getRoles();

                self::info("+++ pass: primary role unset");
                foreach ($roles as $role) {
                        $user->setPrimaryRole(null);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL, false));
                        $this->persist($model);
                        self::assertTrue($this->delete($model, $user, true));
                        $this->cleanup($model);
                }

                $user = new User();
                $roles = $this->capabilities->getRoles();

                self::info("+++ fail: user not authenticated");
                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL, false));
                        $this->persist($model);
                        self::assertTrue($this->delete($model, $user, false));
                        $this->cleanup($model);
                }

                $user = new User((new UniqueUser())->user);
                $roles = $this->capabilities->getRoles();

                self::info("+++ fail: user without roles");
                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL, false));
                        $this->persist($model);
                        self::assertTrue($this->delete($model, $user, false));
                        $this->cleanup($model);
                }

                $user = $this->getDI()->get('user');
                $roles = $this->capabilities->getRoles(self::MODEL);

                self::info("sample=%s", print_r($this->sample->getSample(self::MODEL), true));
                self::info("rolemap=%s", print_r($roles, true));

                self::info("+++ pass: user has roles");
                foreach ($roles as $role => $actions) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL, false));
                        $this->persist($model);
                        if (in_array('delete', $actions)) {
                                self::assertTrue($this->delete($model, $user, true));   // action allowed
                        } else {
                                self::assertTrue($this->delete($model, $user, false));  // action denied
                        }
                        $this->cleanup($model);
                }
        }

        /**
         * @covers OpenExam\Models\Question::find
         * @group model
         */
        public function testRead()
        {
                $user = new User();
                $roles = $this->capabilities->getRoles();

                self::info("+++ pass: primary role unset");
                foreach ($roles as $role) {
                        $user->setPrimaryRole(null);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL));
                        self::assertTrue($this->read($model, $user, true));
                }

                $user = new User();
                $roles = $this->capabilities->getRoles();

                self::info("+++ fail: user not authenticated");
                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL));
                        self::assertTrue($this->read($model, $user, false));
                }

                $user = new User((new UniqueUser())->user);
                $roles = $this->capabilities->getRoles();

                self::info("+++ fail: user without roles");
                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL));
                        self::assertTrue($this->read($model, $user, false));
                }

                $user = $this->getDI()->get('user');
                $roles = $this->capabilities->getRoles(self::MODEL);

                self::info("sample=%s", print_r($this->sample->getSample(self::MODEL), true));
                self::info("rolemap=%s", print_r($roles, true));

                self::info("+++ pass: user has roles");
                foreach ($roles as $role => $actions) {
                        $user->setPrimaryRole($role);
                        $model = new Question();
                        $model->assign($this->sample->getSample(self::MODEL));
                        if (in_array('read', $actions)) {
                                self::assertTrue($this->read($model, $user, true));   // action allowed
                        } else {
                                self::assertTrue($this->read($model, $user, false));  // action denied
                        }
                }
        }

        /**
         * Specific test of Question::query()
         * @covers OpenExam\Models\Question::query
         * @group model
         */
        public function testQuery()
        {
                $user = $this->getDI()->get('user');
                $roles = $this->capabilities->getRoles(self::MODEL);
                $roles = array_merge(array(null), array_keys($roles));

                $sample = $this->sample->getSample(self::MODEL);

                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);

                        $criteria = Question::query();
                        $result = $criteria->execute();
                        self::assertNotNull($result);
                        foreach ($result as $model) {
                                self::assertNotNull($model);
                        }

                        $criteria = Question::query();
                        $criteria
                            ->andWhere("name = :name: AND status = :status:", array(
                                    'name'   => $sample['name'],
                                    'status' => $sample['status']
                            ))
                            ->inWhere("id", array(1, $sample['id']))
                            ->orderBy("name desc, status");
                        $result = $criteria->execute();
                        self::assertNotNull($result);
                        $model = $result->getLast();
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);

                        $criteria = Question::query();
                        $criteria
                            ->andWhere("name = ?0 AND status = ?1", array(
                                    $sample['name'],
                                    $sample['status']
                            ))
                            ->inWhere("id", array(1, $sample['id']))
                            ->orderBy("name desc, status");
                        $result = $criteria->execute();
                        self::assertNotNull($result);
                        $model = $result->getLast();
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);
                }
        }

        /**
         * Specific test of Question::findFirst()
         * @covers OpenExam\Models\Question::findFirst
         * @group model
         */
        public function testFindFirst()
        {
                $user = $this->getDI()->get('user');
                $roles = $this->capabilities->getRoles(self::MODEL);
                $roles = array_merge(array(null), array_keys($roles));

                $sample = $this->sample->getSample(self::MODEL);

                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);

                        $model = Question::findFirst();
                        self::assertNotNull($model);

                        $model = Question::findFirst($sample['id']);
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);

                        $model = Question::findFirstById($sample['id']);
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);

                        $model = Question::findFirst(array(
                                    "conditions" => "name = :name:",
                                    "bind"       => array(
                                            'name' => $sample['name'])
                        ));
                        self::assertNotNull($model);
                        self::assertTrue($model->name == $sample['name']);
                }
        }

        /**
         * Specific test of Question::find()
         * @group model
         */
        public function testFind()
        {
                $user = $this->getDI()->get('user');
                $roles = $this->capabilities->getRoles(self::MODEL);
                $roles = array_merge(array(null), array_keys($roles));

                $sample = $this->sample->getSample(self::MODEL);

                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);

                        $result = Question::find();
                        self::assertNotNull($result);
                        self::assertTrue(count($result) > 0);
                        foreach ($result as $model) {
                                self::assertNotNull($model);
                        }

                        $result = Question::find(sprintf("id = %d", $sample['id']));
                        self::assertNotNull($result);
                        self::assertTrue(count($result) > 0);
                        $model = $result->getLast();
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);

                        $result = Question::find(sprintf("id = %d AND name = '%s'", $sample['id'], $sample['name']));
                        self::assertNotNull($result);
                        self::assertTrue(count($result) > 0);
                        $model = $result->getLast();
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);

                        $result = Question::find(array(
                                    "conditions" => "id = ?0 AND name = ?1",
                                    "bind"       => array($sample['id'], $sample['name'])
                        ));
                        self::assertNotNull($result);
                        self::assertTrue(count($result) > 0);
                        $model = $result->getLast();
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);

                        $result = Question::find(array(
                                    "conditions" => "id = :id: AND name = :name:",
                                    "bind"       => array(
                                            'id'   => $sample['id'],
                                            'name' => $sample['name'])
                        ));
                        self::assertNotNull($result);
                        self::assertTrue(count($result) > 0);
                        $model = $result->getLast();
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);
                }
        }

        /**
         * Specific test of PHQL over the Question model.
         * @group model
         */
        public function testPhql()
        {
                $user = $this->getDI()->get('user');
                $roles = $this->capabilities->getRoles(self::MODEL);
                $roles = array_merge(array(null), array_keys($roles));

                $sample = $this->sample->getSample(self::MODEL);
                $modman = $this->getDI()->get('modelsManager');

                foreach ($roles as $role) {
                        $user->setPrimaryRole($role);

                        // 
                        // Equivalent to Question::find():
                        // 
                        $result = $modman->executeQuery(
                            Question::getQuery("SELECT Question.* FROM Question")
                        );
                        self::assertNotNull($result);
                        self::assertTrue(count($result) > 0);
                        foreach ($result as $model) {
                                self::assertNotNull($model);
                        }

                        // 
                        // Equivalent to Question::findFirst():
                        // 
                        $result = $modman->executeQuery(
                            Question::getQuery("SELECT Question.* FROM Question LIMIT 1")
                        );
                        $model = $result->getFirst();
                        self::assertNotNull($model);

                        // 
                        // Equivalent to Question::findFirstById($sample['id']):
                        // 
                        $result = $modman->executeQuery(
                            Question::getQuery("SELECT Question.* FROM Question WHERE Question.id = " . $sample['id'])
                        );
                        $model = $result->getFirst();
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);

                        // 
                        // Equivalent to Question::find(sprintf("id = %d AND name = '%s'", $sample['id'], $sample['name'])):
                        // 
                        $result = $modman->executeQuery(
                            Question::getQuery(sprintf(
                                    "SELECT Question.* FROM Question WHERE Question.id = %d AND Question.name = '%s'", $sample['id'], $sample['name']
                                )
                        ));
                        self::assertNotNull($result);
                        self::assertTrue(count($result) > 0);
                        $model = $result->getLast();
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);

                        // 
                        // Equivalent to:
                        // 
                        // Question::find(array(
                        //      "conditions" => "id = ?0 AND name = ?1",
                        //      "bind"       => array($sample['id'], $sample['name'])
                        // );
                        $result = $modman->executeQuery(
                            Question::getQuery(
                                "SELECT Question.* FROM Question WHERE Question.id = ?0 AND Question.name = ?1"
                            ), array($sample['id'], $sample['name'])
                        );
                        self::assertNotNull($result);
                        self::assertTrue(count($result) > 0);
                        $model = $result->getLast();
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);

                        // 
                        // Equivalent to:
                        // 
                        // Question::find(array(
                        //      "conditions" => "id = :id: AND name = :name:",
                        //      "bind"       => array(
                        //              'id' => $sample['id'], 'name' => $sample['name']
                        //      )
                        // );
                        $result = $modman->executeQuery(
                            Question::getQuery(
                                "SELECT Question.* FROM Question WHERE Question.id = :id: AND Question.name = :name:"
                            ), array('id' => $sample['id'], 'name' => $sample['name'])
                        );
                        self::assertNotNull($result);
                        self::assertTrue(count($result) > 0);
                        $model = $result->getLast();
                        self::assertNotNull($model);
                        self::assertTrue($model->id == $sample['id']);
                }
        }

}
