<?php

// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    authenticators.phtml
// 
// Author:  Ahsan Shahzad (MedfarmDoIT)
// 
?>
<div style="width:500px">
    <div class="hero-unit">
        <h2><?=Phalcon\Tag::image(array("img/uu_logo.svg", "height"=>"55px", "style"=>"padding-right:20px"));?>Login area</h2>
        <br />
        
        <div id="select_auth_method">
            <p>Please select the appropriate login method from the list.</p>
            <p>
                <select id="auth_method">
                    <option value="">-- Please select one --</option>
                    <?php foreach($authMethods as $authMethod) :?>
                        <option value="<?=$authMethod['code']?>" auth_type="<?=$authMethod['type']?>"><?=$authMethod['name']?></option>
                    <?php endforeach; ?>
                </select>
            </p>
        </div>    
        
        <div class="formbased" id="msad" style="display:none">
            <p>Please enter your login credentials. </p>
                <form role="form" class="form-signin" method="post">
                    <input name="username" type="text" autofocus="" required="" placeholder="Login name" class="form-control">
                    <input name="password" type="password" required="" placeholder="Password" class="form-control">
                    <button type="submit" class="btn btn-lg btn-primary btn-block">Sign in</button>
                </form>        
            </p>
            <div class="formbased-error-msg"></div>
        </div>
    </div>
    
</div>

<!-- Javascript -->
<?=Phalcon\Tag::javascriptInclude('js/jquery.form.min.js');?>
<script language="javascript">
	$(document).ready(function() {
                /**
                 * authentication method selection
                 */
		$( '#auth_method' ).change(function() {
			
			var selAuthMethod = $(this).find(':selected');
                        var selAuthMethodUrl = '<?=$this->url->get("auth/login/")?>' + $(selAuthMethod).val();
                        
			if($(selAuthMethod).attr('auth_type') == 'urlbased') {
				
				location.href = selAuthMethodUrl;
			} else if($(selAuthMethod).attr('auth_type') == 'formbased') {
				
				$('#select_auth_method').hide();
				$('#' + $(selAuthMethod).val())
                                        .show()
                                        .find('form')
                                        .attr('action', selAuthMethodUrl);
			}
		});
                
                /**
                 * submit signin form through ajax
                 */
                $('.form-signin').ajaxForm({ 
                        type:   'post',
                        resetForm: true,
                        success: function (json) {
                                var jsonObj = jQuery.parseJSON(json);
                                if(jsonObj.status == 'failed') {
                                        $('.formbased-error-msg').html('Invalid username or password.')
                                }
                        }
                });  
        });
</script>