<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    form.phtml
// Created: 2015-02-09 14:09:06
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<style type="text/css">
    .login {
        background: none repeat scroll 0 0 #f6f6f6;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin: 0 20px;
        padding: 0 20px 5px;
        max-width: 600px;
        display: inline-block;
    }
    .credentials {
        width: 45%;
        float: left;
    }    
    .credentials form {
        margin-top: 20px;
        margin-left: 30px;
    }
    .credentials h4 {
        color: #999999;
    }
    h2.identity {
        background: url("<?= $this->url->get("/img/kgpg_identity.png") ?>") no-repeat right;
    }
    div.status {
        width: 45%;
        float: right;
        padding: 20px;
        border-radius: 5px;
    }
    #status-info {
        color: #5555aa;
        background-color: #ffffff;
        border: 1px solid lightskyblue;
    }
    #status-success {
        color: #006600;
        background-color: #eeffdd;
        border: 1px solid greenyellow;
    }
    #status-failure {
        background-color: #fffedd;
        border: 1px dashed #ff9d00;
    }
</style>

<div class="login">
    <h2 class="identity">Authentication is required to continue</h2>
    <hr/>

    <div class="credentials">
        <h4>Login using <?= $form->getUserOption('description'); ?></h4>

        <form action="<?= $form->getAction(); ?>" method="POST">
            <?php if ($form->has('fcode')) { ?>
                    <p>
                        <label>Code:</label>
                        <?= $form->render('fpass'); ?>
                    </p>
                    <p>
                        <label>Exam:</label>
                        <?= $form->render('fexam'); ?>
                    </p>
                    <?= $form->render('fcode'); ?>
            <?php } else { ?>
                    <p>
                        <label>Username:</label>
                        <?= $form->render('fuser'); ?>
                    </p>
                    <p>
                        <label>Password:</label>
                        <?= $form->render('fpass'); ?>
                    </p>
            <?php } ?>
            <p class="checkbox">
                <label>
                    <input type="checkbox" onclick="toggle_show_password('fpass')"> Show password
                </label>
            </p>
            <p>
                <?= $form->render('fsubmit'); ?>
            </p>
        </form>
    </div>
    <div class="status" id="status-info">
        <div style="float: left; display: inline-block; width: 15%">
            <i class="fa fa-info-circle fa-2x"></i>
        </div>
        <div style="float: left; display: inline-block; width: 85%">
            <?= $form->getUserOption('information') ?>
        </div>
    </div>
</div>

<script>
        function toggle_show_password(name) {
            var elem = document.getElementById(name);
            if (elem.attributes['type'].value === 'text') {
                elem.attributes['type'].value = 'password';
            } else {
                elem.attributes['type'].value = 'text';
            }
        }
</script>
