<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    form.phtml
// Created: 2015-02-09 14:09:06
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<style type="text/css">
    h2.identity {
        background: url("<?= $this->url->get("/img/kgpg_identity.png") ?>") no-repeat right 0px;
    }
    div.status {
        padding: 10px 25px 0 25px;
    }
    #status-info {
        padding: 20px;
        color: #5555aa;
        background-color: #ffffff;
        border-radius: 5px;
        border: 1px solid lightskyblue;
    }
    #status-success {
        color: #006600;
        background-color: #eeffdd;
        border: 1px solid greenyellow;
    }
    #status-failure {
        background-color: #fffedd;
        border: 1px dashed #ff9d00;
    }
</style>

<div class="oe-login">
    <h2 class="identity">Login using <?= $form->getUserOption('description'); ?></h2>
    <hr/>
    <div class="row">
        <div class="credentials col-sm-6">
            <form action="<?= $form->getAction(); ?>" method="POST">
                <?php if ($form->has('fcode')) { ?>
                        <p>
                            <label>Code:</label>
                            <?= $form->render('fpass'); ?>
                        </p>
                        <p>
                            <label>Exam:</label>
                            <?= $form->render('fexam'); ?>
                        </p>
                        <?= $form->render('fcode'); ?>
                <?php } else { ?>
                        <p>
                            <label>Username:</label>
                            <?= $form->render('fuser'); ?>
                        </p>
                        <p>
                            <label>Password:</label>
                            <?= $form->render('fpass'); ?>
                        </p>
                <?php } ?>
                <p class="checkbox">
                    <label>
                        <input type="checkbox" onclick="toggle_show_password('fpass')"> Show password
                    </label>
                </p>
                <p>
                    <?= $form->render('fcancel'); ?>
                    <?= $form->render('fsubmit'); ?>
                </p>
            </form>
        </div>
        <div class="status col-sm-6">
            <div id="status-info">
                <i class="fa fa-info-circle fa-2x"></i>
                <?= $form->getUserOption('information') ?>
            </div>
        </div>
    </div>
</div>

<script>
        function toggle_show_password(name) {
            var elem = document.getElementById(name);
            if (elem.attributes['type'].value === 'text') {
                elem.attributes['type'].value = 'password';
            } else {
                elem.attributes['type'].value = 'text';
            }
        }
</script>
