<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    login.phtml
// Created: 2015-02-23 23:44:54
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<style>
    h1.success {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }
</style>

<h1 class="success">Logged in</h1>
<p>
    You have successful login to <?= $auth->description; ?>. 
</p>
