<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    select.phtml
// Created: 2015-02-09 13:34:39
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<style type="text/css">
    .login {
        background: none repeat scroll 0 0 #f6f6f6;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin: 0 20px;
        padding: 0 20px 5px;
        max-width: 600px;
    }    
    .login form {
        margin-top: 20px;
        margin-left: 30px;
    }
    .login h4 {
        color: #999999;
    }
    h2.identity {
        background: url("<?=$this->url->get("/img/kgpg_identity.png")?>") no-repeat right;
    }
</style>

<br/>
<div class="login">
    <h2 class="identity">Authentication is required to continue</h2>
    <hr/>
    <h4>Select authentication method</h4>
    <form action="<?= $form->getAction(); ?>" method="POST">
        <?= $form->render("embed"); ?>
        <p>
            <?= $form->render("auth"); ?>
        </p>
        <p>
            <?= $form->render('submit'); ?>
        </p>
    </form>
</div>
