<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    select.phtml
// Created: 2015-02-09 13:34:39
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<style type="text/css">
    h2.identity {
        background: url("<?=$this->url->get("/img/kgpg_identity.png")?>") no-repeat right;
    }
</style>

<div class="oe-login">
    <h2 class="identity">Authentication is required to continue</h2>
    <hr/>
    <h4>Select authentication method</h4>
    <form action="<?= $form->getAction(); ?>" method="POST">
        <?= $form->render("embed"); ?>
        <p>
            <?= $form->render("auth"); ?>
        </p>
        <p>
            <?= $form->render('submit'); ?>
        </p>
    </form>
</div>
