<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    select.phtml
// Created: 2015-02-09 13:34:39
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<style type="text/css">
    h2.identity {
        background: url("<?= $this->url->get("/img/kgpg_identity.png") ?>") no-repeat right;
    }
</style>

<div class="oe-login">
    <h2 class="identity">Authentication is required to continue</h2>
    <hr/>
    <label>Select authentication method:</label>
    <form action="<?= $form->getAction(); ?>" method="POST">
        <?= $form->render("embed"); ?>
        <p>
            <?= $form->render("auth"); ?>
        </p>
        <p>
            <?= $form->render('submit'); ?>
        </p>
    </form>
</div>
