<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    finished.phtml
// Created: 2015-03-13 15:56:03
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<?= Phalcon\Tag::stylesheetLink('css/signup.css'); ?>

<style>
    h1.signup {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }  
</style>

<div class="signup">
    <h1 class="signup">Signup finished!</h1>
    <p>
        Your signup request is now completed. Click on the button below to start use the system.
    </p>
    <p>
        <input class="btn btn-green" type="submit" name="start" value="Continue" onclick="window.location.assign('<?= $startpage ?>')" title="Click on this button to start using the system."/>
    </p>
</div>
