<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    script.phtml
// Created: 2016-12-12 00:14:42
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<script>
        var exception = (function ()
        {
            return {
                server: '<?= gethostname() ?>',
                subject: '<?= $error->getString() ?>',
                message: '<?= $error->getMessage() ?>',
                receiver: <?= json_encode($contact) ?>,
                time: '<?= strftime('%F %T') ?>',
                file: '<?= basename($error->getException()->getFile()) ?>',
                line: '<?= $error->getException()->getLine() ?>'
            };
        }());

        function report_exception()
        {
            var notice = document.getElementById('notice'), message;

            notice.innerHTML = "Opening email application...";
            notice.style.display = 'block';

            var message = 'Please replace this line with an description of what you were doing when encounter this error.%0A%0A';

            message += exception.subject + ' error occurred '
                    + exception.time + ' in '
                    + exception.file + ' on line '
                    + exception.line + ':%0A------------------------------%0A';
            message += 'Server: ' + exception.server + '%0A'
                    + 'Details: ' + exception.message;

            window.location.href = 'mailto:'
                    + exception.receiver.name + ' <' + exception.receiver.addr
                    + '>?subject=OpenExam Exception (' + exception.subject + ')&body='
                    + message;

            return false;
        }
</script>
