<?php
/*
 * Copyright (C) 2016-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    script.phtml
// Created: 2016-12-12 00:14:42
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<script>
        var exception = (function ()
        {
            return {
                server: "<?= gethostname() ?>",
                subject: "<?= $error->getString() ?>",
                message: "<?= $error->getMessage() ?>",
                receiver: <?= json_encode($contact) ?>,
                time: "<?= strftime('%F %T') ?>",
                file: "<?= basename($error->getException()->getFile()) ?>",
                line: "<?= $error->getException()->getLine() ?>"
            };
        }());

        function report_exception()
        {
            var notice = document.getElementById('notice'), message;

            notice.innerHTML = "Opening email application...";
            notice.style.display = 'block';

            var message = 'Please replace this line with an description of what you were doing when encounter this error.%0A%0A';

            message += exception.subject + ' error occurred '
                    + exception.time + ' in '
                    + exception.file + ' on line '
                    + exception.line + ':%0A------------------------------%0A';
            message += 'Server: ' + exception.server + '%0A'
                    + 'Details: ' + exception.message;

            window.location.href = 'mailto:'
                    + exception.receiver.name + ' <' + exception.receiver.addr
                    + '>?subject=OpenExam Exception (' + exception.subject + ')&body='
                    + message;

            return false;
        }
</script>
