<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    style.phtml
// Created: 2016-12-12 00:14:28
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<style>
    .oe-error h2.message {
        margin-left: 0
    }
    .oe-error  p.message {
        margin: 10px;
        padding: 10px;
        background-color: #eeeeee;
    }
    .oe-error div.info {
        padding: 10px;
    }
    .oe-error button {
        min-width: 80px;
    }
</style>
