<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    index.phtml
// Created: 2016-05-25 14:26:27
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<style>
    div.mbox {
        padding: 12px;
        margin: 10px;
        margin-top: 50px;
        box-shadow: 1px 1px 6px #999999;
        border-radius: 10px 10px 10px 10px;
        background: #ffffff;
        max-width: 1024px;
    }
</style>

<div class="mbox">
    <h1>System Diagnostics</h1>

    <button id="monitor" class="btn btn-primary">Monitors...</button>
</div>

<script>
        $("#monitor").click(function () {
            location.href = "performance/monitor";
        })
</script>