<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    monitor.phtml
// Created: 2016-05-25 14:26:46
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<style>
    div.mbox {
        padding: 12px;
        margin: 10px;
        margin-top: 50px;
        box-shadow: 1px 1px 6px #999999;
        border-radius: 10px 10px 10px 10px;
        background: #ffffff;
        max-width: 1024px;
    }
    div.monitor {
        display: none;
    }
    div.counter {
        margin: 10px;
        width: 420px;
        height: 300px;
        border: 2px solid #eeeeee;
        border-radius: 5px;
        display: inline-block;
    }
    div.counter .header {
        padding-left: 10px;
        padding-top: 7px;
    }
    div.sources, div.delta {
        float: right;
        padding-left: 20px;
    }
    span.title {
        font-weight: bold;
        font-size: 1.2em;
        margin-left: 10px;
    }
    div.monitor-buttons button {
        margin-left: 10px;
    }
    button.counter {
        min-width: 100px;
    }
</style>

<div class="mbox">
    <h1>Performance Monitor</h1>
    <div id="monitor-wrapper">
        <!-- navigation buttons -->
        <div class="monitor-buttons"></div>
        <!-- monitor panels -->
        <div class="monitor-content"></div>
    </div>
</div>

<script src="<?= $this->url->get('js/chart.js') ?>"></script>
<script src="<?= $this->url->get('js/views/diagnostics/performance/counters.js') ?>"></script>

<script>
        $(document).ready(function () {

            // 
            // Fetch bootstrap data using AJAX.
            // 
            function fetch(url, callback) {
                $.ajax({
                    type: "GET",
                    url: url,
                    success: function (resp) {
                        callback(JSON.parse(resp));
                    }
                });
            }

            // 
            // Called to dynamic initialize buttons and activate first
            // performance counter.
            // 
            function initialize(content) {
                for (var type in content) {
                    $("div.monitor-content").append("<div class=\"monitor " + type + "\"></div>");
                    $("div.monitor-buttons").append("<button id=\"" + type + "\" class=\"btn btn-primary\">" + content[type].name + "</button>");
                }

                $("div.monitor-buttons").append("<div class=\"delta selectpicker\"><input type=\"checkbox\" id=\"delta\" checked> Delta Mode</input></div>");
                $("div.monitor-buttons").append("<div class=\"sources\"></div>");

                var first = Object.keys(content)[0];
                activate(first, $("div ." + first));

                // 
                // On monitor change:
                // 
                $("button").click(function () {
                    var monitor = $(this).attr('id');
                    var context = $("div ." + monitor);

                    $("button").addClass("btn-primary");

                    activate(monitor, context);
                });
                
                // 
                // On delta mode change:
                // 
                $("#delta").click(function () {
                        counters.setDelta($(this).prop('checked'));
                        counters.reopen();
                        counters.start();
                });
            }

            // 
            // Tell counters object to close/destroy any opened counters
            // and initialize itself with performance counter data for
            // selected monitor.
            // 
            function activate(monitor, context) {
                $("div .monitor").hide();
                $("div ." + monitor).show();

                $("button#" + monitor).toggleClass("btn-primary");

                counters.close();
                counters.open(monitor, context);
                counters.setDelta($(this).prop('checked'));
                counters.start();

                fetch(baseURL + 'utility/diagnostics/performance/' + monitor + '?name=1', sources);
            }

            // 
            // Load counter sources. This is an array of availible names 
            // within this monitor.
            // 
            function sources(content) {
                $("div.sources").empty();

                if (content.name === false) {
                    counters.setSource(0);
                } else {
                    var length = content.name.length, select;

                    select = "<select class=\"sources\" id=\"sources\">";
                    for (var i = 0; i < length; ++i) {
                        select += "<option name=\"" + content.name[i] + "\">" + content.name[i] + "</option>";
                    }
                    select += "</select>";

                    $("div.sources").append(select);
                    $("#sources").change(function () {
                        counters.setSource($(this).val());
                    });

                    counters.setSource(content.name[0]);
                }
            }

            counters.setUrl(baseURL + 'utility/diagnostics/performance');
            counters.setLimit(20);
            counters.setInterval(5);

            fetch(baseURL + 'utility/diagnostics/performance', initialize);
        })
</script>
