<?php
// 
// The source code is copyrighted, with equal shared rights, between the
// authors (see the file AUTHORS) and the OpenExam project, Uppsala University 
// unless otherwise explicit stated elsewhere.
// 
// File:    monitor.phtml
// Created: 2016-05-25 14:26:46
// 
// Author:  Anders Lövgren (QNET/BMC CompDept)
// 

?>

<style>
    div.mbox {
        padding: 12px;
        margin: 10px;
        margin-top: 50px;
        box-shadow: 1px 1px 6px #999999;
        border-radius: 10px 10px 10px 10px;
        background: #ffffff;
        max-width: 1024px;
    }
    div.monitor {
        display: none;
    }
    div.counter {
        margin: 10px;
        width: 420px;
        height: 300px;
        border: 2px solid #eeeeee;
        border-radius: 5px;
        display: inline-block;
    }
    div.counter .header {
        padding-left: 10px;
        padding-top: 7px;
    }
    span.title {
        font-weight: bold;
        font-size: 1.2em;
        margin-left: 10px;
    }
    div.monitor-buttons button {
            margin-left: 10px;
    }
    button.counter {
        min-width: 100px;
    }
</style>

<div class="mbox">
    <h1>Performance Monitor</h1>
    <div id="monitor-wrapper">
        <!-- navigation buttons -->
        <div class="monitor-buttons"></div>
        <!-- monitor panels -->
        <div class="monitor-content"></div>
    </div>
</div>

<script src="<?= $this->url->get('js/chart.js') ?>"></script>
<script src="<?= $this->url->get('js/views/diagnostics/performance/counters.js') ?>"></script>

<script>
        $(document).ready(function () {

            // 
            // Fetch bootstrap data using AJAX.
            // 
            function fetch(url, callback) {
                $.ajax({
                    type: "GET",
                    url: url,
                    success: function (resp) {
                        callback(JSON.parse(resp));
                    }
                });
            }

            // 
            // Called to dynamic initialize buttons and activate first
            // performance counter.
            // 
            function initialize(content) {
                for (var type in content) {
                    $("div.monitor-content").append("<div class=\"monitor " + type + "\"></div>");
                    $("div.monitor-buttons").append("<button id=\"" + type + "\" class=\"btn btn-primary\">" + content[type].name + "</button>");
                }

                var first = Object.keys(content)[0];
                activate(first, $("div ." + first));

                $("button").click(function () {
                    var monitor = $(this).attr('id');
                    var context = $("div ." + monitor);

                    $("button").addClass("btn-primary");

                    activate(monitor, context);
                });
            }

            // 
            // Tell counters object to close/destroy any opened counters
            // and initialize itself with performance counter data for
            // selected monitor.
            // 
            function activate(monitor, context) {
                $("div .monitor").hide();
                $("div ." + monitor).show();

                $("button#" + monitor).toggleClass("btn-primary");

                counters.close();
                counters.open(monitor, context);
                counters.start();
            }

            counters.setUrl(baseURL + 'utility/diagnostics/performance');
            counters.setLimit(20);
            counters.setInterval(5);

            fetch(baseURL + 'utility/diagnostics/performance', initialize);
        })
</script>
